### PR TITLE
radclient: Remove '-q'

### PR DESCRIPTION
**Pull request by jpereira**
It's no longer used

### CODE REVIEW

**Comment by jpereira** [comment]
The current radclient is printing nothing when we send a requests.

e.g:

```
[jpereira@jorge-sugarloaf freeradius-server.git]$ ./build/bin/local/radclient -f ../packet-auth.txt -D share/dictionary 127.0.0.1:1812 auth testing123
[jpereira@jorge-sugarloaf freeradius-server.git]$
```

The patch fix bring back the previous behavior printing the packet types,id, .. as can be seen below.

1. print the headers by default.

```
[jpereira@jorge-sugarloaf freeradius-server.git]$ ./build/bin/local/radclient -f ../packet-auth.txt -D share/dictionary 127.0.0.1:1812 auth testing123
Sent Access-Request Id 206 from 0.0.0.0:52002 to 127.0.0.1:1812 length 43
Received Access-Accept Id 206 from 127.0.0.1:1812 to 0.0.0.0:52002 via lo0 length 20
[jpereira@jorge-sugarloaf freeradius-server.git]$
```

2. processing `-x` normally.

```
[jpereira@jorge-sugarloaf freeradius-server.git]$ ./build/bin/local/radclient -x -f ../packet-auth.txt -D share/dictionary 127.0.0.1:1812 auth testing123
Sent Access-Request Id 94 from 0.0.0.0:60417 to 127.0.0.1:1812 length 43
	Cleartext-Password = "hello"
	User-Name = "bob"
	User-Password = "hello"
Received Access-Accept Id 94 from 127.0.0.1:1812 to 0.0.0.0:60417 via lo0 length 20
[jpereira@jorge-sugarloaf freeradius-server.git]$
```

3. Of course, if `-q`, do nothing.

```
[jpereira@jorge-sugarloaf freeradius-server.git]$ ./build/bin/local/radclient -q -xxx -f ../packet-auth.txt -D share/dictionary 127.0.0.1:1812 auth testing123
[jpereira@jorge-sugarloaf freeradius-server.git]$
```

**Comment by arr2036** [comment]
Nothing _should_ be printed unless there's an error.

**Comment by jpereira** [comment]
well, but it is expected to be different than the older versions like Radclient from fr 1.x, fr 2.x, and fr 3.x ? even the option `-q` is expected to mute everything. or not?

**Comment by arr2036** [comment]
`-q` should be removed.  If you don't want output, don't pass `-x`.

**Comment by jpereira** [comment]
Ok, I updated the pr dropping the `-q`

**Pull request merged**
