### PR TITLE
radeapclient - eap context struct

### PR DESCRIPTION
**Pull request by nchaigne**
Definition of a structure which will hold the EAP context information.
This will also make easier to merge with radclient later on.

As requested, small commits on purpose. If they are too small please let
me know, I will adjust :)

### CODE REVIEW

**Comment by arr2036** [comment]
A little larger :)

The idea is to group multiple related commits together in a single pull request. The commits themselves should be small, the pull request doesn't have to be.

**Comment by nchaigne** [comment]
Alright, then I'll do more small commits, and we'll try to agree when they are sufficient for a merge :)
I think it would be better for me to wait after each commit, so you can review it before I carry on. That way if you disagree with the changes I won't have lost much time.
What do you think ?

**Comment by arr2036** [comment]
Sure. GitHub also keeps pull requests live. So if you push more commits to a branch a pull request originated on, they appear in the pull request.

Just comment when you want review and we can check over the latest commits.

**Comment by nchaigne** [comment]
I'm done for today.
Can you please take a look before I carry on ?
Thanks!

**Comment by arr2036** [comment]
Looks ok so far. Would still prefer the two utilities to be merged... but oh well...

**Comment by nchaigne** [comment]
Yeah but I thought it would be too complicated to begin with (small steps, remember !). Also, I plan to do the parallelism differently than in radclient, and I didn't want to impact people using this tool.
But maybe later...

**Comment by nchaigne** [comment]
Last commit for today.
Can you please take a look ?
Thanks again :)

(The union is still to be done. But it's not forgotten).

**Comment by arr2036** [comment]
OK :) Yep looks ok. Just fix the issue that broke the build

**Comment by arr2036** [comment]
and it's vp->vp_length (vp_length is a macro)

**Comment by nchaigne** [comment]
Alright, I'm done for today.
I've also checked all the commits on radeapclient since last summer to be sure I didn't break anything changed since then.

Can you review again ?
Thanks!

If you don't have more comments, I believe this is in a good shape for a merge :)

**Comment by nchaigne** [comment]
So... nothing more to add ?
Does this mean everything is ok and that it can be merged into FreeRADIUS ?
(I'm pushing a bit, I don't want this to wait one more year ^^)

**Pull request merged**
