### PR TITLE
Fix problems with freeradius-dhcp*.deb, refs #1125

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
@alandekok Now is ok.

**Comment by jpereira** [comment]
Hi @alandekok, could you please merge this?

**Comment by qnet-herwin** [comment]
The lines with `diff --git` and `index` shouldn't be in `radiusd-to-freeradius.diff`. The same thing goes for the appendixes at the line indexes (like `LDFLAGS = $(OPENSSL_LDFLAGS) $(TALLOC_LDFLAGS) @LDFLAGS@`). They clutter the visible changes for this change.

Also, I don't think the file `radiusd-to-freeradius.diff` is the correct one to change DHCP fro a default module, it should belong in a new module.

**Comment by alandekok** [comment]
I agree with herwin here.

**Comment by jpereira** [comment]
The idea of ```radiusd-to-freeradius.diff``` file is to register the differences. remember everyone that the *.diff is out of date. the ```LDFLAGS = $(OPENSSL_LDFLAGS) $(TALLOC_LDFLAGS) @LDFLAGS@``` exist in the Make.inc.in from HEAD but not in the current *.diff

**Comment by alandekok** [comment]
> The idea of radiusd-to-freeradius.diff file is to register the differences.

Which make "radiusd" into the debian "freeradius".

A change with a different purpose should be a different patch.

**Comment by jpereira** [comment]
Ok, In this case the idea is move the changes to another *.diff. right?

**Comment by alandekok** [comment]
Yes.

**Comment by jpereira** [comment]
@alandekok done!

**Comment by jpereira** [comment]
Hi @arr2036 !

have plans to look this? This issue during the *.deb build is very boring.

**Pull request merged**
