### PR TITLE
Extend the H3C dictionary based on public manuals

### PR DESCRIPTION
**Pull request by zhangyoufu**
type may be inaccurate

### CODE REVIEW

**Comment by zhangyoufu** [comment]
based on Googling `site:h3c.com "Vendor Id 25506"`

**Comment by arr2036** [comment]
Need commits to be signed before we can merge this.

**Comment by arr2036** [comment]
Content looks fine though

**Comment by zhangyoufu** [comment]
> Need commits to be signed before we can merge this.

Commit is now signed and rebased.

**Pull request merged**
