### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by arr2036** [comment]
Where are these actually freed?

**Comment by jpereira** [comment]
Not in use.

```
[jpereira@sugarloaf freeradius-server-v3.0.x.git]$ egrep "wide_(path|name)" src/modules/rlm_python3/*
src/modules/rlm_python3/rlm_python3.c:		//if (inst->wide_name) PyMem_RawFree(inst->wide_name);
src/modules/rlm_python3/rlm_python3.c:		//if (inst->wide_path) PyMem_RawFree(inst->wide_path);
[jpereira@sugarloaf freeradius-server-v3.0.x.git]$
```

**Comment by arr2036** [comment]
Your grep foo sucks :P 

https://github.com/FreeRADIUS/freeradius-server/blob/d60da6b9c7c7323fc39fb31e944e53f2472d62cb/src/modules/rlm_python3/rlm_python3.c#L1118

**Comment by jpereira** [comment]
No way! 😆 

```
[jpereira@sugarloaf freeradius-server.git]$ git co v3.0.x
Already on 'v3.0.x'
Your branch is up to date with 'upstream/v3.0.x'.
[jpereira@sugarloaf freeradius-server.git]$ git pull --rebase upstream v3.0.x
From github.com:FreeRADIUS/freeradius-server
 * branch                  v3.0.x     -> FETCH_HEAD
Already up to date.
Current branch v3.0.x is up to date.
[jpereira@sugarloaf freeradius-server.git]$ egrep "wide_(path|name)" src/modules/rlm_python3/*
src/modules/rlm_python3/rlm_python3.c:		//if (inst->wide_name) PyMem_RawFree(inst->wide_name);
src/modules/rlm_python3/rlm_python3.c:		//if (inst->wide_path) PyMem_RawFree(inst->wide_path);
[jpereira@sugarloaf freeradius-server.git]$```

Update your local repo.

**Comment by arr2036** [comment]
Ah, it's because this is against a commit older than the v3.0.x HEAD.

**Comment by jpereira** [comment]
yep! I noticed it now too. thanks

**Pull request merged**
