### PR TITLE
Master CI time saving

### PR DESCRIPTION
**Pull request by terryburton**

### CODE REVIEW

**Comment by arr2036** [comment]
I saw there's a wrapper around apt called 'apt-fast' that parallelises downloads we might want to look into too.

**Comment by terryburton** [comment]
I think apt-fast may optimise the wrong thing. The data transfer actually quite fast:

```
2020-11-11T23:06:33.0395818Z Get:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libwbclient-dev amd64 2:4.7.6+dfsg~ubuntu-0ubuntu2.21 [12.5 kB]
2020-11-11T23:06:33.0412781Z Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 autopoint all 0.19.8.1-6ubuntu0.3 [426 kB]
2020-11-11T23:06:33.0552026Z Get:3 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 dh-autoreconf all 17 [15.8 kB]
2020-11-11T23:06:33.0558422Z Get:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libarchive-zip-perl all 1.60-1ubuntu0.1 [84.6 kB]
2020-11-11T23:06:33.0596455Z Get:5 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libfile-stripnondeterminism-perl all 0.040-1.1~build1 [13.8 kB]
2020-11-11T23:06:33.0601552Z Get:6 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 dh-strip-nondeterminism all 0.040-1.1~build1 [5208 B]
2020-11-11T23:06:33.0606831Z Get:7 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 gettext amd64 0.19.8.1-6ubuntu0.3 [1293 kB]
2020-11-11T23:06:33.0815459Z Get:8 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 intltool-debian all 0.35.0+20060710.4 [24.9 kB]
2020-11-11T23:06:33.0820024Z Get:9 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 po-debconf all 1.0.20 [232 kB]
2020-11-11T23:06:33.0851630Z Get:10 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 debhelper all 11.1.6ubuntu2 [902 kB]
2020-11-11T23:06:33.1006573Z Get:11 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libfile-which-perl all 1.21-1 [11.8 kB]
2020-11-11T23:06:33.1013067Z Get:12 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libfile-homedir-perl all 1.002-1 [37.1 kB]
2020-11-11T23:06:33.1020138Z Get:13 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 devscripts amd64 2.17.12ubuntu1.1 [870 kB]
2020-11-11T23:06:33.1156904Z Get:14 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 dh-make all 2.201701 [31.6 kB]
2020-11-11T23:06:33.1163519Z Get:15 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 diffstat amd64 1.61-1build1 [24.1 kB]
2020-11-11T23:06:33.1171007Z Get:16 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 dovecot-dev amd64 1:2.2.33.2-1ubuntu4.6 [308 kB]
2020-11-11T23:06:33.1226160Z Get:17 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libib-util amd64 3.0.2.32703.ds4-11ubuntu2 [3248 B]
2020-11-11T23:06:33.1231356Z Get:18 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 firebird-dev amd64 3.0.2.32703.ds4-11ubuntu2 [117 kB]
2020-11-11T23:06:33.1245870Z Get:19 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libct4 amd64 1.00.82-2ubuntu0.1 [147 kB]
2020-11-11T23:06:33.1271049Z Get:20 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 freetds-dev amd64 1.00.82-2ubuntu0.1 [258 kB]
2020-11-11T23:06:33.1315898Z Get:21 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgssrpc4 amd64 1.16-2ubuntu0.1 [54.2 kB]
2020-11-11T23:06:33.1325995Z Get:22 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libkdb5-9 amd64 1.16-2ubuntu0.1 [37.2 kB]
2020-11-11T23:06:33.1334062Z Get:23 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libkadm5srv-mit11 amd64 1.16-2ubuntu0.1 [49.7 kB]
2020-11-11T23:06:33.1358199Z Get:24 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libkadm5clnt-mit11 amd64 1.16-2ubuntu0.1 [38.2 kB]
2020-11-11T23:06:33.1365912Z Get:25 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 comerr-dev amd64 2.1-1.44.1-1ubuntu1.3 [38.5 kB]
2020-11-11T23:06:33.1380627Z Get:26 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 krb5-multidev amd64 1.16-2ubuntu0.1 [120 kB]
2020-11-11T23:06:33.1394442Z Get:27 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libapt-pkg-perl amd64 0.1.33build1 [68.0 kB]
2020-11-11T23:06:33.1405160Z Get:28 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libcap-dev amd64 1:2.25-1.2 [23.2 kB]
2020-11-11T23:06:33.1411755Z Get:29 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libsub-name-perl amd64 0.21-1build1 [11.6 kB]
2020-11-11T23:06:33.1418630Z Get:30 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libclass-accessor-perl all 0.51-1 [21.2 kB]
2020-11-11T23:06:33.1424736Z Get:31 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libclone-perl amd64 0.39-1 [10.4 kB]
2020-11-11T23:06:33.1430400Z Get:32 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libcollectdclient1 amd64 5.7.2-2ubuntu1.2 [44.1 kB]
2020-11-11T23:06:33.1435990Z Get:33 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libcollectdclient-dev amd64 5.7.2-2ubuntu1.2 [12.1 kB]
2020-11-11T23:06:33.1441562Z Get:34 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcurl4-openssl-dev amd64 7.58.0-2ubuntu3.10 [294 kB]
2020-11-11T23:06:33.1484154Z Get:35 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libdigest-hmac-perl all 1.03+dfsg-1 [12.1 kB]
2020-11-11T23:06:33.1489588Z Get:36 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libsocket6-perl amd64 0.27-1build2 [23.0 kB]
2020-11-11T23:06:33.1494879Z Get:37 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libio-socket-inet6-perl all 2.72-2 [13.8 kB]
2020-11-11T23:06:33.1499584Z Get:38 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libnet-ip-perl all 1.26-1 [31.5 kB]
2020-11-11T23:06:33.1505815Z Get:39 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libnet-dns-perl all 1.10-2 [335 kB]
2020-11-11T23:06:33.1544345Z Get:40 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libnet-domain-tld-perl all 1.75-1 [29.1 kB]
2020-11-11T23:06:33.1549593Z Get:41 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libemail-valid-perl all 1.202-1 [16.3 kB]
2020-11-11T23:06:33.1554232Z Get:42 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libexporter-tiny-perl all 1.000000-2 [34.6 kB]
2020-11-11T23:06:33.1558812Z Get:43 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libgdbm-dev amd64 1.14.1-6 [79.3 kB]
2020-11-11T23:06:33.1570711Z Get:44 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libtcmalloc-minimal4 amd64 2.5-2.2ubuntu3 [91.6 kB]
2020-11-11T23:06:33.1583552Z Get:45 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libgoogle-perftools4 amd64 2.5-2.2ubuntu3 [190 kB]
2020-11-11T23:06:33.1608293Z Get:46 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libunwind-dev amd64 1.2.1-8 [423 kB]
2020-11-11T23:06:33.1667649Z Get:47 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libgoogle-perftools-dev amd64 2.5-2.2ubuntu3 [204 kB]
2020-11-11T23:06:33.1695262Z Get:48 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libhashkit2 amd64 1.0.18-4.2ubuntu0.18.04.1 [35.4 kB]
2020-11-11T23:06:33.1703444Z Get:49 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libhashkit-dev amd64 1.0.18-4.2ubuntu0.18.04.1 [23.9 kB]
2020-11-11T23:06:33.1709144Z Get:50 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libhiredis0.13 amd64 0.13.3-2.2 [25.3 kB]
2020-11-11T23:06:33.1713848Z Get:51 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libhiredis-dev amd64 0.13.3-2.2 [39.6 kB]
2020-11-11T23:06:33.1721762Z Get:52 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libidn11-dev amd64 1.33-2.1ubuntu1.2 [520 kB]
2020-11-11T23:06:33.1805587Z Get:53 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libio-pty-perl amd64 1:1.08-1.1build4 [30.1 kB]
2020-11-11T23:06:33.1810267Z Get:54 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libio-string-perl all 1.08-3 [11.1 kB]
2020-11-11T23:06:33.1814778Z Get:55 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libiodbc2 amd64 3.52.9-2.1 [140 kB]
2020-11-11T23:06:33.1835793Z Get:56 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libiodbc2-dev amd64 3.52.9-2.1 [36.3 kB]
2020-11-11T23:06:33.1841182Z Get:57 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libipc-run-perl all 0.96-1 [89.9 kB]
2020-11-11T23:06:33.1853438Z Get:58 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libjson-perl all 2.97001-1 [73.3 kB]
2020-11-11T23:06:33.1865228Z Get:59 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 liblist-moreutils-perl amd64 0.416-1build3 [55.5 kB]
2020-11-11T23:06:33.1873886Z Get:60 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libluajit-5.1-common all 2.1.0~beta3+dfsg-5.1 [44.3 kB]
2020-11-11T23:06:33.1880463Z Get:61 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libluajit-5.1-2 amd64 2.1.0~beta3+dfsg-5.1 [227 kB]
2020-11-11T23:06:33.1913249Z Get:62 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libluajit-5.1-dev amd64 2.1.0~beta3+dfsg-5.1 [243 kB]
2020-11-11T23:06:33.1944029Z Get:63 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libmemcachedutil2 amd64 1.0.18-4.2ubuntu0.18.04.1 [9532 B]
2020-11-11T23:06:33.1949920Z Get:64 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libnl-3-dev amd64 3.2.29-0ubuntu3 [90.6 kB]
2020-11-11T23:06:33.1964589Z Get:65 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libnl-genl-3-dev amd64 3.2.29-0ubuntu3 [10.7 kB]
2020-11-11T23:06:33.1966075Z Get:66 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpam0g-dev amd64 1.1.8-3.6ubuntu2.18.04.2 [110 kB]
2020-11-11T23:06:33.2002998Z Get:67 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libparse-debianchangelog-perl all 1.2.0-12 [49.5 kB]
2020-11-11T23:06:33.2010555Z Get:68 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpcap0.8-dev amd64 1.8.1-6ubuntu1.18.04.2 [218 kB]
2020-11-11T23:06:33.2050999Z Get:69 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpcap-dev amd64 1.8.1-6ubuntu1.18.04.2 [3480 B]
2020-11-11T23:06:33.2052502Z Get:70 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libudev-dev amd64 237-3ubuntu10.42 [19.1 kB]
2020-11-11T23:06:33.2064873Z Get:71 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpci-dev amd64 1:3.5.2-1ubuntu1.1 [43.5 kB]
2020-11-11T23:06:33.2075587Z Get:72 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libperl-dev amd64 5.26.1-6ubuntu0.5 [2862 kB]
2020-11-11T23:06:33.2563208Z Get:73 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libpython-all-dev amd64 2.7.15~rc1-1 [1092 B]
2020-11-11T23:06:33.2566329Z Get:74 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libsasl2-dev amd64 2.1.27~101-g0780600+dfsg-3ubuntu2.1 [256 kB]
2020-11-11T23:06:33.2591771Z Get:75 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libwrap0-dev amd64 7.6.q-27 [21.5 kB]
2020-11-11T23:06:33.2597265Z Get:76 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libsensors4-dev amd64 1:3.4.0-4 [34.6 kB]
2020-11-11T23:06:33.2612984Z Get:77 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libsnmp-dev amd64 5.7.3+dfsg-1.8ubuntu3.6 [1093 kB]
2020-11-11T23:06:33.2790934Z Get:78 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libtalloc-dev amd64 2.1.10-2ubuntu1 [60.0 kB]
2020-11-11T23:06:33.2799764Z Get:79 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libtext-levenshtein-perl all 0.13-1 [9612 B]
2020-11-11T23:06:33.2805800Z Get:80 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libunbound2 amd64 1.6.7-1ubuntu2.3 [267 kB]
2020-11-11T23:06:33.2850678Z Get:81 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libunbound-dev amd64 1.6.7-1ubuntu2.3 [5712 kB]
2020-11-11T23:06:33.3800091Z Get:82 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libxml-simple-perl all 2.24-1 [63.6 kB]
2020-11-11T23:06:33.3838779Z Get:83 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libyaml-libyaml-perl amd64 0.69+repack-1 [26.4 kB]
2020-11-11T23:06:33.3840328Z Get:84 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libykclient3 amd64 2.15-1 [22.3 kB]
2020-11-11T23:06:33.3842157Z Get:85 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libykclient-dev amd64 2.15-1 [24.9 kB]
2020-11-11T23:06:33.3845240Z Get:86 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libyubikey0 amd64 1.13-2 [7452 B]
2020-11-11T23:06:33.3847564Z Get:87 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libyubikey-dev amd64 1.13-2 [14.3 kB]
2020-11-11T23:06:33.3850076Z Get:88 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 patchutils amd64 0.3.4-2 [71.1 kB]
2020-11-11T23:06:33.3852314Z Get:89 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 t1utils amd64 1.41-2 [56.0 kB]
2020-11-11T23:06:33.3858352Z Get:90 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 lintian all 2.5.81ubuntu1 [847 kB]
2020-11-11T23:06:33.3955091Z Get:91 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 luajit amd64 2.1.0~beta3+dfsg-5.1 [229 kB]
2020-11-11T23:06:33.3985243Z Get:92 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 quilt all 0.63-8.2 [293 kB]
2020-11-11T23:06:33.4023372Z Get:93 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 debootstrap all 1.0.95ubuntu0.8 [35.3 kB]
2020-11-11T23:06:33.4031157Z Get:94 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libjson-c-dev amd64 0.12.1-1.3ubuntu0.3 [31.9 kB]
2020-11-11T23:06:33.4036701Z Get:95 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libkqueue0 amd64 2.0.3-1.1 [23.3 kB]
2020-11-11T23:06:33.4042152Z Get:96 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libkqueue-dev amd64 2.0.3-1.1 [32.5 kB]
2020-11-11T23:06:33.4047359Z Get:97 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libkrb5-dev amd64 1.16-2ubuntu0.1 [11.8 kB]
2020-11-11T23:06:33.4052753Z Get:98 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libldap2-dev amd64 2.4.45+dfsg-1ubuntu1.7 [261 kB]
2020-11-11T23:06:33.4094678Z Get:99 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libmemcached-dev amd64 1.0.18-4.2ubuntu0.18.04.1 [238 kB]
2020-11-11T23:06:33.4134164Z Get:100 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 pbuilder all 0.229.1 [317 kB]
```

**Comment by arr2036** [comment]
Mmm, yes.  Well this seems to more than halve the install time for the common dependencies so seems good to me!

**Comment by arr2036** [comment]
Also saves LFS bandwidth which isn't free.

**Pull request merged**
