### PR TITLE
rlm_detail: Set maximum value of poll_interval to 300

### PR DESCRIPTION
**Pull request by jpereira**
Give the option to up the maximum interval.

### CODE REVIEW

**Comment by alandekok** [comment]
Why is this change necessary?

**Comment by jpereira** [comment]
I have a lot of unnecessary messages in the log. because, I had some problems during creation/receiving of acct packets using the "buffered-sql"

And after increasing the value, I solve the boring messages.

**Comment by alandekok** [comment]
It's better to fix the messages than to put a band-aid on it.

**Comment by jpereira** [comment]
@alandekok haha! I know.... I Know, but just give us the option to increase the value. Just it! :beer:

**Comment by alanbuxey** [comment]
why stop at 300? why 5 minutes maximum poll?  there are issues with such a
large poll time - the size of the detail file being one(!)  but
what issue were you having that meant a poll time of eg 60 seconds was a
problem?  what aggressiveness value were ou using etc?  if this value is to
be changed
then maybe make 1 hour - 3600 - the maximum value?

alan

**Pull request closed without merging**
