### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Misspellings found by [codespell](https://github.com/codespell-project/codespell).

### CODE REVIEW

**Comment by arr2036** [comment]
Please submit against the config files themselves not the auto-generated documentation see 'raddb'

**Comment by DimitriPapadopoulos** [comment]
See #5252.

**Comment by DimitriPapadopoulos** [comment]
However most typos originate in the `*.adoc` themselves files as far as I can see. Why close the whole pull request?

**Comment by DimitriPapadopoulos** [comment]
I have read [`raddb/README.adoc`](https://github.com/FreeRADIUS/freeradius-server/blob/master/raddb/README.adoc) and it states:
> All of the documentation, READMEs, etc. for this directory are now stored in the doc/raddb directory, which is a soft link to the Asciidoc source

@arr2036 I have not modified `doc/raddb`: I changed files under the symlink target `doc/antora/modules/raddb/pages`  and more generally under `doc/antora/modules/reference`. I fail to find the same typos elsewhere, so I cannot find source files that would be used to generate the ones I have fixed. Could you please provide an additional hint?

**Comment by mcnewton** [comment]
Merged manually, thanks.

@DimitriPapadopoulos I think it was actually only one file that was generated - if you edit files in `raddb` and then run `make asciidoc` it will recreate the Antora raddb documentation automatically.

**Comment by alandekok** [comment]
The files in `doc/antora/modules/raddb/pages` are auto-generated from the files in `raddb`.  Please submit changes against the originals, not against the auto-generated versions.

I've pushed a minor fix to the build in commit b935f9a8ae28

You can edit the files such as `raddb/mods-enabled/ldap`, and then do:

```
$ make doc.raddb
```

and it will be automatically converted.

**Pull request closed without merging**
