### PR TITLE
move the dladdr() call to dl_get_pathname() to avoid a lot of ifdef()

### PR DESCRIPTION
**Pull request by jpereira**
@alandekok I noticed that dladdr() exist in the main unix systems... so, _dl_get_pathname() always will be used and could be reused!

### CODE REVIEW

**Comment by jpereira** [comment]
@alandekok I noticed that dladdr() exist in the main unix systems... so, ```_dl_get_pathname()``` always will be used and could be reused!

**Comment by arr2036** [comment]
TBH i'd rather use the documented function if we're using non standard functions :)

**Comment by jpereira** [comment]
@arr2036 prefer wihout /* comments */?

**Comment by jpereira** [comment]
@arr2036 done!

**Comment by jpereira** [comment]
@arr2036 I did the changes. but for this work you need to apply this fix https://github.com/FreeRADIUS/freeradius-server/pull/1119

**Pull request closed without merging**
