### PR TITLE
add debian libwbclient-dev path

### PR DESCRIPTION
**Pull request by clementhk**
https://packages.debian.org/jessie/amd64/libwbclient-dev/filelist

### CODE REVIEW

**Comment by clementhk** [comment]
Please also cherry-pick to 3.0 if possible. :)

**Comment by arr2036** [comment]
you need to edit configure.ac, and regenerate the configure file.

**Comment by clementhk** [comment]
Hi @arr2036,

I think I'll skip this and leave it to you guys as my autoconf (2.69) is generating very different configure file.

**Comment by arr2036** [comment]
``autoconf -I ../../../``

**Pull request closed without merging**
