### PR TITLE
remove rest of -m option

### PR DESCRIPTION
**Pull request by mcnewton**

### CODE REVIEW

**Comment by arr2036** [comment]
Ugh, there's so much of it.

**Comment by mcnewton** [comment]
Doesn't surprise me. Small thing like that have a habit of sneakily getting everywhere. AFAICT it was always pretty much meaningless anyway.

**Comment by arr2036** [comment]
It explicitly freed various things.  Without it connections weren't shut down properly, and some exec triggers didn't fire.

**Comment by mcnewton** [comment]
Ah, OK. Makes sense to do by default then anyway.

**Pull request merged**
