### PR TITLE
Add support for Aptilo Access Controller

### PR DESCRIPTION
**Pull request by jpereira**
Adding support for "Aptilo Access Controllers" - http://www.aptilo.com/aptilo-access-controller

@arr2036, please replicate in the v3.1.x

Thanks

### CODE REVIEW

**Comment by alandekok** [comment]
What the heck is the internal dictionary?  I don't think that is ever supposed to go j to a radius packet. And if it is, they don't own vendor ID 666.

  that number is VERY likely to me a they're doing something wrong. And they know it.

**Comment by jpereira** [comment]
@alandekok I updated the branch removing the *.internal. Now if you update, you can notice that has only share/dictionary.aptilo

**Comment by jpereira** [comment]
@alandekok I updated the branch removing the *.internal. Now if you update, you can notice that has only share/dictionary.aptilo

**Comment by arr2036** [comment]
What's the Aptilo at the end of every Attribute definition?

**Comment by arr2036** [comment]
Just use ``BEGIN VENDOR Aptilo`` like every other dictionary.

**Comment by arr2036** [comment]
and ``END VENDOR Aptilo`` at the end.

**Comment by jpereira** [comment]
Hi @arr2036 , check again!

**Comment by arr2036** [comment]
The start should be

```
# -*- text -*-
# Copyright (C) 2015 The FreeRADIUS Server project and contributors
#
VENDOR		Aptilo			13209

BEGIN-VENDOR	Aptilo
```

and you should include it in ``share/dictionary`` else it won't get evaluated during the travis test.

**Comment by jpereira** [comment]
@arr2036 done!

**Comment by arr2036** [comment]
Insert the entry after 139 in share/dictionary to maintain lexicographical ordering

**Comment by jpereira** [comment]
@arr2036 done!

**Pull request merged**
