### PR TITLE
RPM spec file: add missing files + bug bix

### PR DESCRIPTION
**Pull request by pwdng**

### CODE REVIEW

**Comment by arr2036** [comment]
Hm, why would we want rlm_test?

**Comment by arr2036** [comment]
(it's literally a test module for testcases)

**Comment by pwdng** [comment]
Ok, but it that case, it probably shouldn't be in the list of stable modules that get deployed.

**Comment by arr2036** [comment]
Well if it's not in stable it doesn't get built, and then the tests will fail for non development builds.

**Pull request merged**
