### PR TITLE
Deal with remaining missing locks (CIDs listed below)

### PR DESCRIPTION
**Pull request by jejones3141**
CIDs: 1551700, 1551701, 1551704, 1551705

### CODE REVIEW

**Comment by arr2036** [comment]
Github is being weird, can you rebase

**Comment by jejones3141** [comment]
Will do.

**Comment by jejones3141** [comment]
Rebasing shows conflict; will manually merge.

**Comment by jejones3141** [comment]
It was a couple of places where master had &foo->mutex and I had &(foo->mutex). I think I'd seen that elsewhere in FreeRADIUS source, which has some parentheses present only to clearly show the semantics, C being notorious for many precedence levels. I made it consistent with master and pushed.

**Pull request merged**
