### PR TITLE
bring rlm_pap man page up-to-date

### PR DESCRIPTION
**Pull request by mcnewton**

### CODE REVIEW

**Comment by arr2036** [comment]
But I took pity due to it being ~3am where you are... :)

**Comment by mcnewton** [comment]
You could try searching Google for "suspended hyphen", then decide if I was really asleep or not! :)

**Comment by arr2036** [comment]
Never come across those before, or at least never consciously recognised their grammatical importance.  Something new every day :)

**Comment by mcnewton** [comment]
Not like it matters much either way!
Cheers,
Matthew

**Pull request merged**
