### PR TITLE
Feature: maximum FD count & idle timeout for file logging facilities can be configured

### PR DESCRIPTION
**Pull request by lytboris**
Cope with "Too many different filenames" logging issue properly.
64 open log files are not enough for everybody :)
Especially, if you use NAS IP(v6) address as dir name and you have many NASes.

### CODE REVIEW

**Comment by alandekok** [comment]
It would be good to fix the travis build issues.  They don't show up in the current v3.1.x HEAD.

**Comment by lytboris** [comment]
Will do for sure. Would an adopted version go to 3.0.x branch? We had a biiiig bada-boom because of 64 being hardcoded/

**Comment by alandekok** [comment]
The `max_open_logfiles` and `log_idle_timeout` configurations should probably be in a separate sub-section.  e.g.

   limit {
        max_files = 20
        idle_timeout = 30
   }

That way it's a bit clearer what's going on.  We're trying to move towards putting common configuration into common sub-sections.  So the configuration isn't full of `foo_bar_baz`, and `foo_thing_bar` and `foo_egg_drop`.

**Comment by alandekok** [comment]
I'm wary of putting this into v3.0.x.  I'm Ok with upping the limit of 64 there.  But we're trying to keep v3.0.x stable with minimal changes, and no new features.

**Comment by lytboris** [comment]
I will add code to `close oldest file if we have array saturated with opened files and need to open a new one` to both branches and `bump 64 to 256 limit` for 3.0.x.

**Comment by alandekok** [comment]
For v3.0.x, you can just close the oldest one if the server needs a new one.  And bump the limit to 256.

The exfiles API caches files for speed.  It's fine to close an old file, as if that file is needed later, it will just be re-opened.

**Comment by lytboris** [comment]
That is exactly what I was going to do. Closing the oldest file when no empty slot available is needed in 3.1 too obviously.

**Comment by lytboris** [comment]
Alan, should I update this pull request somehow to be merged or you're going to re-write it your way?

**Comment by alandekok** [comment]
I've pushed all changes to v3.0.x, and am working on v3.1.x.

**Pull request closed without merging**
