### PR TITLE
make sure rlm_python does not segfault when using 2 instances and second is called first in a Thread

### PR DESCRIPTION
**Pull request by michael-mri**
First commit is about initializing all instances correctly. I had to make main_thread_state global. Note that only 1 interpreter is used, that means 2 instances are not in separate envs...

Second commit is cleaning of the code as I believe (https://docs.python.org/2/c-api/init.html#non-python-created-threads) PyGILState_* should take care of thread states. This simplifies a bit the code

### CODE REVIEW

**Comment by arr2036** [comment]
Firstly, in future, please discuss pull requests on GitHub so that all contributors can comment.

Secondly i'm pretty certain this change will break TLS within python. There was a reason thread states were swapped in/out explicitly, and bound to the life of the worker threads.

**Comment by arr2036** [comment]
Using a single master state is probably correct, but we'd need to see evidence of testing to make sure your changes don't break TLS within python.

**Comment by michael-mri** [comment]
On 14/05/2015 17:41, Arran Cudbard-Bell wrote:
>
> Firstly, in future, please discuss pull requests on GitHub so that all 
> contributors can comment.
>
Yes ! that is why I did a pull request... I was really not sure of the 
code cleaning that is why I did it in 2 separate commits. My C is bad 
and does need review by others for sure.
But after 2 weeks with no answer I did mention it to Alan directly... 
next time I will post a comment on the pull request.
>
> Secondly i'm pretty certain this change will break TLS within python. 
> There was a reason thread states were swapped in/out explicitly, and 
> bound to the life of the worker threads.
>
Now I know why it was implemented like that :) A comment in the code 
would have been welcome...

**Comment by michael-mri** [comment]
Any hint on how to test TLS in python ?

**Comment by arr2036** [comment]
The log relating to rlm_python.c will contain comments explaining why it was done that way. It'd probably show up in ``git blame`` too.

Use the thread.local API in python to test TLS. The values should persist across multiple calls to the same worker thread.

**Comment by michael-mri** [comment]
On 15/05/2015 15:12, Arran Cudbard-Bell wrote:
>
> The log relating to rlm_python.c will contain comments explaining why 
> it was done that way. It'd probably show up in |git blame| too.
>
True. It was hidden behind "Sync rlm_python and rlm_ldap with master". I 
should have dug deeper.
>
> Use the thread.local API in python to test TLS. The values should 
> persist across multiple calls to the same worker thread.
>
> —
>

Using the test in issue #291, it showed indeed that my changes break TLS :(

However without the cleanup, it does not. Can you review commit 
043adb8e1a51853648f52d46d17867f6eae63beb and integrate it ?
This solve issue #1015 that I just created so things are done properly.

Next time I will stick to the rule "do not fix what is not broken"...

**Pull request merged**
