### PR TITLE
Remove ambiguity from radsniff manpage

### PR DESCRIPTION
**Pull request by terryburton**

### CODE REVIEW

**Comment by arr2036** [comment]
Why is this an ambiguity?

**Comment by terryburton** [comment]
Error may be the right term. `response-filter` and `request-filter` are switched in the parameters for the respective options.

Plain "filter" aligns with the adoc manpage in v4, although I note that it doesn't differentiate between what I presume are BPF filters for PCAP (for `-f`) vs RADIUS attribute filters (for `-r` and `-R`).

**Comment by arr2036** [comment]
Maybe just refer to the filter as 'attribute-filter' to differentiate from the BPF filter.

**Comment by terryburton** [comment]
> Maybe just refer to the filter as 'attribute-filter' to differentiate from the BPF filter.

Done, and also PR for v4. Thanks.

**Comment by arr2036** [comment]
Perfect, thanks! All merged.

**Pull request merged**
