### PR TITLE
Some OCSP fixes

### PR DESCRIPTION
**Pull request by frenche**
Two patches for OCSP and intermediate CA scenario.

### CODE REVIEW

**Comment by frenche** [comment]
See here some pointers on X509_STORE_CTX_get1_issuer() and intermediate CA:
https://bz.apache.org/bugzilla/show_bug.cgi?format=multiple&id=41123

**Comment by frenche** [comment]
I've tested and it looks alright to me, I'll send some more details on mailing-list.

**Comment by frenche** [comment]
Cross ref to the mailing list thread:
http://lists.freeradius.org/pipermail/freeradius-users/2018-January/090245.html

**Comment by frenche** [comment]
Thanks for the tip :-)
Will do.

**Comment by frenche** [comment]
I've ported back the squashed commit from v4 branch.

**Comment by BobiUser69** [comment]
Am 05.04.2018 14:12 schrieb "Alan DeKok" <notifications@github.com>:

**Pull request merged**
