### PR TITLE
Split out the dhcpv6.txt by dhcpv6_rfcXXX.txt

### PR DESCRIPTION
**Pull request by jpereira**
1. Each test entry was moved to the respective rfc. e.g: dhcpv6_rfcXXX.txt
2. Added the `decode-pair -` for all tests.
3. The `dhcpv6.txt` still there.

### CODE REVIEW

**Comment by arr2036** [comment]
The fact that a test used options _from_ a particular RFC does not make them tests _for_ a particular RFC.  The test suite does not exist to advertise our compliance with a particular RFC, the test cases exist to exercise the encoder and decoder.

As agreed with @alandekok, the exception to this are, if an organisation is sponsoring development of a particular feature/implementation of a standard and has requested evidence of compliance, or the RFC has complex structures or types which exercise the encoder or decoder in a "useful" way, i.e. a way that may reveal defects or trigger corner cases.

Splitting out the generic test cases that existed before you started working on the test suite, into separate RFC files because they used test options from those RFCs does not qualify for the exception above.

Splitting those tests out makes it harder to work on the encoder and decoder, because it's impossible to get a good overview of the coverage we already have in the unit tests.

Because the dhcpv6 unit test file was large, I've split out the tests into separate files by type.
Because of the confusion over  when test cases should be split into separate files, we will at some point, redo the type specific tests with an internal dictionary only used for the unit tests.

**Comment by jpereira** [comment]
Ok, btw, the current tests by types do not cover up the `decode-pair -`.

**Comment by arr2036** [comment]
OK, if you could submit a PR to add those, then that'd be useful

**Comment by jpereira** [comment]
Ok

**Pull request closed without merging**
