### PR TITLE
some adjustments for a better error messages.

### PR DESCRIPTION
**Pull request by jpereira**
Hi @arr2036!

Today I had the situation that was necessary to call the 'radiusd' using a directory that the user 'freerad' don't had permissions to read... and was terrible to find  the problem like the below message.

```
......
Wed Jun 24 01:00:55 2015 : Debug:   # Loading module "files" from file /root/teste/mods-enabled/files
Wed Jun 24 01:00:55 2015 : Debug:   files {
Wed Jun 24 01:00:55 2015 : Debug:   	filename = "/root/teste/mods-config/files/authorize"
Wed Jun 24 01:00:55 2015 : Error: Unable to open file "/root/teste/mods-config/files/authorize": 
Wed Jun 24 01:00:55 2015 : Debug:   }
Wed Jun 24 01:00:55 2015 : Error: /root/teste/mods-enabled/files[9]: Invalid configuration for module "files"
......
```

after the adjustments...

```
......
Wed Jun 24 01:00:55 2015 : Debug:   # Loading module "files" from file /root/teste/mods-enabled/files
Wed Jun 24 01:00:55 2015 : Debug:   files {
Wed Jun 24 01:00:55 2015 : Debug:   	filename = "/root/teste/mods-config/files/authorize"
Wed Jun 24 01:00:55 2015 : Error: Unable to open file "/root/teste/mods-config/files/authorize": Permission denied
Wed Jun 24 01:00:55 2015 : Debug:   }
Wed Jun 24 01:00:55 2015 : Error: /root/teste/mods-enabled/files[9]: Invalid configuration for module "files"
......
```

more useful! :+1: 

And I made some others adjustments.

### CODE REVIEW

**Comment by arr2036** [comment]
Can you print out the current effective user and group as well. That's what I started doing for other file opening errors.

Really helps tracking down why the server works when run in debug mode vs daemon mode.

**Comment by arr2036** [comment]
There's functions already in the server that wrap the euid egid functions.

**Comment by jpereira** [comment]
@arr2036  Good idea! I will push another pull printing the user id!

**Comment by arr2036** [comment]
OK

**Comment by jpereira** [comment]
@arr2036 What do you mean? I think that could be better create a function that return the current 'user' and 'group' name that runs the process. And in this case just calling like print_current_owner(). has suggestions?

**Comment by jpereira** [comment]
Or could be better call the "uid_name/gid_name" from the src/main/mainconfig.c

**Comment by jpereira** [comment]
@arr2036 

I guess that we can have something like:

```
/*
 * return the name (or #number) of the user/group to run radiusd as
 */
const char *fr_get_owner() {
	static char buf[64];
	const char *user;
	const char *group;
	CONF_SECTION *sec;

	sec = cf_section_find("security");
	if (!sec) return NULL;

	user = cf_section_value_find(sec, "user");
	group = cf_section_value_find(sec, "group");

	if (!user || !group) return NULL;

	snprintf(buf, "%s:%s", user, group);

	return &buf;
}
```

And just calling where we need to show. suggestions?

**Comment by arr2036** [comment]
No. That's not helpful. The reason why I said get the euid/egid is because you want the *effective* uid/gid at the time the system call was made. It's not necessarily going to be the ones configured in radiusd.conf.  radiusd usually starts off as root, and may suid up/down.

Running in debug mode means it never suids to the configured uid/gid, so your code would show the wrong output there too.

Use ``rad_prints_uid`` and ``rad_prints_gid`` with ``geteuid`` and ``getegid``. Those functions take all the pain out of getting the usernames/groupnames.

**Comment by arr2036** [comment]
I can't find where I did the other errors though *sigh*. Maybe someone removed them.

**Comment by jpereira** [comment]
@arr2036 exactly! I didn't find. but the idea is a function like as i said? but using the rad_prints_uid! ?

**Comment by arr2036** [comment]
yes, with geteuid and getegid

**Comment by jpereira** [comment]
@arr2036 exactly! I didn't find. but the idea is a function like as i said?

**Comment by jpereira** [comment]
I will put the new function "const char *fr_get_owner()" in the util.c, like it?

**Comment by arr2036** [comment]
It's only four lines of code to get the euid/egid, i'm not sure it's worth writing a function.

**Comment by jpereira** [comment]
@arr2036 I think that could be better put separated, because we have another contexts that can be useful to print the process owner.

**Comment by jpereira** [comment]
@arr2036 I made in another branch, ref #1071

**Pull request merged**
