### PR TITLE
radeapclient - rate limit option

### PR DESCRIPTION
**Pull request by nchaigne**
This is the first of a new set of commits to radeapclient.
If you're still ok with this, we can proceed the same way as for last
pull request:
I'll post small commits so you can see what's being changed; and at some
point we'll agree on a merge.

This commit adds option "-n" which allows to control the rate of
requests sent per second.

### CODE REVIEW

**Comment by ruyrybeyro** [comment]
apt-get install sysstat

On 1 April 2015 at 18:04, Nicolas C <notifications@github.com> wrote:

> This is the first of a new set of commits to radeapclient.
> If you're still ok with this, we can proceed the same way as for last
> pull request:
> I'll post small commits so you can see what's being changed; and at some
> point we'll agree on a merge.
>
> This commit adds option "-n" which allows to control the rate of
> requests sent per second.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/FreeRADIUS/freeradius-server/pull/948
> Commit Summary
>
>    - radeapclient - rate limit option
>
> File Changes
>
>    - *M* src/modules/rlm_eap/radeapclient.c
>    <https://github.com/FreeRADIUS/freeradius-server/pull/948/files#diff-0>
>    (79)
>
> Patch Links:
>
>    - https://github.com/FreeRADIUS/freeradius-server/pull/948.patch
>    - https://github.com/FreeRADIUS/freeradius-server/pull/948.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRADIUS/freeradius-server/pull/948>.
>



-- 
Regards,

--
Rui Ribeiro
Senior Sysadm
ISCTE-IUL
https://www.linkedin.com/pub/rui-ribeiro/16/ab8/434

**Comment by ruyrybeyro** [comment]
Good evening, I am sorry, wrong thread, was sending this message to someone
else. Have a nice easter you all.

On 2 April 2015 at 04:25, Rui Ribeiro <ruyrybeyro@gmail.com> wrote:

> apt-get install sysstat
>
> On 1 April 2015 at 18:04, Nicolas C <notifications@github.com> wrote:
>
>> This is the first of a new set of commits to radeapclient.
>> If you're still ok with this, we can proceed the same way as for last
>> pull request:
>> I'll post small commits so you can see what's being changed; and at some
>> point we'll agree on a merge.
>>
>> This commit adds option "-n" which allows to control the rate of
>> requests sent per second.
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/FreeRADIUS/freeradius-server/pull/948
>> Commit Summary
>>
>>    - radeapclient - rate limit option
>>
>> File Changes
>>
>>    - *M* src/modules/rlm_eap/radeapclient.c
>>    <https://github.com/FreeRADIUS/freeradius-server/pull/948/files#diff-0>
>>    (79)
>>
>> Patch Links:
>>
>>    - https://github.com/FreeRADIUS/freeradius-server/pull/948.patch
>>    - https://github.com/FreeRADIUS/freeradius-server/pull/948.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FreeRADIUS/freeradius-server/pull/948>.
>>
>
>
>
> --
> Regards,
>
> --
> Rui Ribeiro
> Senior Sysadm
> ISCTE-IUL
> https://www.linkedin.com/pub/rui-ribeiro/16/ab8/434
>



-- 
Regards,

--
Rui Ribeiro
Senior Sysadm
ISCTE-IUL
https://www.linkedin.com/pub/rui-ribeiro/16/ab8/434

**Comment by nchaigne** [comment]
I think this is in a good state for a merge.
Can you review the commits and tell me what you think ?
Thanks!

**Comment by arr2036** [comment]
- As announced on the list v3.0.x is now mostly in feature freeze. The other changes were allowed before in v3.0.x because they contained legitimate bug fixes, these commits only add additional features, and so should but submitted against v3.1.x.
- You're continuing to develop radeapclient, duplicating some features that have already been implemented in radclient, instead of working on merging radclient and radeapclient. I know it's easier to do, but it makes life harder for pretty much everyone except you. Expect hostility and slow merges if you continue to do this.

**Pull request closed without merging**
