### PR TITLE
Adding new Nomadix VSA’s and use official names

### PR DESCRIPTION
**Pull request by cnelissen**
Just adding some new VSA's and renaming one based on official documentation: http://business.nomadix.com/aghelp/common/ag_userguide/QuickReference/Nomadix_Vendor-Specific_RADIUS_Attributes.htm

### CODE REVIEW

**Comment by cnelissen** [comment]
I see that you are requiring commits to be signed. I added a GPG key after I created this PR, but I think I probably need to re-do the request for the commit to be signed... Unless you can do something from your end.

**Comment by arr2036** [comment]
Force push into your PR branch

**Comment by alandekok** [comment]
The existing names shouldn’t be deleted. That would break people’s configurations, which is bad. 

  Just add the new name, and leave the old names there.

**Comment by cnelissen** [comment]
@alandekok So you are saying to leave duplicate attributes for the same index? I.e.

```
ATTRIBUTE	Nomadix-EndofSession			        9	integer
ATTRIBUTE	Nomadix-Session-Terminate-End-Of-Day		9	integer
```

**Comment by alandekok** [comment]
Yes.  It's OK to have duplicate attributes like that.

**Comment by arr2036** [comment]
You still need to sign your original commit.  If you ``git rebase -i HEAD~2`` and squash your second commit, then ``git push --force`` to this branch, it should fix things.

**Comment by cnelissen** [comment]
@arr2036 Thank you sir. Done and done.

**Pull request merged**
