### PR TITLE
Add dictionary for Arista

### PR DESCRIPTION
**Pull request by hzhongmj**
I'd like to merge the dictionary for Arista Networks.

### CODE REVIEW

**Comment by arr2036** [comment]
Why do you keep closing the pull requests?

**Comment by hzhongmj** [comment]
Sorry Arran. I closed those because I wanted to make sure I was submitting
the request against the right branch first.

Below was an email I sent to the list yesterday:

======
Hey FreeRadius devs,

I'd like to add a dictionary for my employer. I am new to github, so I have
a few questions:

1. Should I create a pull request against 'master' or 'v3.1.x' branch? It
seems the latter is the default branch on github, but your instruction says
this:

git pull --rebase upstream master

2. Either case, would this change automatically merge into all active
branches (assuming no conflicts)?

Thanks for your help.
======

On Wed, Jul 1, 2015 at 6:21 AM, Arran Cudbard-Bell <notifications@github.com

**Comment by arr2036** [comment]
> On Jul 1, 2015, at 12:19 PM, hzhongmj <notifications@github.com> wrote:
> 
> Sorry Arran. I closed those because I wanted to make sure I was submitting
> the request against the right branch first.

No problem. For small changes like that it doesn't really matter, but v3.1.x
is preferred.

> Below was an email I sent to the list yesterday:

It wasn't received. Make sure you have a valid subscription to the developers list.


> ======
> Hey FreeRadius devs,
> 
> I'd like to add a dictionary for my employer. I am new to github, so I have
> a few questions:
> 
> 1. Should I create a pull request against 'master' or 'v3.1.x' branch? It
> seems the latter is the default branch on github, but your instruction says
> this:
> 
> git pull --rebase upstream master
> 

v3.1.x - Where are the instructions, i'll change them?

http://doc.freeradius.org will describe the status of the branches.


> 2. Either case, would this change automatically merge into all active
> branches (assuming no conflicts)?

No, it would be manually merged between v3.0.x and v3.1.x.

-Arran

**Comment by hzhongmj** [comment]
On Wed, Jul 1, 2015 at 9:29 AM, Arran Cudbard-Bell <notifications@github.com
> wrote:

>
> > On Jul 1, 2015, at 12:19 PM, hzhongmj <notifications@github.com> wrote:
> >
> > Sorry Arran. I closed those because I wanted to make sure I was
> submitting
> > the request against the right branch first.
>
> No problem. For small changes like that it doesn't really matter, but
> v3.1.x
> is preferred.
>
> Thanks, pull request coming.


> > Below was an email I sent to the list yesterday:
>
> It wasn't received. Make sure you have a valid subscription to the
> developers list.
>
>
Did not know that I had to subscribe first.


>
> > ======
> > Hey FreeRadius devs,
> >
> > I'd like to add a dictionary for my employer. I am new to github, so I
> have
> > a few questions:
> >
> > 1. Should I create a pull request against 'master' or 'v3.1.x' branch? It
> > seems the latter is the default branch on github, but your instruction
> says
> > this:
> >
> > git pull --rebase upstream master
> >
>
> v3.1.x - Where are the instructions, i'll change them?
>
> http://doc.freeradius.org will describe the status of the branches.
>
>
> I followed the instructions here:

http://wiki.freeradius.org/contributing/GitHub#Commits-and-pushing-changes


> > 2. Either case, would this change automatically merge into all active
> > branches (assuming no conflicts)?
>
> No, it would be manually merged between v3.0.x and v3.1.x.
>

Do I have to send separate pull requests for those or the dev team will do
it?

-Arran

**Pull request closed without merging**
