### PR TITLE
Update rfc3315 dictionary with values for 'Reconf-Msg'

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
As can be seen in https://tools.ietf.org/html/rfc8415#section-21.19

**Comment by arr2036** [comment]
Why should this be marked up as a struct? It's a 1 byte unsigned intenger (so uint8_t) according to the RFC you posted

```
   A server includes a Reconfigure Message option in a Reconfigure
   message to indicate to the client whether the client responds with a
   Renew message, a Rebind message, or an Information-request message.
   The format of the Reconfigure Message option is:

       0                   1                   2                   3
       0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |      OPTION_RECONF_MSG        |         option-len            |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |    msg-type   |
      +-+-+-+-+-+-+-+-+

               Figure 33: Reconfigure Message Option Format

      option-code          OPTION_RECONF_MSG (19).

      option-len           1.

      msg-type             5 for Renew message, 6 for Rebind message,
                           11 for Information-request message.  A
                           1-octet unsigned integer.
```

**Comment by jpereira** [comment]
It was a typo, done.

**Comment by arr2036** [comment]
Apparently a typo in both the commit message and commit content?

**Pull request merged**
