### PR TITLE
HMAC -> OpenSSL against master

### PR DESCRIPTION
**Pull request by cipherboy**
Mirror of #2316 against master branch.

See #2316 for more information.

### CODE REVIEW

**Comment by alandekok** [comment]
It's awkward to have layers of functions, e.g. `fr_hmac_md5_internal`.  It would be simple to just build one function or the other.

e.g.

```
#ifdef HAVE_OPENSSL_EVP_H
fr_hmac_md5(...)
 ... using OpenSSL
#else
fr_hmac_md5(...)
 ... not using OpenSSL
```

**Comment by cipherboy** [comment]
@alandekok Okay, I'll switch to that. Apologies I don't usually CI spam but, `master` doesn't build on Fedora as it lacks `libkqueue`. :/

**Comment by alandekok** [comment]
> @alandekok Okay, I'll switch to that. Apologies I don't usually CI spam but, `master` doesn't build on Fedora as it lacks `libkqueue`. :/

Hmm... we do need libkqueue to work.  Moving to another even library would be enormous amounts of work, unfortunately.  The kqueue API is much simpler (and saner) than most other eventing APIs.

**Comment by cipherboy** [comment]
Regarding `libkqueue`, it looks like there were two main packaging attempts:

https://bugzilla.redhat.com/show_bug.cgi?id=684446
https://bugzilla.redhat.com/show_bug.cgi?id=889505

At this point you're probably too heavily invested in `libkqueue` to switch, but [libverto](https://github.com/latchset/libverto) is what [gssproxy](https://pagure.io/gssproxy/blob/master/f/src/gssproxy.c#_284) and [krb5](https://github.com/cipherboy/krb5/blob/master/src/kdc/main.c#L1050) use, and all of these are packaged in RHEL-like distros.

---

Out of curiosity, what is your time scale looking like for releasing v4.x.x? Just wondering if it is measured in months or over a year. 

--- 

This PR and the other are both updated. They should be good to go, but I'll watch CI and make sure it passes.

**Comment by alandekok** [comment]
libverto seems a little odd.  It's a wrapper around wrapper event libraries?  i.e. it doesn't do anything itself, but it abstracts libev, livevent, etc.  That's not something I'm comfortable with.  The extra layers of abstraction cause layers of bugs, make debugging more difficult, etc.

As for v4, "when it's ready".  We don't have funding to work in it exclusively.  So the work is done whenever we can find time.  We hope to have an alpha release early next year.

**Comment by cipherboy** [comment]
Weird, it looks like you're building against OpenSSL 1.0-series versus 1.1-series on master, but 1.1-series on `v3.0.x`.

Thoughts @alandekok? Should I support both or switch to 1.1.x only?

**Comment by alandekok** [comment]
We should support the commonly used OpenSSL versions.

**Comment by arr2036** [comment]
I'll fix it up locally.  There's an ongoing effort to not use monolithic header files so that this doesn't happen.

**Pull request merged**
