### PR TITLE
Fast crypto binding fix

### PR DESCRIPTION
**Pull request by frenche**
PR is against v3.

### CODE REVIEW

**Comment by alandekok** [comment]
Hmm... there's a lot wrong with the EAP-FAST code.  The simplest thing is that the tlv_type and length should *not* be part of the crypto_binding structure.

I've pushed fixes:

* return `code` from crypto_binding() as per your patch
* checks that the VP containing the crypto_binding is the right size
* since the contents of the VP are just the data, and the crypto_binding check takes just the data...
* pass the `vp->vp_octets` directly to the  crypto_binding()  function

Please test.  I'd like to release 3.0.16 next week.

**Comment by frenche** [comment]
now eapol_test ins't happy with the binding that we send, trying to figure what changed.

EAP-FAST: Received Compound MAC - hexdump(len=20): d8 da fc 86 a4 c2 db 41 52 d2 ae ee 20 78 80 5f d1 8b 16 8e
EAP-FAST: Calculated Compound MAC - hexdump(len=20): f9 d9 a4 1e 56 78 cb d6 ba 34 68 d9 89 4e d6 02 9b 9e ee 87
EAP-FAST: Compound MAC did not match
EAP-FAST: Add Result TLV(status=2)

**Comment by alandekok** [comment]
:( Sorry... I suspected something like that might happen.

**Comment by alandekok** [comment]
Arg... the TLV header *and* length are part of the signature:

`fr_hmac_sha1(binding.compound_mac, (uint8_t *)&binding, ..`

so that part has to be re-done.  I'll take a look.

**Comment by alandekok** [comment]
OK, pushed a fix.  That should help.

**Comment by frenche** [comment]
Works perfect now, thanks!

**Pull request closed without merging**
