### PR TITLE
Update freeradius.spec

### PR DESCRIPTION
**Pull request by spaetow**
For some reason, this SPEC doesn't seem to set the executable bit for configure or install.sh.

### CODE REVIEW

**Comment by alandekok** [comment]
`configure` and `install.sh` are executable in the source tree.  Why aren't they marked executable in the tar file / src RPM?  I'd prefer to fix that issue.

Also, the code to do `chmod a-x *.[ch]` is likely unnecessary.  That issue has been fixed for ages.

**Comment by spaetow** [comment]
@alandekok, quite frankly, I don't know why they're not set. This is what I've found when downloading the ZIP file from Github... :-/

**Comment by alanbuxey** [comment]
ZIP file??  ;-)

**Comment by spaetow** [comment]
Yes Alan. ZIP file. Github does ZIP. Smartypants! :-D

**Comment by alanbuxey** [comment]
well, it shouldn't ;-)

..and if it does, their ZIP tool needs to support file flags and ensure its
zipping things up with them correctly.  if they do,
then its your ZIP client or choice of flags to extract with :)

**Comment by spaetow** [comment]
@alanbuxey, you're welcome to prod Github over their choice of archiving tool... I'm just reporting that this is an issue and fixing it. 

@alandekok, the chmod a-x *.[ch] part I can delete, sure. It's been there since v2.0.x...

**Comment by alandekok** [comment]
I'd prefer to not merge this.  The `tar.gz` format supports the correct permissions.  I'm disinclined to add code to fix problems created by other peoples tools.

**Comment by arr2036** [comment]
http://stackoverflow.com/questions/8377081/github-api-download-zip-or-tarball-link

**Pull request closed without merging**
