### PR TITLE
Changed rlm_python to build against python3(.4).

### PR DESCRIPTION
**Pull request by Deisuan**
There is currently an issue where the module (probably) loses the threadstate
or the heap gets corrupted.
This manifests itself as the python functions reading random/broken data from
parameters -> needs work.

### CODE REVIEW

**Comment by herwinw** [comment]
I've got a branch (https://github.com/herwinw/freeradius-server/tree/rlm_python3) where I pushed a fix to make it compile with Python 3.5 (commit 51a7eb0be4e976f7a714a20c00a6b7c2a51b507e). Feel free to include that

**Comment by arr2036** [comment]
Hm, this would drop 2.7 compatibility, how do people feel about that?

**Comment by Deisuan** [comment]
Alternatively a rlm_python3 module could be introduced, concurrently with the current rlm_python(2.7) module. Python 2.7 will be the last python2 version, and support will run out in 2020, while the first python3 version was released in 2008(!). Perhaps it could even be appropriate to have an rlm_python2 (and thus have rlm_python for python3), since it is basically legacy?

**Comment by arr2036** [comment]
That sounds like a lot of nearly duplicated code to maintain for no real value.  I guess my question is, is there any reason to continue using Python 2.7? Are the syntax changes between 2.7 and 3.0 so great that it's huge amounts of effort to rewrite code? Are the number of eggs for Python 3.0 limited?

I'm not really involved in the Python ecosystem, I just help maintain the rlm_python module out of hatred for Perl.

**Comment by Deisuan** [comment]
Allright, IMHO the porting from python2.7 to python3 is mostly trivial (for syntax alone there are scripts as "2to3" available) - as long as one does not use any libraries that are too exotic (and scaling with the size of the code base obviously). As python3 has been around for eight years, I believe it to be justified to switch exclusively to it. No new project should have a compelling reason use python2, and any older projects should consider porting anyways, if you take the ending support into account.

**Comment by Deisuan** [comment]
Porting to python3 should be done. Can be merged, as far as I can tell. Tested against python3.4.

**Comment by arr2036** [comment]
Well, how about you get the tests passing first ;)

**Comment by Deisuan** [comment]
Yeah, well, did build for me :P I'm on it though.

**Comment by arr2036** [comment]
Oh, it builds on one the compilers at least... It also crashes in the automated tests :P

**Comment by arr2036** [comment]
you can ``make test`` to run them locally.

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by arr2036** [comment]
Is there any will to get this merged? Going to close the PR in two weeks if there's no activity.

**Comment by alandekok** [comment]
python2 will be used until 2020.  After that it's dead.

So we can keep using rlm_python against python3.  But at some point, it should change.

TBH, we should probably do this in the v4 branch.

**Comment by arr2036** [comment]
Yeah, this PR is for V4, and would have been merged, it's just it doesn't pass the tests.

**Comment by spbnick** [comment]
@arr2036, @alandekok, did I read you right here and you're not interested in getting v3.0.x to support Python 3? Asking because RHEL8 is going to only have Python 3.

**Comment by alandekok** [comment]
If everyone is moving to Python 3, then we should support it in FreeRADIUS.

Given that we don't want to remove functionality, I think that adding a new module would be the simplest option.  `rlm_python` is only ~1100 LoC, much of which is boilerplate.  I would be OK with adding an `rlm_python3` module, specifically for Python 3.

I suspect it's too hard to have one module support both Python 2 and Python 3.

**Comment by arr2036** [comment]
It's a lot of extremely complicated and involved boilerplate which doesn't improve with python 3.  It's not actually that hard to have a module that supports both, the API is very similar.

**Comment by arr2036** [comment]
I already did a bunch of the work in the existing module.

**Comment by spbnick** [comment]
I see, thank you for the response and an update, @alandekok, @arr2036. Red Hat obviously needs Python 3 support, and in v3.0.x too. I have little time at the moment to help you with that (and I'm not a Python expert), but I'll either find time myself to help with that, or find someone else to take over. Can I somehow follow your efforts on this, in the meantime?

**Comment by jeffersonchua** [comment]
> I've got a branch (https://github.com/herwinw/freeradius-server/tree/rlm_python3) where I pushed a fix to make it compile with Python 3.5 (commit [51a7eb0](https://github.com/FreeRADIUS/freeradius-server/commit/51a7eb0be4e976f7a714a20c00a6b7c2a51b507e)). Feel free to include that

The branch is gone? Is there a patch somewhere for python3

Thanks,
Jeff

**Pull request closed without merging**
