### PR TITLE
v2.x.x misc fixes

### PR DESCRIPTION
**Pull request by spbnick**
This is a bunch of fixes on top of v2.x.x branch done in preparation for RHEL6 rebase on v2.2.6.
I haven't checked yet if any of them apply on v3.0.x.

Most of them are simple Coverity/compiler warning fixes, but some might have real impact.
It would be nice to have them all in, but of course it is up to you to pick and choose.

Thank you.

### CODE REVIEW

**Comment by alandekok** [comment]
I'll take a look.  Most minor fixes can be added.  I'm *very* wary of behavior changes.

Coverity warnings go in.  Compiler warnings are a lower priority.

The v3.0.x branch builds with no compiler warnings, no "clang scan" warnings, and nearly no coverity warnings, or cppcheck.  That was a lot of work, which I'm not going to do for 2.x.

But patches are always welcome.

**Comment by alandekok** [comment]
Most of these look pretty good.  I'll see if I can pull them in by Monday,

**Comment by spbnick** [comment]
Thanks a lot, Alan! I'm glad you took the warnings under control in v3.0.x :) I hope my patches will help towards doing the same in v2.x.x, no matter how old it is.

Regarding start_threads/max_threads, this is how it is done in v3.0.x by Arran (in f12f98d98), but it's up to you, of course.

**Comment by arr2036** [comment]
You can't start more threads than max threads, that's a pretty basic validation check.

**Comment by spbnick** [comment]
@arr2036 Sure. I'm fine with either approaches, but I think an error would be more useful for noticing typos and forgetting to raise max_servers, for example.

**Comment by arr2036** [comment]
With the current code the server will fail to start, but with a more obscure error "Thread spawn failed.  Maximum number of threads (%d) already running.". See ``thread_pool_init`` and ``spawn_thread``.

**Comment by arr2036** [comment]
Just saying it's not really a behaviour change, just changes the log message to something more useufl.

**Comment by spbnick** [comment]
Thanks, Alan!

**Pull request merged**
