### PR TITLE
rlm_ldap: cleanup memory after ldap version query

### PR DESCRIPTION
**Pull request by gureedo**
rlm_ldap: cleanup memory after ldap version query

Signed-off-by: Aleksey Katargin gureedo@intersvyaz.net

### CODE REVIEW

**Comment by arr2036** [comment]
Why the zero length string for inst->server?

**Comment by alandekok** [comment]
`inst->server` should be allocated, so that `talloc_asprintf_append()` works.

It probably should be

    if (!inst->server) inst->server = talloc_strdup(inst, "");

**Comment by gureedo** [comment]
Amended commit with `if (!inst->server) inst->server = talloc_strdup(inst, "");`

**Comment by gureedo** [comment]
So, would you merge this PR?

**Pull request merged**
