### PR TITLE
adding docker scripts for building

### PR DESCRIPTION
**Pull request by mattrose**
as requested.  These docker scripts set up docker containers able to build freeradius easily

### CODE REVIEW

**Comment by alandekok** [comment]
The repository shouldn't have binary RPMs in it.  Is there any way to load these packages from elsewhere, or build them from source.. e.g. like we do already with eapol_test.

**Comment by alanbuxey** [comment]
Was going to say the same thing. RPMs = no. Just pull them directly from
required repo using standard docker/yum scripts. In that way they also stay
up to date and you're not using stale code.

alan

**Comment by mattrose** [comment]
It's not ideal, but these packages I found are definitely not in any standard repository.  I ended up finding the source rpms  on pkgs.org and rebuilding them on a CentOS server to get these binaries.  

The problem with building them on the box is that the freeradius RPMs themselves depend on the RPM packages, not just the libraries, so to build free radius we have to get the source code, then get the RPM manifest from somewhere, and then installing the packages necessary for building RPMs, before we can even get to building the RPMs.

Not impossible, I'll see what I can do.

**Comment by arr2036** [comment]
libkqueue one is already solved.  Shallow clones of git repositories are fine.

**Comment by mattrose** [comment]
retest this please

**Comment by arr2036** [comment]
We needed that? :P

**Comment by arr2036** [comment]
We do actually send systemd hearbeats from the main event loop

**Pull request closed without merging**
