### PR TITLE
Fix build when PSK_MAX_IDENTITY_LEN is not defined

### PR DESCRIPTION
**Pull request by lytboris**

### CODE REVIEW

**Comment by alandekok** [comment]
Commit 696e40de already fixed that.  Why this patch?

**Comment by lytboris** [comment]
Haven't seen your commit. Arran merged only comment to #endif effectively: e6c143af015872f3bd393f108c25cdad227bc4d3

**Comment by alandekok** [comment]
You should have received an email from #1572, which you've commented on. If you look at the commit history for v3.0.x, you'll see Arran merged two commits.

**Comment by lytboris** [comment]
> You should have received an email from #1572
I did receive a message from mcnewton, but not notice about your commit with reference (not even in spam).

Spent a couple of hours tracking this down in vain :(

**Comment by lytboris** [comment]
Why not to merge a9d4798?

**Pull request merged**
