### PR TITLE
Add a Docker parameter to set up the Client and Secret. ref #3203

### PR DESCRIPTION
**Pull request by jpereira**
It will simplify the first user contact with our images.

### CODE REVIEW

**Comment by mcnewton** [comment]
This looks like it will forcibly overwrite any `clients.conf` copied in by the user, no? Which means there's no way to use more than one client (mostly unconfigurable) any more.

TBH I'm not really sure what the point of this is. To make use of the Docker images the user has to supply a working `raddb` config anyway, which may as well contain a `clients.conf` file in it.

**Comment by jpereira** [comment]
Actually, it is a good point @mcnewton . thank you!

**Comment by alandekok** [comment]
You could write the clients to a file `raddb/clients-docker.conf`

and then update the main `clients.conf` file to do:

```
$-INCLUDE clients-docker.conf`
```

**Comment by mcnewton** [comment]
It doesn't really solve much because you still have to create the rest of the config. Unless we added extra options to create users file entries, etc. That could get complicated very quickly.

**Comment by jpereira** [comment]
Maybe use the Docker `VOLUME` parameter to persist externally the config directory. maybe like https://hub.docker.com/_/postgres does.

**Pull request closed without merging**
