### PR TITLE
Remove FR_LOCATE_DIR macro

### PR DESCRIPTION
**Pull request by floppym**
Calling "locate" to find include and library paths makes no sense. The
locate database may contain paths comprised of files meant for entirely
different toolchains.

Fixes: https://github.com/FreeRADIUS/freeradius-server/issues/4317

### CODE REVIEW

**Comment by thesamesam** [comment]
Note that ``locate`` may also find files which do not exist on the system (removed since the last DB update, usually done daily or weekly) or fail to find new files. It's really intended for users to find files rather than within build systems or automated processes which expect to find them in standard-ish locations.

We already have pkg-config which is being used + some additional logic in the build system within FreeRADIUS to go looking for libs and headers, so ``locate`` should not be needed at all.

**Comment by stintel** [comment]
Tested-by: Stijn Tintel <stijn@linux-ipv6.be>

**Comment by floppym** [comment]
@alandekok The code still exists in the master branch. Is there some reason for that?

**Comment by alandekok** [comment]
@floppym We haven't gotten to it yet.

Plus, the "master" branch has not been released as v4, and is not yet supported.

**Comment by floppym** [comment]
Thanks, just wanted to make sure it wasn't missed by mistake.

**Pull request closed without merging**
