### PR TITLE
3.0.x - radeapclient - parallel mode (and more stuff)

### PR DESCRIPTION
**Pull request by nchaigne**
I know, the diff will be useless on so many changes, but it wasn't feasible to do small commits on this one.
Anyhow, it works. Still does all what the old radeapclient was doing before, and much more.
I use it mainly for EAP-SIM, but tested also EAP-MD5 (and non EAP requests).
As always, all comments are welcome :)

- Added a "rce_request_t" structure which allows to store a request
context.
- Load all requests from files (or stdin) in memory in a list of
"rce_request_t".
- Use packet list and socket functions provided by FreeRADIUS library.
- Added support for "parallel" (option -p) and "send rate" (option -n).
- Added a "receive/send" loop, sends requests in parallel mode (similar
to radclient).
- Added statistics (option -s).
- Better handling of output according to debug/quiet (options -x and
-q). No more wilds printf's.
- Bug fix in EAP-SIM client state machine (error case).
- Updated attribute handling as from latest radclient code.

### CODE REVIEW

**Comment by arr2036** [comment]
Hmm this pull request no longer has any commits :( I guess you reused the branch?

**Comment by nchaigne** [comment]
Yes, I was a total newbie with git at the time and didn't know you had to create branchs for pull requests :)
I still have the source if you want it. Though I've realized since then that a lot of things could be done way better...

**Comment by arr2036** [comment]
If you feel like redoing it (and splitting out the commits this time), it would be appreciated. It'd be even better if you merged the functionality with radclient, so we didn't need to maintain two utilities.

**Comment by nchaigne** [comment]
Maybe I can work on it, if you don't mind it being slow (need to find the time to do it). And yes, I'll make small commits... should be easier now that I know where I want to go :)

**Pull request closed without merging**
