### PR TITLE
Fix rlm_python3 dead-lock in GIL. ref #5111

### PR DESCRIPTION
**Pull request by jpereira**
... Limiting to have more than one instance

### CODE REVIEW

**Comment by jpereira** [comment]
Now we could execute more than one script.

e.g: testing using 3 scripts.

```
...
Mon Jul 24 17:05:26 2023 : Debug: (0)   authorize {
Mon Jul 24 17:05:26 2023 : Debug: (0)     modsingle[authorize]: calling python3_script1 (rlm_python3)
Mon Jul 24 17:05:26 2023 : Debug: (0) python3_script1: Initialised new thread state 0x151f22510
Mon Jul 24 17:05:26 2023 : Debug: (0) python3_script1: Using thread state 0x151f22510
*** python3_script1:  authorize ***
Mon Jul 24 17:05:26 2023 : Info: *** radlog call in authorize ***

{'request': (('User-Name', 'bob'), ('User-Password', 'hello')), 'reply': None, 'config': None, 'session-state': None, 'proxy-request': None, 'proxy-reply': None}

{}
Mon Jul 24 17:05:26 2023 : Debug: (0)     modsingle[authorize]: returned from python3_script1 (rlm_python3)
Mon Jul 24 17:05:26 2023 : Debug: (0)     [python3_script1] = ok
Mon Jul 24 17:05:26 2023 : Debug: (0)     modsingle[authorize]: calling python3_script2 (rlm_python3)
Mon Jul 24 17:05:26 2023 : Debug: (0) python3_script2: Initialised new thread state 0x141e08d40
Mon Jul 24 17:05:26 2023 : Debug: (0) python3_script2: Using thread state 0x141e08d40
*** python3_script2: authorize ***
Mon Jul 24 17:05:26 2023 : Info: *** radlog call in authorize ***

{'request': (('User-Name', 'bob'), ('User-Password', 'hello')), 'reply': None, 'config': None, 'session-state': None, 'proxy-request': None, 'proxy-reply': None}

{}
Mon Jul 24 17:05:26 2023 : Debug: (0)     modsingle[authorize]: returned from python3_script2 (rlm_python3)
Mon Jul 24 17:05:26 2023 : Debug: (0)     [python3_script2] = ok
Mon Jul 24 17:05:26 2023 : Debug: (0)     modsingle[authorize]: calling python3_script3 (rlm_python3)
Mon Jul 24 17:05:26 2023 : Debug: (0) python3_script3: Initialised new thread state 0x1529392a0
Mon Jul 24 17:05:26 2023 : Debug: (0) python3_script3: Using thread state 0x1529392a0
*** python3_script3: authorize ***
Mon Jul 24 17:05:26 2023 : Info: *** radlog call in authorize ***

{'request': (('User-Name', 'bob'), ('User-Password', 'hello')), 'reply': None, 'config': None, 'session-state': None, 'proxy-request': None, 'proxy-reply': None}

{}
Mon Jul 24 17:05:26 2023 : Debug: (0)     modsingle[authorize]: returned from python3_script3 (rlm_python3)
Mon Jul 24 17:05:26 2023 : Debug: (0)     [python3_script3] = ok
...
```

**Comment by arr2036** [comment]
But why?.. Do you know _why_ this fixes the problem?

**Comment by jpereira** [comment]
> But why?.. Do you know _why_ this fixes the problem?

We are doing some block operations to initialize the `main_interpreter` mixing unlock (`PyEval_SaveThread()`) of `main_interpreter` with `sub_interpreter` setup causing such _dead-lock_. Therefore, the first call of  `python_interpreter_init()` should release the _global_ GIL instance first.

**Comment by arr2036** [comment]
Still not convinced this is right or sain

**Pull request closed without merging**
