### PR TITLE
radmin fixes

### PR DESCRIPTION
**Pull request by mkhon**
- Fix SIGSEGV during initialization due to uninitialized main_config
- Increase the number of -e commands

### CODE REVIEW

**Comment by mkhon** [comment]
Without the fix radmin fails like this:

```
# radmin
Including files in directory "/etc/raddb/template.d/"
Including files in directory "/etc/raddb/global.d/"
Including files in directory "/etc/raddb/mods-enabled/"
Including files in directory "/etc/raddb/policy.d/"
CAUGHT SIGNAL: Segmentation fault
Backtrace of last 9 frames:
/usr/lib64/freeradius/libfreeradius-util.so(fr_fault+0xe8)[0x7f13dfdc0701]
/lib64/libpthread.so.0(+0xf630)[0x7f13dd41e630]
/usr/lib64/freeradius/libfreeradius-server.so(+0x1f859)[0x7f13df64b859]
/usr/lib64/freeradius/libfreeradius-server.so(+0x20f38)[0x7f13df64cf38]
/usr/lib64/freeradius/libfreeradius-server.so(+0x222ca)[0x7f13df64e2ca]
/usr/lib64/freeradius/libfreeradius-server.so(cf_file_read+0x347)[0x7f13df64e85b]
radmin(main+0x5ac)[0x40424f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f13dce1d555]
radmin[0x402479]
No panic action set
_EXIT(139) CALLED src/lib/util/debug.c[1055]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff738a859 in process_if (stack=0x7fffffffbce0) at src/lib/server/cf_file.c:1470
1470                    if (!main_config->use_new_conditions) {
Missing separate debuginfos, use: debuginfo-install nwkrad-openssl-libs-1.1.1k-1.el7.x86_64
(gdb) print main_config
$1 = (const main_config_t *) 0x0
(gdb) bt
#0  0x00007ffff738a859 in process_if (stack=0x7fffffffbce0) at src/lib/server/cf_file.c:1470
#1  0x00007ffff738bf38 in parse_input (stack=0x7fffffffbce0) at src/lib/server/cf_file.c:1984
#2  0x00007ffff738d2ca in cf_file_include (stack=0x7fffffffbce0) at src/lib/server/cf_file.c:2549
#3  0x00007ffff738d85b in cf_file_read (cs=0x62e4d0, filename=0x608440 <io_buffer> "/etc/raddb/radiusd.conf")
    at src/lib/server/cf_file.c:2657
#4  0x000000000040424f in main (argc=1, argv=0x7fffffffe538) at src/listen/control/radmin.c:995
```

**Comment by mkhon** [comment]
There's one more issue (which is not fixed in this PR):

```
Including files in directory "/etc/raddb/template.d/"
Including files in directory "/etc/raddb/global.d/"
Including files in directory "/etc/raddb/mods-enabled/"
Including files in directory "/etc/raddb/policy.d/"
Including files in directory "/etc/raddb/sites-enabled/"
ASSERT FAILED src/lib/server/cf_file.c[149]: rules->attr.dict_def: No protocol dictionary set
CAUGHT SIGNAL: Aborted
Backtrace of last 7 frames:
/usr/lib64/freeradius/libfreeradius-util.so(fr_fault+0x1ba)[0x7ffff7b28f6a]
/usr/lib64/freeradius/libfreeradius-util.so(_fr_assert_fail+0xf4)[0x7ffff7b29224]
/usr/lib64/freeradius/libfreeradius-server.so(+0x1e7f3)[0x7ffff73d97f3]
/usr/lib64/freeradius/libfreeradius-server.so(cf_file_read+0xa73)[0x7ffff73db0b3]
/usr/sbin/radmin(main+0x36c)[0x4025dc]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ffff4bcd555]
/usr/sbin/radmin[0x403360]
No panic action set

Program received signal SIGABRT, Aborted.
0x00007ffff51ce4fb in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:36
36	  return INLINE_SYSCALL (tgkill, 3, pid, THREAD_GETMEM (THREAD_SELF, tid),
(gdb) bt
#0  0x00007ffff51ce4fb in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:36
#1  0x00007ffff7b28f3b in fr_fault () from /usr/lib64/freeradius/libfreeradius-util.so
#2  0x00007ffff7b29224 in _fr_assert_fail () from /usr/lib64/freeradius/libfreeradius-util.so
#3  0x00007ffff73d97f3 in process_if () from /usr/lib64/freeradius/libfreeradius-server.so
#4  0x00007ffff73db0b3 in cf_file_read () from /usr/lib64/freeradius/libfreeradius-server.so
#5  0x00000000004025dc in main ()
```

The reason is that we have sites-enabled/dhcp (with dhcpv4 dictionary?). This can be workarounded by running radmin with the config dir which does not have sites-enabled/dhcp. However, if there is an easy fix - please suggest.

**Comment by alandekok** [comment]
The migration checks in the `unlang` parser require various migration flags in `main_config_t`.  I'll see if I can push some other fixes which are a bit more generic.

**Comment by mkhon** [comment]
@alandekok any success with this?

**Comment by mkhon** [comment]
@alandekok do you have a fix for "ASSERT FAILED src/lib/server/cf_file.c[149]: rules->attr.dict_def: No protocol dictionary set"?

**Pull request closed without merging**
