### PR TITLE
Backport crossbuild scripts from v4

### PR DESCRIPTION
**Pull request by jpereira**
* It backports the 'crossbuild' scripts from v4 to v3 adding the capability to perform tests against all dockers images available in scripts/docker.
* Add the target 'make crossbuild.IMAGE.test-systemd' that performs tests against the systemd. (the IMAGE directory should have a Dockerfile.systemd)

ps. No impacts on v3 behavior. Only brings the capability to perform the 'crossbuild.IMAGE.up' and of course, perform 'make test' trough the all Dockers images helping to detect cross-platform issues.

### CODE REVIEW

**Comment by arr2036** [comment]
Could you look into why the tests are failing?

**Comment by jpereira** [comment]
No errors, only that one related to Jenkins network issue as can be in https://travis-ci.org/FreeRADIUS/freeradius-server/jobs/590541906 

image

**Comment by alandekok** [comment]
All tests pass now as transient network issues are gone.  I will merge it once 3.0.20 has been released.

**Comment by arr2036** [comment]
Can this be rebased

**Comment by jpereira** [comment]
Rebased and Retested just to double check.

```
[jpereira@sugarloaf freeradius-server-v3.0.x.git]$ make crossbuild.ubuntu18 
START ubuntu18 (fr-crossbuild-ubuntu18)
REFRESH ubuntu18
Already up to date.
Current branch v3/backport-crossbuild is up to date.
TEST ubuntu18 > /Users/jpereira/Devel/FreeRADIUS/freeradius-server-v3.0.x.git/scripts/docker/crossbuild//log.ubuntu18
[jpereira@sugarloaf freeradius-server-v3.0.x.git]$ make crossbuild.ubuntu18.test-systemd
BUILD SYSTEMD ubuntu18 (freeradius-build/ubuntu18.test-systemd) > /Users/jpereira/Devel/FreeRADIUS/freeradius-server-v3.0.x.git/scripts/docker/crossbuild//build.ubuntu18.test-systemd
START ubuntu18 (fr-crossbuild-ubuntu18-test-systemd)
3ed6f7a05ddb8101957862776d4eb2bf2937ccb99a63ec8cbb3976bbb517822c
REFRESHING fr-crossbuild-ubuntu18-test-systemd
Cloning into '/srv/build'...
done.
CALLING TEST SCRIPT: /srv/build/scripts/docker/crossbuild/test-systemd.sh fr-crossbuild-ubuntu18-test-systemd
(##) Changing to /srv/build
(##) Building the packages calling 'make deb' in 3ed6f7a05ddb
(##) Removing any previous installation calling 'dpkg -P freeradius-build-deps'
(##) Installing the packages calling 'dpkg -i ../*.deb' in 3ed6f7a05ddb
(##) Checking if the process freeradius is activated
(##) Stop the service freeradius
(##) Start the service freeradius
(##) Restart the service freeradius
(##) Listing all processes
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        58  0.0  0.0   4628   876 ?        Ss   21:07   0:00 sh -c /srv/build/scripts/docker/cro
root        63  0.0  0.1  18376  3168 ?        S    21:07   0:00  \_ /bin/bash /srv/build/scripts/do
root     39896  0.0  0.1  34400  2900 ?        R    21:11   0:00      \_ ps axuf --cols=100
root         1  0.0  0.3 224420  7772 ?        Ss   21:06   0:00 /lib/systemd/systemd
root        19  0.0  0.2  70136  4224 ?        S<s  21:06   0:00 /lib/systemd/systemd-journald
message+ 39570  0.0  0.2  49924  4116 ?        Ss   21:10   0:00 /usr/bin/dbus-daemon --system --add
freerad  39890  0.0  4.1 251472 84920 ?        Ssl  21:11   0:00 /usr/sbin/freeradius -f
(##) Success with Systemd/freeradius-server.
WIPE fr-crossbuild-ubuntu18-test-systemd
[jpereira@sugarloaf freeradius-server-v3.0.x.git]$
```

**Pull request merged**
