### PR TITLE
Cisco ASA dictionary fixes

### PR DESCRIPTION
**Pull request by mjh75**
I have no idea why the dhcp.c file is being included in this pull request since I only changed dictionary.cisco.asa. Several of the attributes should have been ipaddr instead of string/integer. These changes worked for ASA-Primary-DNS and ASA-Secondary-DNS, I have not tested the rest, but I have the DNS attributes.

### CODE REVIEW

**Comment by arr2036** [comment]
``
git add remote upstream git@github.com:FreeRADIUS/freeradius-server.git
git pull --rebase upstream master
git push --force origin master
``

**Comment by mjh75** [comment]
Redoing

**Comment by alagoutte** [comment]
There is a reason to don't push also on master ?

**Comment by mjh75** [comment]
I cannot seem to get a pull request with just the changes to the 
dictionary file. I ran out of time the other day, but will get back to it.

On 3/10/2015 1:41 PM, Alexis La Goutte wrote:
>
> There is a reason to don't push also on master ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeRADIUS/freeradius-server/pull/921#issuecomment-78106950>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGGSEZqdUGzBhyz9c_-27qIOkhhPJj0Wks5nzyQ7gaJpZM4DrZNR.gif
>

-- 
  
Michael
  
--

Michael J. Hartwick, VE3SLQ
Hartwick Communications Consulting
(519) 396-7719
hartwick@hartwick.com
http://www.hartwick.com

**Pull request closed without merging**
