### PR TITLE
Dictionary Fixups

### PR DESCRIPTION
**Pull request by jsynack**
Some updates for various dictionary files.

Generally:

1. Update URLs to working versions if found to be broken.
2. Update any vendor 'history' - the industry is filled with buyouts / etc.
3. Add any missing VSAs encountered
4. Repair any obvious typos
5. Tag links as 'dead' if they do not work and no replacement URL could be easily found in a couple of minutes of searching. (some were going to domain squatter pages)

There are quite a few more to go - just looking if there is anything else in this area that is desired/not desired.

### CODE REVIEW

**Comment by alandekok** [comment]
What is on line 27 of dictionary.fortinet?  The travis build is failing because the dictionary is wrong.

**Comment by alandekok** [comment]
The dictionary.fortinet has UTF-8 hyphens instead of '-'.  Please push a fix for that.

**Comment by jsynack** [comment]
My bad - probably a copy+paste issue on my part. Will get it fixed up shortly.

**Comment by arr2036** [comment]
Thanks again for these.  Fixing up dictionaries/URLs in documentation really improves the level of polish.

**Pull request merged**
