### PR TITLE
First attempt at a watch file

### PR DESCRIPTION
**Pull request by mans0954**
Provide a debian/watch file and PGP key for identifying new versions and verifying their download.

See https://wiki.debian.org/debian/watch for details.

### CODE REVIEW

**Comment by arr2036** [comment]
Is that Alan's key?

**Comment by arr2036** [comment]
and thanks for helping fix up the Debian packages!

**Comment by mans0954** [comment]
Yes, downloaded from here: http://freeradius.org/pgp/aland@freeradius.org I suggest you check I haven't tampered with it :)

**Comment by arr2036** [comment]
Ah just we created a new non-developer specific signing key.  But I guess the switchover needs coordinating a bit more.

**Comment by arr2036** [comment]
If you felt like working with the Debian guys, we really need a new package maintainer...

**Comment by mans0954** [comment]
A project signing key sounds sensible. Packaging v3 for Debian is being discussed in Debian bug #797181 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797181

**Comment by alandekok** [comment]
Please double-check the v3.0.x branch.  We've pulled over some of your changes from v3.1.x, but not all.

The 3.0.10 release will be taken from the v3.0.x branch, *not* v3.1.x.

**Comment by alanbuxey** [comment]
yes, they need to be aware of the relationship between 3.1.x and 3.0.x - as
Alan says, 3.0.10 is from 3.0.x HEAD with bug fixes, security updates etc
3.1.x HEAD is the development bridgehead with new features, breaking of
older configs etc etc... (there be dragons here! etc etc) :-)

**Pull request merged**
