### PR TITLE
Turnoff -Wdocumentation for json-c

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
```
In file included from src/modules/rlm_rest/rlm_rest.c:34:
src/modules/rlm_rest/rest.h:46:10: fatal error: 'freeradius-devel/json/base.h' file not found
#include <freeradius-devel/json/base.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
CC src/modules/rlm_rest/io.c
make: *** [build/objs/src/modules/rlm_rest/rlm_rest.lo] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/modules/rlm_rest/rest.c:40:
src/modules/rlm_rest/rest.h:46:10: fatal error: 'freeradius-devel/json/base.h' file not found
#include <freeradius-devel/json/base.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/objs/src/modules/rlm_rest/rest.lo] Error 1
In file included from src/modules/rlm_rest/io.c:24:
src/modules/rlm_rest/rest.h:46:10: fatal error: 'freeradius-devel/json/base.h' file not found
#include <freeradius-devel/json/base.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.```

**Comment by jpereira** [comment]
```
In file included from src/lib/json/jpath.c:29:
In file included from src/lib/json/base.h:35:
In file included from /usr/local/include/json-c/json.h:30:
/usr/local/include/json-c/json_tokener.h:94:5: error: declaration is marked with '\deprecated' command but does not
      have a deprecation attribute [-Werror,-Wdocumentation-deprecated-sync]
 * @deprecated Unused in json-c code
   ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/lib/json/json.c:29:
In file included from src/lib/json/base.h:35:
In file included from /usr/local/include/json-c/json.h:30:
/usr/local/include/json-c/json_tokener.h:94:5: error: declaration is marked with '\deprecated' command but does not
      have a deprecation attribute [-Werror,-Wdocumentation-deprecated-sync]
 * @deprecated Unused in json-c code
   ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LINK build/bin/radict```

**Comment by arr2036** [comment]
So i'm confused as to why you're getting these warnings, which are usually suppressed by compiler arguments and would like to replicate them on my local system before merging any more of these PRs.  How can I do that?

**Comment by jpereira** [comment]
I am using the:

```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by arr2036** [comment]
Which is only available when you're subscribed to the Beta program?

**Comment by arr2036** [comment]
Use the official version of clang from homebrew, not Apple's butchered version, do you still get the warnings?

**Comment by jpereira** [comment]
Not sure, I am just using the latest Xcode.

```
[jpereira@Jorges-MBP freeradius-server.git]$ xcodebuild -version
Xcode 10.2.1
Build version 10E1001
[jpereira@Jorges-MBP freeradius-server.git]$```

**Comment by arr2036** [comment]
Was that a no? You don't get the warnings?

**Comment by jpereira** [comment]
Now is fine using the official version clang-8 from Brew. the Apple version is so terrible.

**Pull request closed without merging**
