### PR TITLE
Add fr_box_tainted()/fr_box_tainted_len() to respect taint values

### PR DESCRIPTION
**Pull request by jpereira**
The new both macros have an extra field to set the "taint" state.

### CODE REVIEW

**Comment by jpereira** [comment]
It's necessary to complete the commit 012865619f8001b0903fa129ac44cff22e91fadd and fix the xlat tests. (even the tests still failing, but related to rlm_csv)

fyi @arr2036

**Comment by alandekok** [comment]
My $0.02 is that I'd rather call it `fr_box_tainted()`.  That would be clearer than using '`strvalue2`.

**Comment by jpereira** [comment]
@alandekok done. actually, sounds better.

**Comment by alandekok** [comment]
I think the commits are now missing the actual `fr_box_tainted_with_len()` functions?

**Comment by jpereira** [comment]
It's appearing for me.

image

even I rebased just to keep above of your last commit in rlm_csv

**Comment by jpereira** [comment]
@alandekok As we have `fr_box_strvalue() / fr_box_strvalue_len()`. then, I just created `fr_box_tainted()` and `fr_box_tainted_len()`.

i.e: the `fr_box_tainted_with_len()` is there as `_fr_box_tainted_with_len()`

**Pull request merged**
