### PR TITLE
dhcpclient - xlat is not supported

### PR DESCRIPTION
**Pull request by nchaigne**
Apply the same processing as performed in radclient to  input value pairs.

### CODE REVIEW

**Comment by arr2036** [comment]
Sign commits plz

**Comment by arr2036** [comment]
you need to rebase your branch from master

**Comment by nchaigne** [comment]
Don't merge this yet, I screwed up the rebase. It doesn't show the useful changes. :/

**Comment by nchaigne** [comment]
OK this seems alright now. :)

**Comment by arr2036** [comment]
yay

**Pull request merged**
