### PR TITLE
debian: Fixing logrotate script

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by alandekok** [comment]
Please check this in 3.0.10.  I've put patches in which mean you can HUP the server instead of doing a "copytruncate" on the logs.  That would be more efficient.

**Comment by jpereira** [comment]
ah! ok, i will update!

**Comment by jpereira** [comment]
done

**Comment by jpereira** [comment]
done

**Comment by jpereira** [comment]
@alandekok  got it!

**Comment by jpereira** [comment]
@alandekok got it! updated

**Comment by arr2036** [comment]
Copytruncate is the better command to use.  There's no reason to change the logrotation scripts.

**Comment by arr2036** [comment]
killall isn't present in all systems, hup has the side effect of loading config changes.  If you want to make this work reliably, the command socket command is the thing to use, but as not everyone has that enabled, copyrotate is the best way of rotating lots.

**Comment by alandekok** [comment]
Pretty much every other daemon on the planet uses HUP to rotate the logs, and to re-read the configuration.

I don't have a lot of sympathy for people who make random changes to the server and leave them in the raddb directory without (a) testing them, or (b) making them live.

The HUP in 3.0.10 will re-load ONLY those modules which have changed configurations.  Any module or config file which has an error will be ignored, and the old configuration will be remain in use.

**Comment by jpereira** [comment]
I agree with @alandekok

**Comment by arr2036** [comment]
But when you have an alternative which does not have side effects, it's better to use that, surely?

**Comment by arr2036** [comment]
and, yes, all those other daemons were shit and did it wrong too.

**Pull request merged**
