### PR TITLE
Small docs change "blacklist" -> "blocklist"

### PR DESCRIPTION
**Pull request by tashian**
Per best current practice in https://tools.ietf.org/id/draft-knodel-terminology-01.html

### CODE REVIEW

**Comment by tashian** [comment]
There is also many `master`/`slave` references in the FreeRADIUS codebase that could be clarified as `leader` / `follower`, but I did not make those changes as they are more delicate.

**Comment by alandekok** [comment]
The document you reference is simply an opinion piece by a random person.  It is not an IETF "best current practices" standard, and you should not misrepresent the situation by claiming it is one.

**Comment by tashian** [comment]
You're right, it's a proposed BCP. Thanks @alandekok

**Comment by arr2036** [comment]
My primary concern is understandability and consistency of the documentation.  If a datastore the documentation refers to uses the terms `primary`/`replica` we'll use those terms in out documentation.

If a protocol describes a key from which other keys are derived as a `master key` then we're going to use that term in the configuration items and documentation for a module implementing that protocol, we're NOT going to refer to it as a `leader key` or `primary key`.

FWIW - If you're aiming to be non-offensive I would also suggest you not promote terms like `leader` and `follower`, cult survivors and those who have escaped oppressive regimes will thank you.

**Pull request merged**
