### PR TITLE
Fix the 'python_path' (rlm_python/Python2)

### PR DESCRIPTION
**Pull request by jpereira**
The PySys_SetPath() reset the entire python path causing problems to use the existing libraries.

Therefore, we should split the 'python_path' paths and append into 'sys.path'. It is the correct way to keep the default paths allowing to use existing libraries

### CODE REVIEW

**Comment by jpereira** [comment]
so, as confirmed in #3180. now, we are appending the content of `python_path` into the default Python path.

e.g:

1. The default `python_path` set.

```
$ grep python_path $raddb/mods-available/python
    python_path="${modconfdir}/${.:name}:/path/to/python/files:/another_path/to/python_files/"
$
```

2. We have the `authorize` method configured in `$raddb/mods-config/python/example.py` to print out the content of `sys.path`

```
def authorize(p):
  try:
    import sys
    import pprint

    print("Output of sys.path: ")
    pprint.pprint(sys.path)

    return radiusd.RLM_MODULE_OK
  except Exception, err:
    print(Exception, err)
``` 

3. The output is:

```
...
Thu Dec  5 15:21:27 2019 : Debug: (0) # Executing section authorize from file raddb//sites-enabled/default
Thu Dec  5 15:21:27 2019 : Debug: (0)   authorize {
Thu Dec  5 15:21:27 2019 : Debug: (0)     modsingle[authorize]: calling python (rlm_python)
Thu Dec  5 15:21:27 2019 : Debug: (0) python: Initialised new thread state 0x7f950c4a7310
Thu Dec  5 15:21:27 2019 : Debug: (0) python: Using thread state 0x7f950c4a7310
Output of sys.path:
['/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coccigrep-1.17-py2.7.egg',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pygments-2.4.2-py2.7.egg',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/configparser-4.0.2-py2.7.egg',
 '/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/argparse-1.4.0-py2.7.egg',
 'raddb//mods-config/python',
 '/path/to/python/files',
 '/another_path/to/python_files/']
Thu Dec  5 15:21:27 2019 : Debug: (0)     modsingle[authorize]: returned from python (rlm_python)
Thu Dec  5 15:21:27 2019 : Debug: (0)     [python] = ok
...
```

so, now we are able to use existing modules provided by the Python runtime.

**Comment by geaaru** [comment]
Hi, I applied your patches to Gentoo 3.0.20 staging ebuild (in my overlay):
https://github.com/geaaru/geaaru_overlay/commit/d8835f1a7d43378560ff0819bbb9d0f06d2c1acc
I will report back soon feedback.
Gentoo/Sabayon will drop python 2.7 from FreeRadius with version 3.0.20, so it's important from our side to stabilize py3 support.

**Comment by geaaru** [comment]
Hi Jorge,
probably I wrote in the wrong PR but at least rlm_python3 is referenced in this pr.

I tested rlm_python3 but doesn't work. This is the error when I try to load the radiusd_test.py example (with print command correction: print "xxx" => print("xxx"))
```
Mon Dec  9 18:18:51 2019 : Error: do_python_single:568, detach - pRet is NULL
Mon Dec  9 18:18:51 2019 : Error: python_error_log:200, Exception type: <class 'SystemError'>, Exception value: null argument to internal routine
Mon Dec  9 18:18:51 2019 : Error: do_python_single:676, detach - RLM_MODULE_FAIL
```
It seems that `PyObject_CallFunctionObjArgs` return a NULL.

**Comment by jpereira** [comment]
@geaaru can you share the content of `radiusd_test.py` and also the `raddb/mods-enabled/python3`?

**Comment by geaaru** [comment]
It's the online [example](https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/modules/rlm_python3/radiusd_test.py) with only the change that I wrote:

print "xxx"

print("xxx")

FWIK print syntax without bracket is not admitted in py3.

Same for mods-available config. I added also /usr/lib64/python3.6 in python_path but probably is not needed:

```
python_path = ${modconfdir}/${.:name}:/usr/lib64/python3.6
```

**Comment by jpereira** [comment]
@geaaru please, perform the tests using `example.py` and your `raddb/mods-enabled/python3` should be something like:

```
python3 {
	python_path = "${modconfdir}/${.:name}:/path/to/python/files:/another_path/to/python_files/"

	module = example

	# Pass all VPS lists as a 6-tuple to the callbacks
	# (request, reply, config, state, proxy_req, proxy_reply)
	# pass_all_vps = no

	# Pass all VPS lists as a dictionary to the callbacks
	# Keys: "request", "reply", "config", "session-state", "proxy-request",
	#       "proxy-reply"
	# This option prevales over "pass_all_vps"
	# pass_all_vps_dict = no

	mod_instantiate = ${.module}
	func_instantiate = instantiate
```

It's expected to the `example.py` has the configured `instantiate` function like.

e.g:

``` 
def instantiate(p):
  import sys
  import tempfile
  print("*** instantiate test ***")
  print(p)
  print("PYTHONPATH: {}".format(sys.path))
  print("Tempdir {}".format(tempfile.gettempdir()))
```

**Comment by geaaru** [comment]
Hi Jorge, maybe it's something related to Gentoo Python libraries because also in the branch `v3.0.x` I have the same errors:

```
Tue Dec 10 14:23:43 2019 : Info: Python version: 3.6.9 (default, Oct 29 2019, 20:41:01)  [GCC 8.2.0]
Tue Dec 10 14:23:44 2019 : Error: do_python_single:568, instantiate - pRet is NULL
Tue Dec 10 14:23:44 2019 : Error: python_error_log:200, Exception type: <class 'SystemError'>, Exception value: null argument to internal routine
Tue Dec 10 14:23:44 2019 : Error: do_python_single:676, instantiate - RLM_MODULE_FAIL

```

```python
import radiusd

def instantiate(p):
  print("*** instantiate ***")
  print(p)
```
The problem is on initialize functions pointer to Python code.

So, it isn't related to your patches. Let me know if you want to continue this discussion here or in ML.

The problem I think that `pFunc`  is null:

```
Breakpoint 1, do_python_single (request=request@entry=0x0, pFunc=0x0, funcname=funcname@entry=0x7ffff7bc7c7e "instantiate", pass_all_vps=true, pass_all_vps_dict=false)
    at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:495
495		if ((pArgs = PyTuple_New(6)) == NULL) {
(gdb) n
502		if (request != NULL) {
(gdb) p *request
Cannot access memory at address 0x0
(gdb) bt
#0  do_python_single (request=request@entry=0x0, pFunc=0x0, funcname=funcname@entry=0x7ffff7bc7c7e "instantiate", pass_all_vps=<optimized out>, pass_all_vps_dict=<optimized out>)
    at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:562
#1  0x00007ffff7bc63c2 in mod_instantiate (conf=<optimized out>, instance=0x555555875400) at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:1260
#2  0x00005555555822d3 in module_instantiate (modules=0x5555557d3460, askedname=0x5555557dc900 "python3") at /home/geaaru/Projects/freeradius-server/src/main/modules.c:761
#3  0x0000555555584ec6 in modules_init (config=0x5555555eb690) at /home/geaaru/Projects/freeradius-server/src/main/modules.c:2146
#4  0x000055555558dff0 in main (argc=8, argv=0x7fffffffd258) at /home/geaaru/Projects/freeradius-server/src/main/radiusd.c:520
1260		code = do_python_single(NULL, inst->instantiate.function, "instantiate", inst->pass_all_vps, inst->pass_all_vps_dict);
(gdb) p *inst
$1 = {
  name = 0x5555557dc900 "python3", 
  sub_interpreter = 0x55555589c420, 
  python_path = 0x0, 
  module = 0x0, 
  cext_compat = true, 
  instantiate = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875620 "example", 
    function_name = 0x0
  }, 
  authorize = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875690 "example", 
    function_name = 0x0
  }, 
  authenticate = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875700 "example", 
    function_name = 0x0
  }, 
  preacct = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875770 "example", 
    function_name = 0x0
  }, 
  accounting = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x5555558757e0 "example", 
    function_name = 0x0
  }, 
  checksimul = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875850 "example", 
    function_name = 0x0
  }, 
  pre_proxy = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x5555558758c0 "example", 
    function_name = 0x0
  }, 
  post_proxy = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875930 "example", 
    function_name = 0x0
  }, 
  post_auth = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x5555558759a0 "example", 
    function_name = 0x0
  }, 
  recv_coa = {
    module = 0x0, 
--Type <RET> for more, q to quit, c to continue without paging--
    function = 0x0, 
    module_name = 0x555555875a10 "example", 
    function_name = 0x0
  }, 
  send_coa = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875a80 "example", 
    function_name = 0x0
  }, 
  detach = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875af0 "example", 
    function_name = 0x0
  }, 
  pythonconf_dict = 0x0, 
  pass_all_vps = true, 
  pass_all_vps_dict = false
}

```

The weird thing is that python is NULL when on mod config I have this:

```
python3 {
	#  Path to the python modules
	#
	#  Note that due to limitations on Python, this configuration
	#  item is GLOBAL TO THE SERVER.  That is, you cannot have two
	#  instances of the python module, each with a different path.
	#
#        python_path="/path/to/python/files:/another_path/to/python_files/"
        python_path="${modconfdir}/${.:name}:/usr/lib64/python3.6"

	module = example

	# Pass all VPS lists as a 6-tuple to the callbacks
	# (request, reply, config, state, proxy_req, proxy_reply)
#  pass_all_vps = yes

	# Pass all VPS lists as a dictionary to the callbacks
	# Keys: "request", "reply", "config", "session-state", "proxy-request",
	#       "proxy-reply"
	# This option prevales over "pass_all_vps"
pass_all_vps_dict = yes

	mod_instantiate = ${.module}
...
```

**Comment by jpereira** [comment]
Ah! @geaaru sorry, I informed the wrong PR. This one here is about the rlm_python (Python2). you should use the branch from https://github.com/FreeRADIUS/freeradius-server/pull/3185

**Comment by geaaru** [comment]
Ok, n/p. But my issues are with the right branch:
```
On branch v3/python3-3180
Your branch is up to date with 'jpereira/v3/python3-3180'.
```
So, this means that rlm_python3 has the same issue about `python_path` of the rlm_python2?

Too many PR :D

**Comment by jpereira** [comment]
@geaaru yes, It was fixed in both modules. so, I think that you've something wrong with your setup. because, If you go to https://github.com/FreeRADIUS/freeradius-server/pull/3184 you will see the build/tests/evidence with several Python3.X versions.

e.g:

* Build
```
$ python3 --version
Python 3.7.5
$ git checkout v3/python3-3180
$ ./configure ... \
          --with-rlm-python3-config-bin=python3-config
$ make
```

* Config

```
$ cat raddb/mods-config/python3/example.py
#! /usr/bin/env python3
import radiusd

def instantiate(p):
  import sys
  import tempfile
  print("teste: *** instantiate test ***")
  print("teste: {}".format(p))
  print("teste: Python3 Version: {}".format(sys.version.replace("\n","")))
  print("teste: PYTHONPATH: {}".format(sys.path))
  print("teste: Tempdir {}".format(tempfile.gettempdir()))
$
$ cat raddb/mods-enabled/python3
 python3 {
 	python_path="${modconfdir}/${.:name}:/another_path/to/python_files"
	module = example
	mod_instantiate = ${.module}
	func_instantiate = instantiate
}
$
```

* Test

```
...
Tue Dec 10 12:40:27 2019 : Debug:   # Instantiating module "python3" from file raddb//mods-enabled/python3
Tue Dec 10 12:40:27 2019 : Info: Python version: 3.7.5 (default, Nov  1 2019, 02:16:32)  [Clang 11.0.0 (clang-1100.0.33.8)]
teste: *** instantiate test ***
teste: None
teste: Python3 Version: 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
teste: PYTHONPATH: ['/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '/usr/local/Cellar/protobuf/3.11.1/libexec/lib/python3.7/site-packages', 'raddb//mods-config/python3', '/another_path/to/python_files']
teste: Tempdir /var/folders/ld/6tg9c6qj4fx4c85q26mcqrsh0000gn/T
...
```

**Comment by jpereira** [comment]
@geaaru yes, It was fixed in both modules. so, I think that you've something wrong with your setup. because, If you go to https://github.com/FreeRADIUS/freeradius-server/pull/3185 you will see the build/tests/evidence with several Python3.X versions.

e.g:

* Build
```
$ python3 --version
Python 3.7.5
$ git checkout v3/python3-3180
$ ./configure ... \
          --with-rlm-python3-config-bin=python3-config
$ make
```

* Config

```
$ cat raddb/mods-config/python3/example.py
#! /usr/bin/env python3
import radiusd

def instantiate(p):
  import sys
  import tempfile
  print("teste: *** instantiate test ***")
  print("teste: {}".format(p))
  print("teste: Python3 Version: {}".format(sys.version.replace("\n","")))
  print("teste: PYTHONPATH: {}".format(sys.path))
  print("teste: Tempdir {}".format(tempfile.gettempdir()))
$
$ cat raddb/mods-enabled/python3
 python3 {
 	python_path="${modconfdir}/${.:name}:/another_path/to/python_files"
	module = example
	mod_instantiate = ${.module}
	func_instantiate = instantiate
}
$
```

* Test

```
...
Tue Dec 10 12:40:27 2019 : Debug:   # Instantiating module "python3" from file raddb//mods-enabled/python3
Tue Dec 10 12:40:27 2019 : Info: Python version: 3.7.5 (default, Nov  1 2019, 02:16:32)  [Clang 11.0.0 (clang-1100.0.33.8)]
teste: *** instantiate test ***
teste: None
teste: Python3 Version: 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
teste: PYTHONPATH: ['/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '/usr/local/Cellar/protobuf/3.11.1/libexec/lib/python3.7/site-packages', 'raddb//mods-config/python3', '/another_path/to/python_files']
teste: Tempdir /var/folders/ld/6tg9c6qj4fx4c85q26mcqrsh0000gn/T
...
```

**Pull request merged**
