### PR TITLE
Fix checking dladdr() #1113

### PR DESCRIPTION
**Pull request by jpereira**
hi @alandekok ,

Now the dladdr() will be reached. refs to #1113

### CODE REVIEW

**Comment by alandekok** [comment]
Not necessary.  The solution is to update autoconf.h.in, which I just did.

**Comment by jpereira** [comment]
@alandekok have you checked? without this doesn't works.

**Comment by jpereira** [comment]
have you checked? without the patch 529bcc5,  this doesn't works.

**Comment by jpereira** [comment]
ah! ok

**Pull request closed without merging**
