### PR TITLE
Use radiusd constants and comment rlm_python tests

### PR DESCRIPTION
**Pull request by gyx1000**

### CODE REVIEW

**Comment by gyx1000** [comment]
I think that my test "auth_with_tls" is not really sure because the fact that `pmod1` and `pmod3_withmod1` have their own interpreters, any attributes are already independents.

Do you think that enable cext_compat on this two modules will "emulate" better a multi-thread context for unittest ?

**Comment by arr2036** [comment]
Yes, it'll be distinct.  Even if the same interpreter is used, rlm_python will create a thread state per thread per module instance.  It's useful to have the tests just to make sure nothing crashes :)

**Comment by arr2036** [comment]
Could you make a similar pull request for v3.0.x.  The patches fail to pull across cleanly, and I don't have any time to investigate why today.  Thanks!

**Comment by gyx1000** [comment]
Sure, I will do. I see that when you backport #1589 you don't backport python test folder entirely (Only *pyc". I will make a PR for the full folder content.

**Comment by arr2036** [comment]
ah, ok, that's what it was. Thanks.

**Pull request merged**
