### PR TITLE
fixed typos and some grammar issues

### PR DESCRIPTION
**Pull request by alanbuxey**
fixed typos and some grammar issues

### CODE REVIEW

**Comment by arr2036** [comment]
Why on the v3.1.x branch?

**Comment by alanbuxey** [comment]
backport - 4.0.x has been fixed already (though a few of the grammar issues
are there - I'll sort those some other time)

**Comment by arr2036** [comment]
Hmm, but there'll never be any releases from the v3.1.x branch.  The only reason we're keeping it around is because people are using it in production environments.

**Comment by alanbuxey** [comment]
yes, I know - and they should have nice clean version :)  - please see
email i sent to your github account relating to 4.0.x and a question...

**Pull request merged**
