### PR TITLE
allow moving RPM raddb location

### PR DESCRIPTION
**Pull request by mcnewton**
use rpmbuild parameter: --define '_sysconfdir /etc'

### CODE REVIEW

**Comment by arr2036** [comment]
Can you do a similar pull request for the master branch too?

**Comment by mcnewton** [comment]
Yeah, it's planned - time pressure on this one and I've not had time to test the master branch one yet.

**Comment by arr2036** [comment]
Cherry-picked it over manually.  I doubt it'll cause problems.

**Comment by mcnewton** [comment]
That was my easy to do job for when I'm asleep in the morning! :)

Thanks. Agreed it should be fine.

**Pull request merged**
