### PR TITLE
Update map.c

### PR DESCRIPTION
**Pull request by alanbuxey**
spelling

### CODE REVIEW

**Comment by jpereira** [comment]
Hi @alanbuxey, are you teacher? haha! :+1:

**Comment by arr2036** [comment]
apparently *sigh*. @alanbuxey for changes that are unlikely to require review, and are related, please use the same pull request, saves my clicking finger +1

**Comment by alanbuxey** [comment]
sorry Arran.....was being very lazy and using the GIT web interface to
update rather than a local GIT clone!!  :-)

**Comment by alandekok** [comment]
Lazy for you, lots more work for us.

**Comment by arr2036** [comment]
Do it on your forked copy, you can still be lazy and use the web interface.

**Comment by alanbuxey** [comment]
doh!  umm... yes. I wasnt being lazy.. I was being stupid too!   :-)

**Pull request merged**
