### PR TITLE
Use SSL_SESSION_get_master_key (OpenSSL 1.1)

### PR DESCRIPTION
**Pull request by stapelberg**
This unbreaks compilation with OpenSSL 1.1

### CODE REVIEW

**Comment by arr2036** [comment]
But breaks all other versions :/

**Comment by alandekok** [comment]
I put patches into v4.0.x which fix this in a compatible way. Please check that.

**Comment by stapelberg** [comment]
> But breaks all other versions :/

Updated the pull request so that it actually is backwards compatible. The only still failing travis builds were broken before, I believe.

> I put patches into v4.0.x which fix this in a compatible way. Please check that.

…but my pull request is for v4.0.x? Where can I find your patches?

**Comment by alandekok** [comment]
The other commits I have were for v4.0.x.  Look at "git log" would show you.

It's commit 9a450772305 which fixes it for the get server/client random.  Something similar is necessary for `SSL_SESSION_get_master_key()`

**Comment by stapelberg** [comment]
> The other commits I have were for v4.0.x. Look at "git log" would show you.
> 
> It's commit 9a45077 which fixes it for the get server/client random. Something similar is necessary for SSL_SESSION_get_master_key()

Yes, I have seen that code, and my pull request follows exactly the same pattern that the referenced commit uses.

I don’t understand what you’re trying to tell me. Did you look at my pull request? Does it need any changes?

**Comment by alandekok** [comment]
Ah... it's inside of the previously-defined `#ifdef`.  I had missed that, sorry.

The only real comment I have then is that the `SSL_SESSION_get_master_key()` should probably be made `static`.  Nothing else in the server source needs it.  And exporting a public version of that symbol could cause problems for others.

**Comment by stapelberg** [comment]
Done.

**Pull request merged**
