### PR TITLE
Add sql_fields for IODBC. refs #993

### PR DESCRIPTION
**Pull request by jpereira**
pull request references for #993

### CODE REVIEW

**Comment by arr2036** [comment]
hmm, i'll redo the iodbc one, that's not right.

**Comment by jpereira** [comment]
About the support for IODBC, this was my solution. 
About the rlm_sql_null, I commited in the same pull request.

**Comment by arr2036** [comment]
IODBC function is actually identical to DB2 :)

**Comment by arr2036** [comment]
There's two functions which you can use to get the column name. I started with the one you used, but it pulls back so much extra crap we don't need. I'll push up the changes and you'll see.

**Comment by jpereira** [comment]
@arr2036  wow !I noted the similarities between ODBC/DB2 and made the patch for IODBC. if you haven't done, i can push up.

**Pull request closed without merging**
