### PR TITLE
Travelping dictionary update

### PR DESCRIPTION
**Pull request by lemenkov**
Update Travelping dictionary according to the commit travelping/eradius@5f5752f3816fd00cb6b3cb96939521e4fc675630 (2017-06-22).

### CODE REVIEW

**Comment by lemenkov** [comment]
Please hold on. I'll push -f everything as soon as I learn how to add GPG-key to my account.

**Comment by arr2036** [comment]
Looks like the framed protocol value is missing a 0x prefix too.

**Comment by lemenkov** [comment]
@arr2036 sorry for that - mislooked an accidental tab pressed during Vi "replace" mode.

**Comment by arr2036** [comment]
@lemenkov would it help if I wrote up some instructions for adding GPG keys to git and github?  A few people have run into this so far, and happily, no one has complained, but there's no reason to make it harder than it needs to be.

**Comment by lemenkov** [comment]
@arr2036 actually GitHub's provided documentation is quite extensive and well-written. So yes, it might be a good idea, but surely not the one which should be on top of your TODO list :)

**Comment by arr2036** [comment]
have you got a link? I'll just add it to the wiki page on contributing

**Comment by lemenkov** [comment]
@arr2036 I've followed this HOWTO

https://help.github.com/articles/signing-commits-with-gpg/

**Pull request merged**
