### PR TITLE
Add the vsa 'Alc-Wlan-SSID-VLAN' for Alcatel 7750

### PR DESCRIPTION
**Pull request by jpereira**
following the document https://infoproducts.alcatel-lucent.com/html/0_add-h-f/93-0088-HTML/7750_SR_RADIUS_Attributes_Reference_Guide/SROS_RADIUS_Attrib.html

@arr2036 Please, replicate in the v3.0.x

### CODE REVIEW

**Comment by jpereira** [comment]
on second thought... @arr2036 can you replicate all the dict share/dictionary.alcatel.sr in the v3.0.x?

**Comment by arr2036** [comment]
do you mean there are attributes in v3.1.x that aren't in v3.0.x? It may have been intentional...

**Comment by arr2036** [comment]
or more, we try not to rename VSAs across branches...

**Comment by jpereira** [comment]
I don't know... i think that the best way it's to have the same dictionaries between the branches. wouldn't you?

**Comment by arr2036** [comment]
No, because then you break people's config when they upgrade the server.

**Comment by arr2036** [comment]
For example if the Alcatel dictionary in v3.0.x had a bunch of attributes like

```
Al-User-Name
Al-VLAN
```

Then they got bought out by Juniper and all the official attribute names changes to

```
JU-User-Name
JU-VLAN
```

and people used the ``AL`` attributes in their configs, the upgrade would break their configs.

**Pull request merged**
