### PR TITLE
Free rad_perlconf_hv in correct perl context

### LINKED ISSUE #1675: Bugs in rlm_perl config {} section handling
# Issue type
- [X] Defect - Crash or memory corruption.

# Defect/Feature description

Using two perl {} sections, if the second one contains a config {} section freeradius crashes.

## How to reproduce issue

System: Git snapshot from today, including the fix for #1674 Debian Jessie, perl 5.20.2-3+deb8u6

To reproduce the stock configfiles without any change and the following addition are enough:

Create a /etc/freeradius/mods-enabled/zzz-perl-crash:
```
 perl a {  
        filename = ${modconfdir}/perl/example.pl
 }
 perl b {
        filename = ${modconfdir}/perl/example.pl
        config {
                three = "three"
        }
 }
```

(No need to use them anywhere to reproduce a crash)

Restart freeradius. (In my case using systemd, with default service file)

Depending on "luck" sometimes results in:
```
 freeradius[5665]: Configuration appears to be OK
 kernel: [2008172.003054] freeradius[5665]: segfault at c131200 ip 00007f9884a768a9 sp 00007ffff968edb0 error 4 in libperl.so.5.20.2[7f98849b8000+1b7000]
```
or
```
 freeradius[5002]: Configuration appears to be OK
 freeradius[5002]: *** Error in `/usr/sbin/freeradius': corrupted double-linked list: 0x0000000000b3fa40 ***
```
or
```
 freeradius[5716]: Configuration appears to be OK
 freeradius[5716]: Attempt to free nonexistent shared string 'three', Perl interpreter: 0x1d022a0 during global destruction.
 freeradius[5716]: Unbalanced string table refcount: (1) for "three" during global destruction.
 freeradius[5716]: Scalars leaked: 1
```
## Output of ``[radiusd|freeradius] -X`` showing issue ocurring

This bug does NOT occur if running as "freeradius -X" ! There (with my full config instead of the reduced reproduction settings) it completely works.

## Full backtrace from LLDB or GDB
```
Starting program: /usr/sbin/freeradius -Cxm -lstdout
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff15e58a9 in ?? () from /usr/lib/x86_64-linux-gnu/libperl.so.5.20
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7fe4740 (LWP 6070) "freeradius" 0x00007ffff15e58a9 in ??
    () from /usr/lib/x86_64-linux-gnu/libperl.so.5.20

Thread 1 (Thread 0x7ffff7fe4740 (LWP 6070)):
#0  0x00007ffff15e58a9 in ?? () from /usr/lib/x86_64-linux-gnu/libperl.so.5.20
No symbol table info available.
#1  0x00007ffff15e67bb in ?? () from /usr/lib/x86_64-linux-gnu/libperl.so.5.20
No symbol table info available.
#2  0x00007ffff15e6a1e in Perl_hfree_next_entry ()
   from /usr/lib/x86_64-linux-gnu/libperl.so.5.20
No symbol table info available.
#3  0x00007ffff15e6c4e in ?? () from /usr/lib/x86_64-linux-gnu/libperl.so.5.20
No symbol table info available.
#4  0x00007ffff15e9f64 in Perl_hv_undef_flags ()
   from /usr/lib/x86_64-linux-gnu/libperl.so.5.20
No symbol table info available.
#5  0x00007ffff18eae62 in mod_detach (instance=0x8f58c0)
    at src/modules/rlm_perl/rlm_perl.c:1003
        inst = 0x8f58c0
        exitstatus = 0
        count = 0
#6  0x00007ffff6ef6650 in ?? () from /usr/lib/x86_64-linux-gnu/libtalloc.so.2
No symbol table info available.
#7  0x00007ffff6eef39b in _talloc_free ()
   from /usr/lib/x86_64-linux-gnu/libtalloc.so.2
No symbol table info available.
#8  0x00007ffff798b847 in free_walker (tree=0x8ca300, x=0x8f7de0)
    at src/lib/rbtree.c:80
No locals.
#9  0x00007ffff798b838 in free_walker (tree=0x8ca300, x=0x8ea030)
    at src/lib/rbtree.c:78
No locals.
#10 0x00007ffff798b827 in free_walker (tree=0x8ca300, x=0x8e6c50)
    at src/lib/rbtree.c:77
No locals.
#11 0x00007ffff798b838 in free_walker (tree=0x8ca300, x=0x8de820)
    at src/lib/rbtree.c:78
No locals.
#12 0x00007ffff798b827 in free_walker (tree=0x8ca300, x=0x8d6a40)
    at src/lib/rbtree.c:77
No locals.
#13 0x00007ffff798b827 in free_walker (tree=0x8ca300, x=0x8cf620)
    at src/lib/rbtree.c:77
No locals.
#14 0x00007ffff798bdfb in rbtree_free (tree=0x8ca300) at src/lib/rbtree.c:93
No locals.
#15 0x0000000000421400 in modules_free () at src/main/modules.c:485
No locals.
#16 0x000000000040f94a in main (argc=<optimized out>, argv=<optimized out>)
    at src/main/radiusd.c:623
        rcode = 0
        status = <optimized out>
        argval = <optimized out>
        spawn_flag = false
        display_version = false
        flag = 0
        from_child = {-1, -1}
        state = 0x0
        autofree = 0x66c070
A debugging session is active.

        Inferior 1 [process 6070] will be killed.

Quit anyway? (y or n) 
```

### PR DESCRIPTION
**Pull request by herwinw**
This should fix #1675

### CODE REVIEW

**Comment by herwinw** [comment]
This fixes the only possible reproduction I could find for #1675. Maybe @haegar would like to test this.

**Comment by arr2036** [comment]
Yeah, looks good.

**Comment by haegar** [comment]
Yes, looks good, thanks a lot!
Cherry-picked ef5600081cd507dfa216eeefe6e529c491c8a672 into my v3.0.x branch, added the config {} sections exporting mysql access infos to my 3 perl scripts, and works fine. Finally only one place where the mysql infos are defined, and not 3.

**Comment by alandekok** [comment]
I've cherry-picked ef5600081cd5 into v3.0.x.

**Pull request merged**
