### PR TITLE
Add Oracle session pool to rlm_sql oracle driver

### PR DESCRIPTION
**Pull request by pobept**
Adding support for receiving connections using the built-in oracle client session mechanism.

Changing the function of preparing a query for execution from OCIStmtPrepare to OCIStmtPrepare2, since this function was deprecated beginning with Oracle Database 12c Release 2 (12.2).
This breaks the ability to use Oracle client below 10g

### CODE REVIEW

**Comment by arr2036** [comment]
Can you give some more background on these changes for people who don't daily interact with instaclient and oracle databases? Will it impact the ability to establish connections asynchronously in future?

**Comment by alandekok** [comment]
I'm happy to disallow using clients below 10g.  That's 10 years old.

**Comment by alandekok** [comment]
If you could sign the commits and squash them together, I think we can pull it into "master" and to v3.

**Comment by pobept** [comment]
> Can you give some more background on these changes for people who don't interact with instaclient and oracle databases daily? Will it impact the ability to establish connections asynchronously in future?

The changes concern only the driver for Oracle, and do not break the architecture of the application, they allow you to get a connection to the database given faster, because for example, an authentication step is scrolling through.
On the other hand, these changes are necessary to enable the query caching mechanism with binding variables.

**Comment by pobept** [comment]
> If you could sign the commits and squash them together, I think we can pull it into "master" and to v3.

Ok, I will sign the changes and re-create MR for v4 and v3

**Comment by pobept** [comment]
In addition, I have a working v4 driver for Oracle and Postgres with xlat templates and binding variables. but they require a bit of refactoring

**Comment by arr2036** [comment]
I'd be interested to see what you did there, even if you just push the code up to a public branch in your repo.

--

In regards to this PR, is it that multiple sessions are multiplexed over a single network connection? Or does the new API manage both sessions and connections (are they the same thing?).

**Comment by pobept** [comment]
> In regards to this PR, is it that multiple sessions are multiplexed over a single network connection? Or does the new API manage both sessions and connections (are they the same thing?).

Sessions and connections are pooled by OCI. Documentation says that, OCI multiplex several OCI sessions over a few physical connections. 

Testing shows that when using the OCI Session pool with parameters min = 1, max = 30, inc = 2 and the number of application threads 30, the same 30 connections are opened to the database.

**Pull request closed without merging**
