### PR TITLE
psql: fix accounting_on query syntax

### PR DESCRIPTION
**Pull request by santigimeno**

### CODE REVIEW

**Comment by arr2036** [comment]
Ug and this is why https://github.com/FreeRADIUS/freeradius-server/issues/830 would be so useful. Thanks for the pull request.

**Comment by santigimeno** [comment]
Wow, that was fast! Thanks. Shouldn't it be backported to branch v3.0.x too?

**Comment by arr2036** [comment]
It already has been, but the cherry pick won't show up in the pull request history.

**Comment by santigimeno** [comment]
Ok I see it now. Thanks again!

**Pull request merged**
