### PR TITLE
Fix seg fault on rlm_python when multiple instances are configured

### PR DESCRIPTION
**Pull request by gyx1000**
If not the first configured instance of a rlm_python module is called first a segmentation fault occurs.

### CODE REVIEW

**Comment by arr2036** [comment]
Thanks for the test cases!  Could you try the version from v3.1.x and see if the issue still occurs? If it's fixed then we could backport that code.  It should allow us to remove the thread concurrency restriction too.

**Comment by gyx1000** [comment]
As the version 3.0.x with no thread support, an issue occurs on mod_detach (see backtrace bellow).
I need time to find a solution. Does someone have an idea ?

#0  0x00007ffff34285da in PyErr_Occurred () at /usr/src/debug/Python-2.7.5/Python/errors.c:80
    80	    return tstate->curexc_type;
#1  0x00007ffff33e971e in PyObject_ClearWeakRefs (object=object@entry=<_thread._localdummy at remote 0x7ffff7f1f170>) at /usr/src/debug/Python-2.7.5/Objects/weakrefobject.c:927
#2  0x00007ffff344e490 in localdummy_dealloc (self=0x7ffff7f1f170) at /usr/src/debug/Python-2.7.5/Modules/threadmodule.c:230
#3  0x00007ffff33bd79f in dict_dealloc (mp=0xaec640) at /usr/src/debug/Python-2.7.5/Objects/dictobject.c:1019
#4  0x00007ffff3438e87 in PyThreadState_Clear (tstate=0x9d3930) at /usr/src/debug/Python-2.7.5/Python/pystate.c:239
#5  0x00007ffff37075cd in python_thread_free (state=0x9d3930) at src/modules/rlm_python/rlm_python.c:499
#6  0x00007ffff3708792 in mod_detach (instance=0x988c60) at src/modules/rlm_python/rlm_python.c:988
#7  0x00007ffff6ed3407 in _talloc_free_internal (ptr=0x988c60, location=0x43c29d "src/main/modules.c:336") at ../talloc.c:1046
#8  0x00007ffff6ed2fdb in _talloc_free_children_internal (location=0x43c29d "src/main/modules.c:336", ptr=0x988bb0, tc=0x988b50) at ../talloc.c:1525
#9  _talloc_free_internal (ptr=0x988bb0, location=0x43c29d "src/main/modules.c:336") at ../talloc.c:1072
#10 0x00007ffff6eccb23 in _talloc_free_children_internal (location=0x43c29d "src/main/modules.c:336", ptr=0x96c610, tc=0x96c5b0) at ../talloc.c:1525
#11 _talloc_free_internal (location=<optimized out>, ptr=<optimized out>) at ../talloc.c:1072
#12 _talloc_free (ptr=0x96c610, location=0x43c29d "src/main/modules.c:336") at ../talloc.c:1647
#13 0x00000000004153a5 in modules_free () at src/main/modules.c:336
#14 0x00000000004225ff in main (argc=10, argv=0x7fffffffe578) at src/main/unittest.c:963

**Comment by arr2036** [comment]
@gyx1000 Yes, my idea is you test the v3.1.x code to see if the problem is still present.

**Comment by gyx1000** [comment]
@arr2036 The traceback was generated with the v3.1.x code.

**Comment by arr2036** [comment]
Try latest v3.1.x head.  Just pushed a possible fix...

**Comment by gyx1000** [comment]
Py_EndInterpreter now raise a Py_FatalError because the PyThreadState passed is not the the current. I tried swapping to it just before call the Py_EndInterpreter with no luck. This Py_FatalError is raised https://github.com/python/cpython/blob/2.7/Python/pythonrun.c#L661

```
#0  0x00007ffff5c4a5f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5c4bce8 in __GI_abort () at abort.c:90
#2  0x00007ffff343a9be in Py_FatalError (msg=msg@entry=0x7ffff3484798 "Py_EndInterpreter: thread is not current")
    at /usr/src/debug/Python-2.7.5/Python/pythonrun.c:1698
#3  0x00007ffff343aab5 in Py_EndInterpreter (tstate=0x9f6de0) at /usr/src/debug/Python-2.7.5/Python/pythonrun.c:661
#4  0x00007ffff37075dd in python_interpreter_free (interp=0x9f6de0) at src/modules/rlm_python/rlm_python.c:499
#5  0x00007ffff370877e in mod_detach (instance=0x98be80) at src/modules/rlm_python/rlm_python.c:984
#6  0x00007ffff6ed3407 in _talloc_free_internal (ptr=0x98be80, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1046
#7  0x00007ffff6ed2fdb in _talloc_free_children_internal (location=0x43cddd "src/main/modules.c:336", ptr=0x98bdd0, tc=0x98bd70) at ../talloc.c:1525
#8  _talloc_free_internal (ptr=0x98bdd0, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1072
#9  0x00007ffff6eccb23 in _talloc_free_children_internal (location=0x43cddd "src/main/modules.c:336", ptr=0x96d690, tc=0x96d630) at ../talloc.c:1525
#10 _talloc_free_internal (location=<optimized out>, ptr=<optimized out>) at ../talloc.c:1072
#11 _talloc_free (ptr=0x96d690, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1647
#12 0x0000000000415535 in modules_free () at src/main/modules.c:336
#13 0x0000000000422793 in main (argc=10, argv=0x7fffffffe568) at src/main/unittest.c:963
```

**Comment by gyx1000** [comment]
@arr2036 Do you know why Py_Finalize is never called ? Indeed python_instances counter is never decremented.

**Comment by arr2036** [comment]
Because some idiot forgot to decrement it when he rewrote the code (oops).  Should work now.  Only issue might be if the atexit() function doesn't fire.  I did have some issues with that previously..

**Comment by gyx1000** [comment]
PyImport_Cleanup now cause a little problem.

```
#0  PyType_IsSubtype (a=0x6361626563617274, b=0x7ffff36cd9e0 <PyModule_Type>) at /usr/src/debug/Python-2.7.5/Objects/typeobject.c:1150
    1150	    if (!(a->tp_flags & Py_TPFLAGS_HAVE_CLASS))
#1  0x00007ffff342f8f2 in PyImport_Cleanup () at /usr/src/debug/Python-2.7.5/Python/import.c:518
#2  0x00007ffff343aadf in Py_EndInterpreter (tstate=0x9f6d50) at /usr/src/debug/Python-2.7.5/Python/pythonrun.c:667
#3  0x00007ffff3707639 in python_interpreter_free (interp=0x9f6d50) at src/modules/rlm_python/rlm_python.c:500
#4  0x00007ffff37087f4 in mod_detach (instance=0x98bdf0) at src/modules/rlm_python/rlm_python.c:993
#5  0x00007ffff6ed3407 in _talloc_free_internal (ptr=0x98bdf0, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1046
#6  0x00007ffff6ed2fdb in _talloc_free_children_internal (location=0x43cddd "src/main/modules.c:336", ptr=0x98bd40, tc=0x98bce0) at ../talloc.c:1525
#7  _talloc_free_internal (ptr=0x98bd40, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1072
#8  0x00007ffff6eccb23 in _talloc_free_children_internal (location=0x43cddd "src/main/modules.c:336", ptr=0x96d690, tc=0x96d630) at ../talloc.c:1525
#9  _talloc_free_internal (location=<optimized out>, ptr=<optimized out>) at ../talloc.c:1072
#10 _talloc_free (ptr=0x96d690, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1647
#11 0x0000000000415535 in modules_free () at src/main/modules.c:336
#12 0x0000000000422793 in main (argc=10, argv=0x7fffffffe568) at src/main/unittest.c:963
(gdb) frame 1
#1  0x00007ffff342f8f2 in PyImport_Cleanup () at /usr/src/debug/Python-2.7.5/Python/import.c:518
518	        if (PyString_Check(key) && PyModule_Check(value)) {
(gdb) frame 0
#0  PyType_IsSubtype (a=0x6361626563617274, b=0x7ffff36cd9e0 <PyModule_Type>) at /usr/src/debug/Python-2.7.5/Objects/typeobject.c:1150
1150	    if (!(a->tp_flags & Py_TPFLAGS_HAVE_CLASS))
```

**Comment by gyx1000** [comment]
I don't know if this can help you. I see that the issue occurs when PyImport_Cleanup try to clean the sys module attached to the interpreter. All modules before sys are cleaned correctly.

Modules list to clean
```
{
    'copy_reg': <module at remote 0x7ffff25f3c20>, 
    'sre_compile': None, 
    '_sre': None, 
    'site': None, 
    '__builtin__': <module at remote 0x7ffff7e4dd00>, 
    'sysconfig': None, 
    '__main__': None, 
    'mod2': None, 
    'abc': None, 
    'posixpath': <module at remote 0x7ffff25dc590>, 
    '_weakrefset': None, 
    'errno': <module at remote 0x7ffff25dc398>, 
    'sre_constants': None, 
    're': None, 
    '_abcoll': <module at remote 0x7ffff25f3520>, 
    'types': <module at remote 0x7ffff25dcd00>, 
    '_warnings': None, 
    'genericpath': <module at remote 0x7ffff25dc8a0>, 
    'stat': <module at remote 0x7ffff25dc750>, 
    'zipimport': None, 
    '_sysconfigdata': None, 
    'warnings': <module at remote 0x7ffff25dcc58>, 
    'UserDict': <module at remote 0x7ffff25f3168>, 
    'sys': <module at remote 0x7ffff7e4d130>, 
    'radiusd': <unknown at remote 0x7ffff7e5cd70>, 
    'os.path': <module at remote 0x7ffff25dc590>, 
    '_weakref': None, 
    'traceback': None, 
    'linecache': <module at remote 0x7ffff25dccc8>, 
    'posix': None, 
    'sre_parse': None, 
    'os': <module at remote 0x7ffff25dc360>
}
```

```
517     while (PyDict_Next(modules, &pos, &key, &value)) {
(gdb) print key
$24 = 'sys'
(gdb) n
518         if (PyString_Check(key) && PyModule_Check(value)) {
(gdb) n

Program received signal SIGSEGV, Segmentation fault.
PyType_IsSubtype (a=0x6361626563617274, b=0x7ffff36cd9e0 <PyModule_Type>) at /usr/src/debug/Python-2.7.5/Objects/typeobject.c:1150
1150        if (!(a->tp_flags & Py_TPFLAGS_HAVE_CLASS))

(gdb) print a->tp_flags
Cannot access memory at address 0x636162656361731c
```

**Comment by gyx1000** [comment]
Now the issue occur on the last "Py_EndInterpreter" as explain in my last post at the end.

**Comment by arr2036** [comment]
Sounds like the atExit callback isn't firing for the thread local storage.   Could you augment the ``_python_thread_free`` function.

Something like ``fprintf(stderr, "Destroying thread %p\n", thread);``

**Comment by gyx1000** [comment]
I augment the function and effectively, I can't see the print.

```
(0)  } # server default
(0)  Virtual server sending reply
Access-Accept
Exiting normally
Fatal Python error: Py_EndInterpreter: not the last thread

Program received signal SIGABRT, Aborted.
0x00007ffff5c4a5f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
Missing separate debuginfos, use: debuginfo-install keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 pcre-8.32-15.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64
(gdb) bt
#0  0x00007ffff5c4a5f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5c4bce8 in __GI_abort () at abort.c:90
#2  0x00007ffff343a9be in Py_FatalError (msg=msg@entry=0x7ffff34847f8 "Py_EndInterpreter: not the last thread") at /usr/src/debug/Python-2.7.5/Python/pythonrun.c:1698
#3  0x00007ffff343aada in Py_EndInterpreter (tstate=0x9d49b0) at /usr/src/debug/Python-2.7.5/Python/pythonrun.c:665
#4  0x00007ffff37076b9 in python_interpreter_free (interp=0x9d49b0) at src/modules/rlm_python/rlm_python.c:500
#5  0x00007ffff37088a6 in mod_detach (instance=0x989ce0) at src/modules/rlm_python/rlm_python.c:1001
#6  0x00007ffff6ed3407 in _talloc_free_internal (ptr=0x989ce0, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1046
#7  0x00007ffff6ed2fdb in _talloc_free_children_internal (location=0x43cddd "src/main/modules.c:336", ptr=0x989c30, tc=0x989bd0) at ../talloc.c:1525
#8  _talloc_free_internal (ptr=0x989c30, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1072
#9  0x00007ffff6eccb23 in _talloc_free_children_internal (location=0x43cddd "src/main/modules.c:336", ptr=0x96d690, tc=0x96d630) at ../talloc.c:1525
#10 _talloc_free_internal (location=<optimized out>, ptr=<optimized out>) at ../talloc.c:1072
#11 _talloc_free (ptr=0x96d690, location=0x43cddd "src/main/modules.c:336") at ../talloc.c:1647
#12 0x0000000000415535 in modules_free () at src/main/modules.c:336
#13 0x0000000000422793 in main (argc=10, argv=0x7fffffffe578) at src/main/unittest.c:963
```

**Comment by arr2036** [comment]
OK, FreeRADIUS does mess with stderr/stdout a lot... It might work with the ERROR( macro.  I did find something that *may* have stopped the thread local destructors firing.  Apparently the destructor for a pthread_key is only called in the value is non-null, and we never actually set a key value if the __Thread_local storage class was available.

**Comment by gyx1000** [comment]
Ok, I make some changes on rlm_python.c and now all the test pass correctly with thread support and without. I create a branch in my forked repo but I don't have create a PR because I'm not sure if it's ok for you. Can you check if my changes are correct ?

https://github.com/gyx1000/freeradius-server/commit/c730eb7bdcb67792709bf18ef02e03b2a219b07b

**Comment by arr2036** [comment]
Ok, swapping to main thread state before Py_Finalize() works.  We need Py_ThreadState for each sub interpreter because that enables Thread Local Storage for threads, which is something many users use to cache connections in rlm_python.

The cext_compat fix looks good... Could you make a pull request with the first and last of those fixes, and your test cases.  Then i'll work on the other issues locally.

Thanks!

**Comment by gyx1000** [comment]
I think that a PyInterpreter is enough for tls? Because they are Thread State. Am I wrong ? I wrote the tests for that and caching works.

**Comment by arr2036** [comment]
That didn't used to work, but the first version of rlm_python didn't have subinterpreters.  If you could include those tests in your PR, that'd be great, then I can double check and make sure the behaviour is what's expected.

**Comment by gyx1000** [comment]
I create the PR #1596 
Hope it can help to fix this issue.

**Comment by gyx1000** [comment]
Ha... Yes, I was only testing rlm_python with the unittest framework. I'm sorry, I was not clear...
Do you have a procedure for test with real thread ? Or can I simply run a radiusd server and send multiple radius requests ?

**Comment by arr2036** [comment]
That's pretty much it for now :\

radclient has a -p option that can be used to send multiple parallel requests from a file.

**Comment by gyx1000** [comment]
Perfect, Now I'm armed to test correctly my changes :)
With all this changes, can you backport to v3.0.x ?

**Comment by arr2036** [comment]
Yes, i'll just copy the v3.1.x module back into v3.0.x, and change the API calls.

**Comment by gyx1000** [comment]
I think we can use the radiusd contants for returns in python MODULE-TEST.

**Comment by arr2036** [comment]
yes should work

**Comment by gyx1000** [comment]
I try to understand why we need to attach a second ThreadState to each SubInterpreters.
Indeed, `Py_NewInterpreter()` already created his own ThreadState [Py_NewInterpreter source](https://github.com/python/cpython/blob/2.7/Python/pythonrun.c#L589).

Simply Swapping to this ThreadState isn't enough for TLS ?

**Comment by arr2036** [comment]
There has to be one ThreadState per thread.  Accessing the same ThreadState from multiple threads would probably lead to memory corruption.  There'd also be no way it could store thread local variables specific to a thread without multiple thread states.

Or at least that's how I remember the requirements.  Are there still issues?

**Comment by gyx1000** [comment]
Ah I see. I was thinking that we have only one threadstate per module...
Thanks for the clarification

**Comment by arr2036** [comment]
Did you get a chance to test?  If there are no problems I can backport to v3.0.x.

**Comment by gyx1000** [comment]
Yes it's working. For me you can backport. I think I can improve tests "unittest". Use radiusd constant for returns. Should I create a CR after backport ?

**Comment by arr2036** [comment]
Sure

**Pull request closed without merging**
