### PR TITLE
Clarify sqlippool operation and queries, change defaults

### PR DESCRIPTION
**Pull request by abatie**
Comments updated to describe operation of sqlippool and the supporting queries.

Also changed default queries to preserve user info, allowing reuse of ip addresses after disconnects or outages.

### CODE REVIEW

**Comment by arr2036** [comment]
Comments are useful, but why are the clear queries commented out?

**Comment by arr2036** [comment]
Ah that's the preserving user info part?  I'd request those queries not be changed unless that's the default for other languages.

**Comment by abatie** [comment]
On 2/8/16 4:22 PM, Arran Cudbard-Bell wrote:
> Comments are useful, but why are the clear queries commented out?

Clearing all the entries for a NAS on startup/shutdown removes the
information needed to allow users to get the same ip address they had
before.  I should probably split this into two requests, but the
comments were sorta tied to the specific queries...

**Comment by abatie** [comment]
On 2/8/16 4:25 PM, Arran Cudbard-Bell wrote:
> Ah that's the preserving user info part? I'd request those queries not
> be changed unless that's the default for other languages.

Yes, that makes sense.

**Pull request closed without merging**
