### PR TITLE
CI: Package tests including reuse of eapol_test tests in post-install context

### PR DESCRIPTION
**Pull request by terryburton**
RPMs: https://github.com/terryburton/freeradius-server/actions/runs/421435552
DEBs: https://github.com/terryburton/freeradius-server/actions/runs/421435549

### CODE REVIEW

**Comment by arr2036** [comment]
Is there any reason not to use the existing EAP test config and eapol_test configuration files?

**Comment by terryburton** [comment]
Maybe, I haven't looked. I'm out of time for a day or two and there are some build system issues that I want to address first...

My goal for this is to have something that will flag up any glaring run time issues with OpenSSL, the dynamic linker, etc. which this first iteration should achieve.

It's a shame we can't detect SELinux issues with this approach, however we hopefully can do this in future when the CI system switches to a modern kernel.

**Comment by alandekok** [comment]
as of commit 89ee420077201f6e you should be able to do `make eapol_test`, and it will build _only_ the `eapol_test` binary.

**Comment by terryburton** [comment]
@alandekok That's nice. Thanks.

Rebased and updated workflow for DEB to always use it. Also doing RPM now...

**Comment by terryburton** [comment]
> Rebased and updated workflow for DEB to always use it. Also doing RPM now...

Done. Package build is clean.

**Comment by terryburton** [comment]
Ignore for now: Pushed to wrong branch. Sorry for the noise.

**Comment by terryburton** [comment]
This now reuses the eapol_test CI test but in post-install context without requiring any additional run-time dependencies (other than any non-ancient version of GNU Make).

**Comment by arr2036** [comment]
Hm do we still need those config files embedded in the workflow?

**Comment by terryburton** [comment]
> Hm do we still need those config files embedded in the workflow?

Their benefit is only marginal. I've culled them.

**Pull request merged**
