### PR TITLE
V3.0.x openssl 1.1 fix 2

### PR DESCRIPTION
**Pull request by spbnick**
Some more fixes for OpenSSL v1.1.0 compatibility.
Not actually tested apart from building.

### CODE REVIEW

**Comment by spbnick** [comment]
@mcnewton, could you please take a look at my rlm_eap_pwd changes? They touch what you were fixing recently. Thank you.

**Comment by mcnewton** [comment]
@spbnick not me? Or I've been coding in my sleep again.

**Comment by spbnick** [comment]
@mcnewton, no, it's you after all, even though I failed to verify that before calling you :) I'm talking about the fix in #1876. The a28b2a49dff in particular. You added calls to HMAC_CTX_init and now I removed them.

**Comment by mcnewton** [comment]
Oh, yeah, I did. My memory has gone, I don't even remember that :-(

So from the look of it you've kept initialising the context by now calling HMAC_CTX_new rather than HMAC_CTX_init? As long as #1876 doesn't come back.

**Pull request merged**
