### PR TITLE
fix the  Null pointer dereference: prefix

### PR DESCRIPTION
**Pull request by zengwei2000**
fix the  Null pointer dereference: prefix

Signed-off-by: zengwei zengwei1@uniontech.com

### CODE REVIEW

**Review by arr2036 — COMMENTED** [review]
Prefix will always be NULL in this branch so the patch is pointless.

**Comment by zengwei2000** [comment]
> Prefix will always be NULL in this branch so the patch is pointless.

So the fprintf content here should be error instead of prefix？

**Comment by zengwei2000** [comment]
> Prefix will always be NULL in this branch so the patch is pointless.

https://github.com/FreeRADIUS/freeradius-server/pull/5251  I have resubmitted the PR, please review whether it should be modified like this

**Comment by arr2036** [comment]
Yes

**Pull request closed without merging**
