### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
weird, the editor is showing a syntax error. therefore, it is related to the _macro_ `fr_value_box_list_foreach_safe`

**Comment by alandekok** [comment]
The macro is a little weird. :(

**Comment by arr2036** [comment]
Yeah you need the extra closing curly brace.  Not really any other way to fix it unfortunately.

**Comment by arr2036** [comment]
Unless maybe have a loop close macro or something?

**Comment by jpereira** [comment]
I'd suggest something like top macro. it looks reasonable.

**Pull request closed without merging**
