### PR TITLE
rlm_sql_oracle: Add support to the version '18' also

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by arr2036** [comment]
Are you sure a subversion isn't required? Most of the examples show the subversion in the path ``export LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client/lib:$LD_LIBRARY_PATH``

**Comment by arr2036** [comment]
https://www.oracle.com/database/technologies/instant-client/linux-x86-32-downloads.html

**Comment by jpereira** [comment]
The library uses the $major number.

```
[jpereira@sugarloaf Downloads]$ unzip -l instantclient-basic-linux-18.3.0.0.0dbru.zip
Archive:  instantclient-basic-linux-18.3.0.0.0dbru.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    31934  07-01-2018 09:25   instantclient_18_3/adrci
     1313  07-01-2018 09:25   instantclient_18_3/BASIC_README
    45209  07-01-2018 09:25   instantclient_18_3/genezi
  6788398  07-01-2018 09:25   instantclient_18_3/libclntshcore.so.18.1
       17  07-01-2018 09:25   instantclient_18_3/libclntsh.so
 63828690  07-01-2018 09:25   instantclient_18_3/libclntsh.so.18.1
  5724833  07-01-2018 09:25   instantclient_18_3/libnnz18.so
       15  07-01-2018 09:25   instantclient_18_3/libocci.so
  1011968  07-01-2018 09:25   instantclient_18_3/libocci.so.18.1
126937958  07-01-2018 09:25   instantclient_18_3/libociei.so
   174930  07-01-2018 09:25   instantclient_18_3/libocijdbc18.so
   313251  07-01-2018 09:25   instantclient_18_3/libons.so
    84303  07-01-2018 09:25   instantclient_18_3/liboramysql18.so
        0  07-01-2018 09:25   instantclient_18_3/network/
  4161744  07-01-2018 09:25   instantclient_18_3/ojdbc8.jar
  1398331  07-01-2018 09:25   instantclient_18_3/ucp.jar
   191012  07-01-2018 09:25   instantclient_18_3/uidrvci
    74263  07-01-2018 09:25   instantclient_18_3/xstreams.jar
        0  07-01-2018 09:25   instantclient_18_3/network/admin/
      502  07-01-2018 09:25   instantclient_18_3/network/admin/README
---------                     -------
210768671                     20 files
[jpereira@sugarloaf Downloads]$```

**Comment by jpereira** [comment]
```
[jpereira@sugarloaf Downloads]$ ls -1 instantclient-basic-linux*.zip
instantclient-basic-linux-11.2.0.4.0.zip
instantclient-basic-linux-12.1.0.2.0.zip
instantclient-basic-linux-12.2.0.1.0.zip
instantclient-basic-linux-19.3.0.0.0dbru.zip
instantclient-basic-linux32-11.1.0.7.zip
[jpereira@sugarloaf Downloads]$ ls instantclient-basic-linux*.zip | while read a; do unzip -l $a; done | grep libnnz
  7098468  08-25-2013 08:18   instantclient_11_2/libnnz11.so
  5323903  07-08-2014 07:44   instantclient_12_1/libnnz12.so
  5678829  02-01-2017 07:15   instantclient_12_2/libnnz12.so
  5700744  04-22-2019 14:44   instantclient_19_3/libnnz19.so
  5974910  10-26-2008 23:14   instantclient_11_1/libnnz11.so
[jpereira@sugarloaf Downloads]$
```

Always using the `$major` number.

**Comment by arr2036** [comment]
The issue here is that we won't actually look in the default install locations for the various versions, but I guess people can just specify the paths manually.  I don't know why 12.1 is included in the version list.  I think that was an external contribution, maybe it should be removed.

**Pull request merged**
