### PR TITLE
Add support for ldap, mysql and postgres tests through the use of an ext...

### PR DESCRIPTION
**Pull request by pwdng**
...ernal VM.

### CODE REVIEW

**Comment by arr2036** [comment]
Just for easier merging, could this be broken out into separate commits. One for tests, one for setup and others for bug fixes and schema changes. Thanks!

**Comment by alanbuxey** [comment]
any more details about this work/patch - how it operates, what is needed to
use it? cheers

**Comment by arr2036** [comment]
You set ``<module>_TEST_SERVER``  in the environment and run make test.

**Comment by pwdng** [comment]
You can have any of LDAP, MySQL and or Postgres running on a server/VM and corresponding module tests will run against this host if the corresponding environment variable is set:
LDAP_TEST_SERVER, SQL_MYSQL_TEST_SERVER, SQL_POSTGRESQL_TEST_SERVER
or
TEST_SERVER if all are available.
(value should be IP of host)

**Comment by alanbuxey** [comment]
how do you use certificates/credentials for the test? uses the values in
the .conf files?

**Comment by pwdng** [comment]
Yes, it uses the local module.conf in the corresponding directory.

**Pull request merged**
