### PR TITLE
Docker container v4

### PR DESCRIPTION
**Pull request by svlentink**
Since v4 enables dynamic realms, I would like to put a basis for v4 out here, for people to join on development and debugging.

### CODE REVIEW

**Comment by arr2036** [comment]
Is there something wrong with the existing docker files in master branch?

**Comment by svlentink** [comment]
Yes, that one gives an error

```
Step 13/13 : RUN /opt/freeradius/sbin/radiusd -XC
 ---> Running in 96e4652f2bea
Getting debug state failed: ptrace capability not set.  If debugger detection is required run as root or: setcap cap_sys_ptrace+ep <path_to_radiusd>
Info  : FreeRADIUS Version 4.0.0
Info  : Copyright 1999-2019 The FreeRADIUS server project and contributors
Info  : There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
Info  : PARTICULAR PURPOSE
Info  : You may redistribute copies of FreeRADIUS under the terms of the
Info  : GNU General Public License
Info  : For more information about these matters, see the file named COPYRIGHT
Error : tls - Failed initialising protocol library: from $INCLUDE at /opt/freeradius/share/freeradius/dictionary/radius/dictionary[95]
Error : Error reading /opt/freeradius/share/freeradius/dictionary/radius/dictionary.rfc2865[12]
Error : Unknown option 'encrypt'
radiusd
The command '/bin/sh -c /opt/freeradius/sbin/radiusd -XC' returned a non-zero code: 1
```

**Comment by alandekok** [comment]
Please submit fixes to the existing scripts instead of re-inventing the wheel.

**Comment by svlentink** [comment]
OK. Wasn't able to get it working with 2 days of working on it from different angles. Will try it again in a couple of months.

**Pull request closed without merging**
