### PR TITLE
Ignore non http version headers in init state

### PR DESCRIPTION
**Pull request by kck325**
Version: FreeRadius 3.0.x
Issue: Some servers return server name and date headers along with http version header. It is throwing out freeradius rest server. While in init state, ignore other headers.

### CODE REVIEW

**Comment by arr2036** [comment]
Hm, weird.  Are they allowed to do that? :)

**Comment by kck325** [comment]
yeah rfc says so.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.2

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by arr2036** [comment]
You've not really cited anything that supports your claims.  

The format of the response is:
```text
After receiving and interpreting a request message, a server responds with an HTTP response message.

       Response      = Status-Line               ; Section 6.1
                       *(( general-header        ; Section 4.5
                        | response-header        ; Section 6.2
                        | entity-header ) CRLF)  ; Section 7.1
                       CRLF
                       [ message-body ]          ; Section 7.2
```

The status line is:

```text
Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
```

So the first component of any HTTP response should be the status line.  If your server is responding without the Status line, your server is not in compliance with RFC2616 and is unsupported.

**Pull request closed without merging**
