### PR TITLE
Adding radiusMaxDailySession to LDAP schema

### PR DESCRIPTION
**Pull request by MCMic**
PR as asked in ticket #1144

### CODE REVIEW

**Comment by alandekok** [comment]
Why is this needed?  What is the use-case for it?

**Comment by MCMic** [comment]
I don’t know the exact use case as I’m not the author of #1144 , but shouldn’t all options be available through the LDAP backend? What it the rule?

**Comment by alandekok** [comment]
There are about 8000 RADIUS attributes in all of the various dictionaries.  There is *no* need to have all of them in LDAP.

**Comment by arr2036** [comment]
There's a generic ldap attribute that can represent all attributes.  No need for specific ldap schema attributes.

Whoever opened the issue didn't specify *which* schema.  So it was easier to say 'show me'.

**Comment by MCMic** [comment]
What is the generic attribute?

**Comment by arr2036** [comment]
``radiusAttribute``

**Comment by arr2036** [comment]
There there are list specific ones ``radiusControlAttribute`` ``radiusReplyAttribute`` ``radiusRequestAttribute ``

**Pull request closed without merging**
