### PR TITLE
CA path reload interval v3.0.x

### PR DESCRIPTION
**Pull request by lytboris**
Created to ease review

### CODE REVIEW

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by alandekok** [comment]
Hmm... this should really go in.  I don't have time to do it before 3.0.16, but it will be on my short list after that.

Sorry for the delay.

**Comment by noahwilliamsson** [comment]
Is there any chance this PR could be rebased and merged to both the v3.0.x and master branches?

It would be great to have this feature available so AAA didn't temporarily break during FreeRADIUS restarts because of the need to refresh CRLs.

Thanks!

**Comment by lytboris** [comment]
@alandekok , do you have a milestone to merge it in?
It would be a bit painful to re-write this PR so it could be merged into today's 3.0.x and wait forever for a merge still.

**Comment by alandekok** [comment]
It's been too long, sorry.

Yes, we should add this to v3.

**Comment by bobmc67** [comment]
The lack of this feature has bugged me for years (using FreeRADIUS for 802.1x EAP-TLS auth) so I can't wait to see this merged and later show up in Long-Term Support releases of popular Linux distributions.

**Comment by lytboris** [comment]
OpenSSL 1.1.1 support is done somewhat wrong, it makes radiusd crash upon store swap. Will update patch once I find a way to fix that.

**Pull request merged**
