### PR TITLE
add name option back to tls cache

### PR DESCRIPTION
**Pull request by mcnewton**

### CODE REVIEW

**Comment by arr2036** [comment]
Ak, no I meant add a CONF_PARSER array element that marks it as deprecated (if that got removed).  sorry for the confusion...

**Comment by mcnewton** [comment]
ah, sorry - the conf_parser option is there, just not marked as deprecated (neither are the other deprecated options)

**Comment by mcnewton** [comment]
how's that now?

**Comment by arr2036** [comment]
Did you see how that code's been restructured in v3.1.x? :)

**Comment by mcnewton** [comment]
Haven't had a look yet - when I get a spare hour (haha) :) I know you've been hacking on it!

**Pull request merged**
