### PR TITLE
4.0.x - rest - curl option CURLOPT_CAINFO

### PR DESCRIPTION
**Pull request by nchaigne**
Port to "master" of https://github.com/FreeRADIUS/freeradius-server/pull/2167

### CODE REVIEW

**Comment by arr2036** [comment]
This introduces configuration item ambiguity.  `ca_file` in other contexts typically means the certificates used to build the chain for the certificate being offered, or the chain to validate the certificate being presented.  That _seems_ more like what ca_info_file does.  The original fix in v3.0.x should have been to swap the curl options used, and add a "certificate_issuer_file" config item to allow the user to specify which cert in the chain was actually used.

**Comment by nchaigne** [comment]
We discussed that at the time on the mailing list for the v3 pull request. The goal was to not change existing configuration, so people using the curl module would not be impacted. The new configuration item name was a compromise.

But maybe with v4 it's acceptable to rename (and break things) ?

**Comment by alandekok** [comment]
Yes, v4 implements breaking changes.  We should "do it the right way" here.

**Comment by nchaigne** [comment]
Alright then. Agreed on the following names ?
"ca_file" for "CURLOPT_CAINFO" (the bundle of certificates) - which is shown as "CAfile" in curl verbose output
"certificate_issuer_file" for "CURLOPT_ISSUERCERT"

**Comment by arr2036** [comment]
It's ok, I'm putting together a patch that documents the rest of the cert configuration options too

**Comment by nchaigne** [comment]
Good documentation :)
Thanks!

**Pull request closed without merging**
