### PR TITLE
Ca path reload interval v4.0.x

### PR DESCRIPTION
**Pull request by lytboris**
See #1577 for more info

### CODE REVIEW

**Comment by lytboris** [comment]
any news?

**Comment by alandekok** [comment]
We're still working on 4.0 re-architecture.  But yes... the patch is a good idea.

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by nwkrad** [comment]
Can one of the admins verify this patch?

**Comment by bigbig6** [comment]
Is this patch will be merged a day?

Thanks'

Regards,

Big

**Pull request closed without merging**
