### PR TITLE
Update debian folder, fix minor bugs

### PR DESCRIPTION
**Pull request by mans0954**
Various updates to the debian folder for closer alignment with current Debain policy and compatibility with unstable. Also fix some minor issues identified by lintian.

### CODE REVIEW

**Comment by arr2036** [comment]
Generally commits should be split by purpose.  Can you go and do that. Can you also rebase to remove the merge commits.

**Comment by jpereira** [comment]
try

# git checkout origin v3.1.x
# git pull --rebase
# git push -f

**Comment by mans0954** [comment]
I tried that:

git checkout origin v3.1.x
error: pathspec 'v3.1.x' did not match any file(s) known to git.

# git checkout origin/v3.1.x
Note: checking out 'origin/v3.1.x'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 9e8ed1f... Correct minor issues with package descriptions

# git pull --rebase
You are not currently on a branch. Please specify which
branch you want to rebase against. See git-pull(1) for details.

    git pull <remote> <branch>

# git pull --rebase upstream/v3.1.x
fatal: 'upstream/v3.1.x' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

# git pull --rebase upstream v3.1.x
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14 (delta 5), reused 4 (delta 4), pack-reused 1
Unpacking objects: 100% (14/14), done.
From https://github.com/FreeRADIUS/freeradius-server
 * branch            v3.1.x     -> FETCH_HEAD
   2c22373..617e9b1  v3.1.x     -> upstream/v3.1.x
First, rewinding head to replay your work on top of it...
Applying: Fix unescaped single quote at begining of line in man/man5/rlm_passwd.5
Applying: Updated dh compat to 9
Applying: Add DEP-3 headers to patches
Applying: Adjust debian/patches/logrotate-path.diff in line with commit e82215b
Applying: Fix spelling mistakes identified by lintian
Applying: Use buildflags to enable hardening (https://wiki.debian.org/Hardening)
Applying: Correct minor issues with package descriptions
# git push -f
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

This looked wrong, so I started again:

#git checkout v3.1.x
Warning: you are leaving 7 commits behind, not connected to
any of your branches:

  4f6dfb6 Correct minor issues with package descriptions
  7b6e162 Use buildflags to enable hardening (https://wiki.debian.org/Hardening)
  aa59e55 Fix spelling mistakes identified by lintian
  97d9611 Adjust debian/patches/logrotate-path.diff in line with commit e82215b
 ... and 3 more.

If you want to keep them by creating a new branch, this may be a good time
to do so with:

 git branch new_branch_name 4f6dfb6

Switched to branch 'v3.1.x'
Your branch is up-to-date with 'origin/v3.1.x'.

# git pull --rebase
Current branch v3.1.x is up to date.

# git push -f
Everything up-to-date

So that doesn't appear to have done anything?

Sorry, I am not very familiar with pull requests. This is what I have set up:

git remote -v
origin	https://github.com/mans0954/freeradius-server.git (fetch)
origin	https://github.com/mans0954/freeradius-server.git (push)
upstream	https://github.com/FreeRADIUS/freeradius-server.git (fetch)
upstream	https://github.com/FreeRADIUS/freeradius-server.git (push)

git branch -a
* v3.1.x
  remotes/origin/HEAD -> origin/v3.1.x
  remotes/origin/coverity_scan
  remotes/origin/master
  remotes/origin/revert-1204-patch-1
  remotes/origin/v1.1.x
  remotes/origin/v2.1.x-apple
  remotes/origin/v2.x.x
  remotes/origin/v3.0.x
  remotes/origin/v3.1.x
  remotes/upstream/v3.1.x

**Comment by mans0954** [comment]
I tried:

\# git checkout v3.1.x
\# git pull --rebase upstream v3.1.x
\# 2351  git push -f

Is that better?

**Comment by arr2036** [comment]
Perfect, thanks!

**Pull request merged**
