### PR TITLE
Update rlm_python.c

### PR DESCRIPTION
**Pull request by alejandro-perez**
This includes missing log level codes that are present on log.h

### CODE REVIEW

**Comment by qnet-herwin** [comment]
It looks like the indentation is not consistent (tabs and spaces mixed up)

**Comment by alejandro-perez** [comment]
Umm, it should have been the WSYIWYG editor of github... I'll try again later.

**Comment by alejandro-perez** [comment]
The new PR should fix inconsistent tabs/spaces.

**Comment by qnet-herwin** [comment]
Two very minor remarks:

* The line with `L_DBG_ERR_REQ` has a trailing tab character
* It would be cleaner to squash these two commits into one

I've got no idea if that second thing is possible to do using the github editor though.

**Comment by alejandro-perez** [comment]
I'll redo it again and submit a new pull-request soon.

**Pull request closed without merging**
