### PR TITLE
incorporate all redhat specific files into the tarball

### PR DESCRIPTION
**Pull request by mattrose**
There's no sense in having separate Source entries in the spec file for files that exist in the distribution tarball in the first place.

### CODE REVIEW

**Comment by mattrose** [comment]
retest this please

**Comment by spaetow** [comment]
I'd review this PR again given how RH themselves ship their specific files (installed into rpmbuild/SOURCES from the .src.rpm) and hence the existing SOURCE file entries. Of course, if you work for RH and are now making changes, go right ahead 👍

**Comment by mattrose** [comment]
I don't work for Redhat or anything like that, I'm just trying to make their lives (and mine) a little easier.  I do maintain a few packages for Fedora.

With RPMs, the extra files in SOURCES are changes or files that do not exist in the upstream tarball that are necessary to incorporate the upstream tarball contents into the distribution, patches, extra initialization files, etc.  Since we have taken these files and incorporated them into the tarball that we distribute, there's no need for them to be listed separately in SOURCES.

**Comment by spbnick** [comment]
Hi @mattrose, @spaetow, this is alright with Red Hat, since we don't use those files ATM. I will consider using the files from the tarball on the next rebase.

**Comment by spaetow** [comment]
Thanks, @spbnick! 👍

**Comment by mattrose** [comment]
retest this please

**Comment by mattrose** [comment]
retest this please

**Pull request closed without merging**
