### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by x-jokay**
Updates the license using the correct template from [licenses /
license-templates](https://github.com/licenses/license-templates/blob/master/templates/gpl2.txt) so it gets correctly recognized by GitHub too 😉 

And this is what it will look like:

license

### CODE REVIEW

**Comment by arr2036** [comment]
Fine with this in principle.  Looks to be mostly formatting changes.  Only bit that stands out is changing `Lesser` to `Library` in the final paragraph. @alandekok are you ok with this?

**Comment by x-jokay** [comment]
You are right, given the fact [this](https://github.com/ome/bioformats/blob/develop/LICENSE.txt) gets recognized as well, you may try this which results in lesser changes.

**Comment by x-jokay** [comment]
Strange, it seems it didn't work 🧐

**Comment by x-jokay** [comment]
Could be due to multiple `LICENSE` files, e.g. [here](https://github.com/FreeRADIUS/freeradius-server/blob/master/doc/LICENSE).

**Pull request merged**
