### PR TITLE
implement radiusd::radius_xlat in rlm_perl (v3.0.x)

### PR DESCRIPTION
**Pull request by lytboris**
v 3.0 variant of #1822

### CODE REVIEW

**Comment by lytboris** [comment]
No need to redo it without perl SVs?

**Comment by lytboris** [comment]
Applied all but SVs changes that were noted in v3.1 pull request. Seems to be ready to be merged.

**Comment by arr2036** [comment]
Can you squash the commits, then i'll merge the pull request.

**Comment by lytboris** [comment]
Squashed.

**Comment by arr2036** [comment]
Ugh and rebase to fix the ChangeLog

**Comment by lytboris** [comment]
Now build is broken because of commits merged! Fantastic...

**Comment by alandekok** [comment]
I've pushed a fix.

**Pull request merged**
