### PR TITLE
rlm_python3: Fix build against Python 3.8.x

### PR DESCRIPTION
**Pull request by jpereira**
We don't need the -specs=/... that comes from Python

### CODE REVIEW

**Comment by jpereira** [comment]
The current `python3-config --cflags` is returing `-specs=...` on Ubuntu 20.04.

```
checking for a Python interpreter with version >= 3.0... python3
checking for python3... /bin/python3
checking for python3 version... 3.8
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.8/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.8/site-packages
checking for python3-config... python3-config
configure: python3-config's cflags were "-I/usr/include/python3.8 -I/usr/include/python3.8  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.8-6QL2k7/python3.8-3.8.2=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack
-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall"
configure: Sanitized cflags were "-isystem/usr/include/python3.8 -isystem/usr/include/python3.8    -fdebug-prefix-map=/build/python3.8-6QL2k7/python3.8-3.8.2=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector   -fwrapv  "
checking for gawk... no
checking for mawk... mawk
configure: python3-config's ldflags were "-L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -L/usr/lib -lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm }"
configure: Sanitized ldflags were "-L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -L/usr/lib -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm"
checking for dl_iterate_phdr... yes
configure: creating ./config.status
config.status: creating all.mk
config.status: creating config.h
config.status: config.h is unchanged
configure: WARNING: unrecognized options: --enable-developer, --enable-werror, --with-kqueue-include-dir, --with-kqueue-lib-dir, --with-rlm-python-bin, --without-rlm-lua, --without-rlm-mruby
CC src/modules/rlm_python3/rlm_python3.c
clang: error: argument unused during compilation: '-specs=/usr/share/dpkg/no-pie-compile.specs' [-Werror,-Wunused-command-line-argument]
make: *** [scripts/boiler.mk:635: build/objs/src/modules/rlm_python3/rlm_python3.lo] Error 1
````

**Comment by arr2036** [comment]
You see how every other argument has a comment above the pattern block, tell you why it was stripped out...

**Comment by jpereira** [comment]
The `-specs=/path/whatever.specs` is a compiler option to load extra options from a .spec file. More about the option [here](https://gcc.gnu.org/onlinedocs/gcc/Spec-Files.html).

Looks that it is appearing recently on Ubuntu 20.04 + Python 3.8.2 as can be seen below.

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
# python3-config --cflags
-I/usr/include/python3.8 -I/usr/include/python3.8  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.8-6QL2k7/python3.8-3.8.2=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall
#
```

Even I've used the reference https://fedoraproject.org/wiki/Changes/Python_Extension_Flags#The_Problem and https://fedoraproject.org/wiki/Changes/Python_Extension_Flags#The_Solution

**Comment by jpereira** [comment]
Ah! I've noticed that the Ubuntu `python-3.8.2.deb` scheme is stripping out too.

```
# cd /tmp
# wget -qO - http://archive.ubuntu.com/ubuntu/pool/main/p/python3.8/python3.8_3.8.2-1ubuntu1.1.debian.tar.xz | xzcat | tar -xf -
# grep -A5 -B5 specs debian/rules 
	$(if $(with_lto),$(foreach i,-flto -fuse-linker-plugin -ffat-lto-objects,-e 's/$(i)//g')) \
	-e '/^OPT/s,-O3,-O2,' \
	-e 's/-O3/-O2/g' \
	-e 's/-fprofile-use *-fprofile-correction//g' \
	-e 's/-fstack-protector /-fstack-protector-strong /g' \
	-e 's/-specs=[^ ]*//g' \
	-e 's/-fdebug-prefix-map=[^ ]*//g' \
	-e 's,^RUNSHARED *=.*,RUNSHARED=,' \
	-e '/BLDLIBRARY/s/-L\. //'

ifeq ($(derivative),Ubuntu)
# 
```

**Pull request merged**
