### PR TITLE
Refactoring conditional directives for incomplete if conditions and else if wrappers.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by jpereira** [comment]
Hi @wmarquesr,

TBH, I can't figure out some gain about that... It's code! if you're was able to understand the old-code and change.... It's the prove that code is 'ok'!

p.s: I saw some others pull-request that you are proposing the samething about the refactoring based on Kernel/ifdef style. what's idea? is it like a Religion? :)

**Comment by flaviommedeiros** [comment]
The idea is always to encompass only complete/entire statements/expressions with preprocessor conditional directives. It is something that is getting popular in many different projects (started mainly on the Linux Kernel).

We agree totally that breaking statements with directives influences code quality, i.e., understanding, maintainability and error proneness. We found some evidence based on interviews with developers and an online survey regarding this negative effect on quality. 

- http://www.cs.cmu.edu/~ckaestne/pdf/ecoop15.pdf

Don't you agree with that, @jpereira?

**Comment by jpereira** [comment]
actually... I think unnecessary! but, you need to ask to @arr2036 and @alandekok about that!

**Comment by jpereira** [comment]
@flaviommedeiros congrats about your paper is very interesting (you're close to my hometown, Recife). 

These types of changes will implicate in changes in code-style/best-practices of the project. for me I think unnecessary! but, @arr2036 and @alandekok will decide that.

**Comment by alandekok** [comment]
Patches to fix the `ifdef`s are interesting.  Especially if they allow the code to be compiled and checked.

But for me, adding lots of "check_foo" variables doesn't help.  The `ifdef`s are still there, and it just became more difficult to see *why* a path is being taken.   `if (check_foo)` isn't that descriptive.  Having the actual checks in place (even if they are more complicated) is more understandable

**Comment by flaviommedeiros** [comment]
Thanks for the feedback, @jpereira and @alandekok. Please have a look at alternative ways of removing directives that break statements. They might be of your interest. 

- https://github.com/xrmx/uwsgi/commit/0bb9b0b1338cfe625a478c3c86b94a0467e02161
- https://github.com/balabit/syslog-ng/pull/810/files

**Comment by alandekok** [comment]
Yes, putting multiple checks into a well-named macro is better.

**Comment by jpereira** [comment]
@flaviommedeiros The example xrmx/uwsgi@0bb9b0b is different of proposed in this patch. much better than a lot of "bool checked_name ...."

**Comment by arr2036** [comment]
Thanks for the patch,  but it's generally better to ask a member of the project before putting effort into something as subjective as code styling.  I'm going to close this now,  you're welcome to continue the discussion.

**Pull request closed without merging**
