### PR TITLE
Fix SIGSEGV on exit when an EAP method is referenced (v3.0.x)

### PR DESCRIPTION
**Pull request by lytboris**
in multiple eap stansas, e.g.
===========================
eap instance1 {
	...
	md5 {
	}
	...
}
eap instance2 {
	...
	md5 {
	}
	...
}
===========================

Sponsored by: Yandex LLC

### CODE REVIEW

**Comment by alandekok** [comment]
I don't see why this is necessary.  The dlopen / dlclose API takes care of reference counting the handles.  From the "man" page for dlopen:

    A second call to dlopen() with the same path will return the same handle, but the internal reference
    count for the handle will be incremented.  Therefore all dlopen() calls should be balanced with a
    dlclose() call.

In this case, if `inst->handle == NULL`, then something *else* has gone through and smashed the `inst` structure.

**Comment by lytboris** [comment]
I tracked it down. My patch IS correct. Take a look on
https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/src/modules/rlm_eap/eap.c#L126

When module is loaded, no dlopen() is invoked and handle is left as 0x0. The only thing to fix for this patch is to fix the comment.

**Comment by arr2036** [comment]
Heh yeah, I guess that was added to support static compilation of EAP methods into rlm_eap.

**Comment by arr2036** [comment]
I think we still need to call the detach method though, that's probably per rlm_eap instance.  If we don't call it we leak memory on HUP

**Comment by lytboris** [comment]
detach pointer may reference freed memory when real rlm_eap_... method was unloaded previously invalidating type pointer.

**Pull request closed without merging**
