### PR TITLE
jlibtool: Fix generate of *.la file Closes #1433

### LINKED ISSUE #1433: Problems with current libtool *.la scheme
The current libfreeradius-radius.la scheme is a unrecognized archive. it's different of the documentation https://autotools.io/libtool/lafiles.html

```
[jpereira@jpereira-desktop mod_auth_radius.git]$ make
apxs -c -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1 -L/opt/radius-3.1.x/lib/ -Wl,-R/opt/radius-3.1.x/lib/ -lfreeradius-radius  mod_auth_radius.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1  -c -o mod_auth_radius.lo mod_auth_radius.c && touch mod_auth_radius.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -Wl,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now    -o mod_auth_radius.la -R/opt/radius-3.1.x/lib/  -L/opt/radius-3.1.x/lib/ -lfreeradius-radius -rpath /usr/lib/apache2/modules -module -avoid-version    mod_auth_radius.lo
libtool: link: `/opt/radius-3.1.x/lib//libfreeradius-radius.la' is not a valid libtool archive
apxs:Error: Command failed with rc=65536
.
Makefile:25: recipe for target '.libs/mod_auth_radius.so' failed
make: *** [.libs/mod_auth_radius.so] Error 1
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

```
[jpereira@jpereira-desktop mod_auth_radius.git]$ cat /opt/radius-3.1.x/lib/libfreeradius-radius.la 
/opt/radius-3.1.x/lib
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

btw, sure! works fine when i use explicit library like: ```-l:libfreeradius-radius.so```

```
[jpereira@jpereira-desktop mod_auth_radius.git]$ make
apxs -c -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1 -L/opt/radius-3.1.x/lib/ -Wl,-R/opt/radius-3.1.x/lib/ -l:libfreeradius-radius.so  mod_auth_radius.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1  -c -o mod_auth_radius.lo mod_auth_radius.c && touch mod_auth_radius.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -Wl,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now    -o mod_auth_radius.la -R/opt/radius-3.1.x/lib/  -L/opt/radius-3.1.x/lib/ -l:libfreeradius-radius.so -rpath /usr/lib/apache2/modules -module -avoid-version    mod_auth_radius.lo
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

### PR DESCRIPTION
**Pull request by jpereira**
Currently, the scripts/jlibtool generates a wrong *.la files that prevent the use it. 

e.g:

```
[jpereira@jpereira-desktop mod_auth_radius.git]$ make
apxs -c -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1 -L/opt/radius-3.1.x/lib/ -Wl,-R/opt/radius-3.1.x/lib/ -lfreeradius-radius  mod_auth_radius.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1  -c -o mod_auth_radius.lo mod_auth_radius.c && touch mod_auth_radius.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -Wl,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now    -o mod_auth_radius.la -R/opt/radius-3.1.x/lib/  -L/opt/radius-3.1.x/lib/ -lfreeradius-radius -rpath /usr/lib/apache2/modules -module -avoid-version    mod_auth_radius.lo
libtool: link: `/opt/radius-3.1.x/lib//libfreeradius-radius.la' is not a valid libtool archive
apxs:Error: Command failed with rc=65536
.
Makefile:25: recipe for target '.libs/mod_auth_radius.so' failed
make: *** [.libs/mod_auth_radius.so] Error 1
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

The generate *.la file is invalid (more about *.la in https://autotools.io/libtool/lafiles.html)
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ cat /opt/radius-3.1.x/lib/libfreeradius-radius.la 
/opt/radius-3.1.x/lib
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

The idea of this patch is to add the feature to be compatible with expected by gcc. 

```
[jpereira@jpereira-desktop freeradius-server.git]$ cat /opt/radius-3.1.x/lib/libfreeradius-radius.la
# Generated by jlibtool 1.4
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libfreeradius-radius.so'

# Libraries that this one depends upon.
dependency_libs='-lpcap -lreadline -lpthread -ldl -lresolv -lnsl -lrt -lcap -lpcre -ltalloc -lssl-lcrypto'

# Names of this library.
library_names='libfreeradius-radius.so'

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='/opt/radius-3.1.x/lib'
[jpereira@jpereira-desktop freeradius-server.git]$

[jpereira@jpereira-desktop freeradius-server.git]$ cat /opt/radius-3.1.x/lib/libfreeradius-redis.la
# Generated by jlibtool 1.4
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libfreeradius-redis.so'

# Libraries that this one depends upon.
dependency_libs='-lhiredis'

# Names of this library.
library_names='libfreeradius-redis.so'

# Is this an already installed library?
installed=yes
# Should we warn about portability when linking against -modules?
shouldnotlink=no

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='/opt/radius-3.1.x/lib'
[jpereira@jpereira-desktop freeradius-server.git]$
```

expected build!
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ make
apxs -c -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1 -L/opt/radius-3.1.x/lib/ -Wl,-R/opt/radius-3.1.x/lib/ -lfreeradius-radius  mod_auth_radius.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -I/opt/radius-3.1.x/include -DHAVE_PTHREAD_H -DWITH_THREADS=1  -c -o mod_auth_radius.lo mod_auth_radius.c && touch mod_auth_radius.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -Wl,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now    -o mod_auth_radius.la -R/opt/radius-3.1.x/lib/  -L/opt/radius-3.1.x/lib/ -lfreeradius-radius -rpath /usr/lib/apache2/modules -module -avoid-version    mod_auth_radius.lo
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

### CODE REVIEW

**Comment by alandekok** [comment]
Are the build failures a result of the patch, or are they pre-existing?

Given that the autotools.io page says that the .la files are not really used or needed, I think the preferred approach would be to just not install the .la files.

Though if this patch works / builds / passes travis... I'm inclined to pull it in just as a "screw you" to the libtool people.

**Comment by arr2036** [comment]
I can see this being useful... If you git pull --rebase and force push, we can see if the issues are because of this patch or because of a pre-existing issue.

**Comment by arr2036** [comment]
@jpereira any progress on this?  Would be one of the more useful patches you've submitted ;)

**Comment by alandekok** [comment]
The patch works for me on OSX.

Maybe Linux is doing something weird, and getting excited over the la files?

**Comment by alandekok** [comment]
OK, I see the error on Ubuntu 14.04

**Comment by alandekok** [comment]
Commit 0d94624 fixes the underlying issue.

**Comment by jpereira** [comment]
sorry for delay... I am out on vacation, backing only Jan/22

**Comment by pwdng** [comment]
This change has broken the jlibtool link mode. The load_install_path function reads the .la file and expects it to only contain the libdir path. I've submitted a pull request to fix this: https://github.com/FreeRADIUS/freeradius-server/pull/1491

**Pull request merged**
