### PR TITLE
new vendor support

### PR DESCRIPTION
**Pull request by towingie**
- added dictionary for rcntec's RPCM hardware

### CODE REVIEW

**Comment by jpereira** [comment]
@towingie You are missing to include it into `share/dictionary/radius/dictionary`

**Comment by towingie** [comment]
> @towingie You are missing to include it into `share/dictionary/radius/dictionary`

Thanks! added!

**Comment by jpereira** [comment]
@towingie If you have access to the _RPCM hardware_ equipment documentation. please, update it with all existing attributes.

**Comment by towingie** [comment]
@jpereira this two (RCNTEC-RPCM-Group and RCNTEC-RPCM-Session-Expire) is all of supported for now.

**Pull request merged**
