### PR TITLE
Backport winbind module config

### PR DESCRIPTION
**Pull request by spaetow**
It never existed in the 3.0.x branch, only 3.1.x and 4.0.x.

### CODE REVIEW

**Comment by alandekok** [comment]
Except that rlm_winbind doesn't exist in the v3.0.x branch?

**Comment by spaetow** [comment]
ARGH!

**Comment by alanbuxey** [comment]
yep - native winbind exists in 3.0.x for mschap module... the PAP stuff
with rlm_winbind is 3.1.x and higher (and one of the few reasons to be
running 3.1.x in production :) )

**Comment by spaetow** [comment]
@alanbuxey except 3.1.x is not being taken forward (and has in fact been deleted from Github), so any bug fixes in 3.0.x are not pulled along.

**Comment by mcnewton** [comment]
Don't use v3.1.x any more. None of the latest security updates (and there were a lot) were pulled across, which is why it was deleted.

**Comment by alanbuxey** [comment]
..dont use 3.1.x - dont use 4.x - so lose all features and only have 3.0.x
?  :(

**Comment by arr2036** [comment]
The major refactoring is mostly done on v4.0.x now, it's probably safe to start playing around with it again.

**Comment by arr2036** [comment]
Or.. at least the configuration structure won't change much between now and the release.

**Pull request closed without merging**
