### PR TITLE
Update dependencies path in configure script

### PR DESCRIPTION
**Pull request by nqb**

### CODE REVIEW

**Comment by alandekok** [comment]
Please sign commits.  It help with code attribution.

**Comment by jpereira** [comment]
It should be changed also in `configure.ac`

**Comment by arr2036** [comment]
and you need to rebase and force push your commits

**Comment by nqb** [comment]
Thanks a lot for your comments and help. That should be fine now.

**Comment by arr2036** [comment]
Could you squash those commits into 1? ``git rebase -i HEAD~3`` and correct as appropriate.

**Pull request closed without merging**
