### PR TITLE
Create relative symlinks so that the source tree can be shared across several hosts to be accessed remotely

### PR DESCRIPTION
**Pull request by mkhon**

### CODE REVIEW

**Comment by alandekok** [comment]
I'll merge this, but the build system needs many more changes in order to have multiple builds from one source tree.

**Comment by arr2036** [comment]
What's the use case?

**Comment by mkhon** [comment]
> What's the use case?

vagrant or multipass (source code is in a vagrant or multipass VM, code editor on laptop)

**Comment by arr2036** [comment]
Ah fair enough.

**Pull request merged**
