### PR TITLE
Add pcap support

### PR DESCRIPTION
**Pull request by pwdng**

### CODE REVIEW

**Comment by jpereira** [comment]
This feature sounds great!

**Comment by jpereira** [comment]
@arr2036 This inspires a new feature to be possible listen from a fifo-file.

**Comment by pwdng** [comment]
It's main purpose is for the DHCP server.
It lets us listen to broadcast traffic on BSD systems that won't let us bind to an interface.

**Comment by arr2036** [comment]
As a general rule, any new functions going in should have doxygen headers too. It's a lot of work to go back a fix all the functions without headers (though we are slowly), but it's less work to ensure the problem doesn't get worse.

**Comment by arr2036** [comment]
@pwdng Looks good, but can you squish it into the previous commits so that we can see the code overall, thanks!

**Pull request merged**
