### PR TITLE
Fix the 'python_path' (rlm_python3)

### PR DESCRIPTION
**Pull request by jpereira**
Backport from rlm_python (#3184) changes to rlm_python3

### CODE REVIEW

**Comment by jpereira** [comment]
It's a backport from #3184 to v3/rlm_python3. 

1. The default `python_path` set.

```
$ grep python_path $raddb/mods-available/python
python_path="${modconfdir}/${.:name}:/lets/go/to/there"
$
```

2. Python function used in `$raddb/mods-config/python/example.py` to print out the content of `sys.version` and `sys.path`.

```python
def instantiate(p):
  try:
    import sys
    import pprint

    print("example.py: Python Version: {}".format(sys.version.replace("\n", "")))
    print("example.py: Output of sys.path: ")
    pprint.pprint(sys.path)

    return radiusd.RLM_MODULE_OK
  except Exception as err:
    print(Exception, err)
```

# Therefore, we have the tests: (Pay attention that now we could see the default _path_ with the other ones configured with `python_path`)

## Python 3.5.x

```
$ pyenv local 3.5.8
$ eval "$(pyenv init -)"
$ ./configure ...  --with-rlm-python3-config-bin=python3.5-config
$ make
```

testing

```
...
example.py: Python Version: 3.5.8 (default, Dec  5 2019, 18:50:51) [GCC Clang 9.0.0 (tags/RELEASE_900/final)]
example.py: Output of sys.path:
['/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python35.zip',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5/plat-darwin',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5/lib-dynload',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5/site-packages',
 'raddb//mods-config/python3',
 '/lets/go/to/there']
...
```

## Python 3.6.x

build

```
$ pyenv local 3.6.9
$ eval "$(pyenv init -)"
$ ./configure ...  --with-rlm-python3-config-bin=python3.6-config
$ make
```

testing

```
...
example.py: Python Version: 3.6.9 (default, Dec  5 2019, 17:27:02) [GCC Clang 9.0.0 (tags/RELEASE_900/final)]
example.py: Output of sys.path:
['/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python36.zip',
 '/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python3.6',
 '/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python3.6/lib-dynload',
 '/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python3.6/site-packages',
 'raddb//mods-config/python3',
 '/lets/go/to/there']
...
```

## Python 3.7,x

build

```
$ pyenv local 3.7.5
$ eval "$(pyenv init -)"
$ ./configure ...  --with-rlm-python3-config-bin=python3.7-config
$ make
```

testing

```
...
example.py: Python Version: 3.7.5 (default, Dec  5 2019, 17:33:31) [Clang 9.0.0 (tags/RELEASE_900/final)]
example.py: Output of sys.path:
['/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python37.zip',
 '/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python3.7',
 '/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python3.7/lib-dynload',
 '/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python3.7/site-packages',
 'raddb//mods-config/python3',
 '/lets/go/to/there']
...
```

**Comment by jpereira** [comment]
It's a backport from #3184 to v3/rlm_python3. 

1. The default `python_path` set.

```
$ grep python_path $raddb/mods-available/python3
python_path="${modconfdir}/${.:name}:/lets/go/to/there"
$
```

2. Python function used in `$raddb/mods-config/python3/example.py` to print out the content of `sys.version` and `sys.path`.

```python
def instantiate(p):
  try:
    import sys
    import pprint

    print("example.py: Python Version: {}".format(sys.version.replace("\n", "")))
    print("example.py: Output of sys.path: ")
    pprint.pprint(sys.path)

    return radiusd.RLM_MODULE_OK
  except Exception as err:
    print(Exception, err)
```

Therefore, we have the tests: (Pay attention that now we could see the default path (`sys.path`) with the other ones configured in `python_path`)

## Python 3.5.x

```
$ pyenv local 3.5.8
$ eval "$(pyenv init -)"
$ ./configure ...  --with-rlm-python3-config-bin=python3.5-config
$ make
```

testing

```
...
example.py: Python Version: 3.5.8 (default, Dec  5 2019, 18:50:51) [GCC Clang 9.0.0 (tags/RELEASE_900/final)]
example.py: Output of sys.path:
['/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python35.zip',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5/plat-darwin',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5/lib-dynload',
 '/Volumes/Users/jpereira/.pyenv/versions/3.5.8/lib/python3.5/site-packages',
 'raddb//mods-config/python3',
 '/lets/go/to/there']
...
```

## Python 3.6.x

build

```
$ pyenv local 3.6.9
$ eval "$(pyenv init -)"
$ ./configure ...  --with-rlm-python3-config-bin=python3.6-config
$ make
```

testing

```
...
example.py: Python Version: 3.6.9 (default, Dec  5 2019, 17:27:02) [GCC Clang 9.0.0 (tags/RELEASE_900/final)]
example.py: Output of sys.path:
['/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python36.zip',
 '/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python3.6',
 '/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python3.6/lib-dynload',
 '/Volumes/Users/jpereira/.pyenv/versions/3.6.9/lib/python3.6/site-packages',
 'raddb//mods-config/python3',
 '/lets/go/to/there']
...
```

## Python 3.7,x

build

```
$ pyenv local 3.7.5
$ eval "$(pyenv init -)"
$ ./configure ...  --with-rlm-python3-config-bin=python3.7-config
$ make
```

testing

```
...
example.py: Python Version: 3.7.5 (default, Dec  5 2019, 17:33:31) [Clang 9.0.0 (tags/RELEASE_900/final)]
example.py: Output of sys.path:
['/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python37.zip',
 '/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python3.7',
 '/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python3.7/lib-dynload',
 '/Volumes/Users/jpereira/.pyenv/versions/3.7.5/lib/python3.7/site-packages',
 'raddb//mods-config/python3',
 '/lets/go/to/there']
...
```

**Comment by jpereira** [comment]
@geaaru, The fix about rlm_python3 is here.

**Comment by geaaru** [comment]
It's broken from my side:
```
$ git status . 
On branch v3/python3-3180
Your branch is up to date with 'jpereira/v3/python3-3180'.
```
This the ldflags/cflags used:
```
configure: python3.6-config's cflags were "-I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -O2 -march=x86-64 -pipe -fwrapv -DNDEBUG "
configure: Sanitized cflags were "-isystem/usr/include/python3.6m -isystem/usr/include/python3.6m    -march=x86-64 -pipe -fwrapv "
configure: python3.6-config's ldflags were "-L/usr/lib64 -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic}"
configure: Sanitized ldflags were "-L/usr/lib64 -lpython3.6m -lpthread -ldl -lutil -lm "
```

But let me clarify my first error. In the previous post `python_path` it was empty for another issue :)

If it's used a different `confdir`  and then on instance file is used:
```
$INCLUDE ${confdir}/mods-enabled
```
`confdir` is not resolved and for this reason it was used wrong file. So, if I statically configure:
```
$INCLUDE test/mods-enable
```
then `python_path` is correctly configured:
```
Breakpoint 1, mod_instantiate (conf=0x5555557dc760, instance=0x5555558757e0) at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:1222
1222		inst->name = cf_section_name2(conf);
(gdb) p *inst
$4 = {
  name = 0x0, 
  sub_interpreter = 0x0, 
  python_path = 0x555555875f40 "/tmp/radius/usr/etc/raddb//mods-config/python3:/usr/lib64/python3.6", 
  module = 0x0, 
  cext_compat = true, 
  instantiate = {
    module = 0x0, 
    function = 0x0, 
    module_name = 0x555555875a00 "example", 
    function_name = 0x0
  }, 
```

However, I continue to have the same issue, `pFunc` is NULL:

```
Breakpoint 2, do_python_single (request=0x0, pFunc=0x0, funcname=0x7ffff7bc93ae "instantiate", pass_all_vps=false, pass_all_vps_dict=true) at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:483
483		PyObject	*pArgs = NULL;
(gdb) bt
#0  do_python_single (request=0x0, pFunc=0x0, funcname=0x7ffff7bc93ae "instantiate", pass_all_vps=false, pass_all_vps_dict=true) at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:483
#1  0x00007ffff7bc754b in mod_instantiate (conf=0x5555557dc760, instance=0x5555558757e0) at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:1257
#2  0x00005555555822d3 in module_instantiate (modules=0x5555557d33c0, askedname=0x5555557dc860 "python3") at /home/geaaru/Projects/freeradius-server/src/main/modules.c:761
#3  0x0000555555584ec6 in modules_init (config=0x5555555eb690) at /home/geaaru/Projects/freeradius-server/src/main/modules.c:2146
#4  0x000055555558dff0 in main (argc=8, argv=0x7fffffffd258) at /home/geaaru/Projects/freeradius-server/src/main/radiusd.c:520
```

A possible cause maybe could be related to this?

```diff
diff --git a/src/modules/rlm_python3/config.h.in b/src/modules/rlm_python3/config.h.in
index 64b950d728..f80de9c383 100644
--- a/src/modules/rlm_python3/config.h.in
+++ b/src/modules/rlm_python3/config.h.in
@@ -1,8 +1,5 @@
 /* config.h.in.  Generated from configure.ac by autoheader.  */
 
-/* Define to 1 if you have the `dl_iterate_phdr' function. */
-#undef HAVE_DL_ITERATE_PHDR
-
 /* Define to the address where bug reports for this package should be sent. */
 #undef PACKAGE_BUGREPORT

```

What is the value of your HAVE_DL_ITERATE_PHDR define?

**Comment by jpereira** [comment]
@geaaru well, this patch doesn't look to be ours. please, drop it and perform the test again.

**Comment by geaaru** [comment]
FYIK the config.h.in is the file update by ./autogen.sh. I think that in Gentoo this symbol is present and for this reason `autogen.sh` try to update it.

Can you check if your env where you run tests contains this symbol?
```
$ objdump -Tt /lib64/libc.so.6 | grep dl_iterate_phdr
0000000000147590  w   DF .text	00000000000001f1  GLIBC_2.2.5 dl_iterate_phdr
```

Gentoo/Sabayon uses glibc-2.29.

However, same result without that change.

Take a look on this:
```
(gdb) p inst->instantiate
$6 = {
  module = 0x0, 
  function = 0x0, 
  module_name = 0x555555875a00 "example", 
  function_name = 0x0
}
(gdb) bt
#0  mod_instantiate (conf=0x5555557dc760, instance=0x5555558757e0) at /home/geaaru/Projects/freeradius-server/src/modules/rlm_python3/rlm_python3.c:1257
#1  0x00005555555822d3 in module_instantiate (modules=0x5555557d33c0, askedname=0x5555557dc860 "python3") at /home/geaaru/Projects/freeradius-server/src/main/modules.c:761
#2  0x0000555555584ec6 in modules_init (config=0x5555555eb690) at /home/geaaru/Projects/freeradius-server/src/main/modules.c:2146
#3  0x000055555558dff0 in main (argc=8, argv=0x7fffffffd258) at /home/geaaru/Projects/freeradius-server/src/main/radiusd.c:520
```

It seems that `inst->instantiate.function` is not initialized correctly.

**Comment by jpereira** [comment]
@geaaru Please, copy/paste your `raddb/mods-enabled/python3` here.

**Comment by geaaru** [comment]
I understood. See https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-available/python3#L31 , all func_* are commented! :)

Please, add an if [here](https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/modules/rlm_python3/rlm_python3.c#L1260):

```diff
diff --git a/src/modules/rlm_python3/rlm_python3.c b/src/modules/rlm_python3/rlm_python3.c
index 9f78011e35..1e809a0199 100644
--- a/src/modules/rlm_python3/rlm_python3.c
+++ b/src/modules/rlm_python3/rlm_python3.c
@@ -1254,12 +1254,14 @@ static int mod_instantiate(CONF_SECTION *conf, void *instance)
 	/*
 	 *	Call the instantiate function.
 	 */
-	code = do_python_single(NULL, inst->instantiate.function, "instantiate", inst->pass_all_vps, inst->pass_all_vps_dict);
-	if (code < 0) {
-	error:
-		python_error_log();	/* Needs valid thread with GIL */
-		PyEval_SaveThread();
-		return -1;
+	if (inst->instantiate.function) {
+		code = do_python_single(NULL, inst->instantiate.function, "instantiate", inst->pass_all_vps, inst->pass_all_vps_dict);
+		if (code < 0) {
+		error:
+			python_error_log();	/* Needs valid thread with GIL */
+			PyEval_SaveThread();
+			return -1;
+		}
 	}
 	PyEval_SaveThread();
```

```

**Comment by jpereira** [comment]
@geaaru Don't need the extra `if()`, because the `do_python_single()` is checking the parameter. btw, I've performed the test against the Python 3.6 over Ubuntu 18.04 as can be seen below.

Linux env.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
$ python3.6 --version
Python 3.6.9
$ git status
On branch v3/python-3180
Your branch is up to date with 'origin/v3/python-3180'.

nothing to commit, working tree clean
$
```

Build

```
$ ./configure \
    --with-rlm-python3-config-bin=/usr/bin/x86_64-linux-gnu-python3.6m-config
$ make
``` 

Tests

1. Python3 example.py

```
$ cat raddb/mods-config/python3/example.py
#! /usr/bin/env python3

import radiusd

def instantiate(p):
  try:
    import sys
    import pprint

    print("example.py: Python Version: {}".format(sys.version.replace("\n", "")))
    print("example.py: Output of sys.path: ")
    pprint.pprint(sys.path)

    return radiusd.RLM_MODULE_OK
  except Exception as err:
    print(Exception, err)
$
```

2. rlm_python3 configuration

```
$ cat raddb/mods-enabled/python3
 python3 {
 	python_path="${modconfdir}/${.:name}:/another_path/to/python_files"
	module = example

	mod_instantiate = ${.module}
	func_instantiate = instantiate
}
$
```

3. Execution. (pay attention to see the content of `python_path` added with the default directories)

```
Tue Dec 10 17:57:37 2019 : Debug:   # Instantiating module "python3" from file raddb//mods-enabled/python3
Tue Dec 10 17:57:37 2019 : Info: Python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
example.py: Python Version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
example.py: Output of sys.path:
['/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages',
 'raddb//mods-config/python3',
 '/another_path/to/python_files']

```

I am pretty sure that your Gentoo setup has something wrong. I encourage you to perform the tests isolated as I did. (if you don't have the `python3-config`, it is necessary to inform trough the option `--with-rlm-python3-config-bin`)

**Comment by geaaru** [comment]
My issue happens if you comment:
```
# func_instantiate = instantiate
```
is not related to Gentoo but to the code. In `do_python_single` there isn't a check about `pFunc` parameter. It's only present in `do_python` function.

**Comment by geaaru** [comment]
Probably this is better:
```diff
diff --git a/src/modules/rlm_python3/rlm_python3.c b/src/modules/rlm_python3/rlm_python3.c
index 9f78011e35..12b5fc447d 100644
--- a/src/modules/rlm_python3/rlm_python3.c
+++ b/src/modules/rlm_python3/rlm_python3.c
@@ -485,6 +485,8 @@ static rlm_rcode_t do_python_single(REQUEST *request, PyObject *pFunc, char cons
 	int		ret;
 	int 		i;
 
+	if (!pFunc) return RLM_MODULE_NOOP;
+
 	/* Default return value is "OK, continue" */
 	ret = RLM_MODULE_OK;
 
```

**Comment by jpereira** [comment]
Ok, we will see it.

but, have you got success to perform the tests against Python 3 using the sample importing any default library? e.g: `import pprint`?

**Comment by geaaru** [comment]
It seems ok now. I also tested a builtin import:
```python
def instantiate(p):
  print("*** instantiate ***")
  import uuid

  print(uuid.uuid4())
  # return 0 for success or -1 for failure
  try:
    import sys
    import pprint

    print("example.py: Python Version: {}".format(sys.version.replace("\n", "")))
    print("example.py: Output of sys.path: ")
    pprint.pprint(sys.path)

    return radiusd.RLM_MODULE_OK
  except Exception as err:
    print(Exception, err)
```
and it works:
```
Tue Dec 10 19:29:27 2019 : Info: Python version: 3.6.9 (default, Oct 29 2019, 20:41:01)  [GCC 8.2.0]
*** instantiate ***
[Detaching after fork from child process 102140]
97dfb2b8-61b8-424d-87b1-1a17abb241b0
example.py: Python Version: 3.6.9 (default, Oct 29 2019, 20:41:01) [GCC 8.2.0]
example.py: Output of sys.path: 
['/usr/lib64/python36.zip',
 '/usr/lib64/python3.6',
 '/usr/lib64/python3.6/lib-dynload',
 '/usr/lib64/python3.6/site-packages',
 '/tmp/radius/usr/etc/raddb//mods-config/python3',
 '/usr/lib64/python3.6']

```

I will test and open the issue about parsing of custom `modsconfdir` but from my side python3 works. I will test better tomorrow but it seems OK. :+1:

**Comment by jpereira** [comment]
@geaaru About that, it was fixed in https://github.com/FreeRADIUS/freeradius-server/pull/3194

Thank you for the feedback.

> Probably this is better:
> 
> ```diff
> diff --git a/src/modules/rlm_python3/rlm_python3.c b/src/modules/rlm_python3/rlm_python3.c
> index 9f78011e35..12b5fc447d 100644
> --- a/src/modules/rlm_python3/rlm_python3.c
> +++ b/src/modules/rlm_python3/rlm_python3.c
> @@ -485,6 +485,8 @@ static rlm_rcode_t do_python_single(REQUEST *request, PyObject *pFunc, char cons
>  	int		ret;
>  	int 		i;
>  
> +	if (!pFunc) return RLM_MODULE_NOOP;
> +
>  	/* Default return value is "OK, continue" */
>  	ret = RLM_MODULE_OK;
>  
> ```

**Pull request merged**
