### PR TITLE
dhcp - interface / raw socket mode - fixup

### PR DESCRIPTION
**Pull request by nchaigne**
At some point this was working (actually on 3.0.x, I'm not sure this
ever built on 3.1.x), but it broke a long time ago. Nobody noticed since
the relevant define was not set by autoconf...

### CODE REVIEW

**Comment by nchaigne** [comment]
Damn... it doesn't build when pcap and if_packet are both available.
So, let's see, we have to handle:
- no pcap, no if_packet
- pcap, no if_packet
- no pcap, if_packet
- pcap and if_packet

Seems overly complicated :'(

**Comment by nchaigne** [comment]
Now Travis complains about the rest module, I did not have this before.
Not related to dhcp anyway...

src/modules/rlm_rest/rest.c:2014:2: error: the address of ‘timeout’ will always evaluate as ‘true’ [-Werror=address]

**Comment by arr2036** [comment]
Fixed a large number of these just now. Grr. Looks like autoheader/autoconf wasn't run before submitting the pull request, which masked a significant number of issues in the code.  I think all your fixes are covered in the commit I just did, if not, please could you open another PR for the remaining ones.

Cheers!

**Comment by nchaigne** [comment]
It doesn't build if you don't have pcap. The following defines (in src\modules\proto_dhcp\dhcp.c) are required to build with raw sockets:

#ifdef HAVE_PCAP_H
#define ETH_TYPE_IP    0x0800
#define IP_HDR_SIZE    20
#define UDP_HDR_SIZE   8
#define ETH_ADDR_LEN   6
#endif

If you remove the #ifdef / #endif around those, build works.

**Comment by arr2036** [comment]
I guess it's ifdef HAVE_PCAP_H or the linux raw socket header

**Comment by arr2036** [comment]
(clang on OSX complains if there are unused macros now)

**Comment by arr2036** [comment]
Ok, done

**Comment by nchaigne** [comment]
It works again, thanks :)

There's a minor issue with DEBUG: the macro does not add a "\n". Some uses of DEBUG add a "\n", some don't.

I see that radclient's DEBUG macro adds a "\n". Maybe dhcpclient should also.

**Comment by arr2036** [comment]
Yeah in general the macro should add the new line.  If you need multiline output, call the macro multiple times :)

I think the only place where that's ever been an issue is in the SQL drivers, the PG and MySQL client libraries love to produce all kinds of weird intermixed errors, with server errors and client errors and network errors *sigh*.

**Pull request closed without merging**
