### PR TITLE
Fix _dict_from_file() allowing relative file.

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
e.g: It allows to call `fr_dict_read(_d, NULL, dict_file)` then without sigsegv with stlren() due to empty dir_name.

```
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff7b89c1c in _dict_from_file (ctx=0x7fffffffe2d0, dir_name=0x0, 
    filename=0x55555575de50 "/opt/freeradius4/share/freeradius/dictionary/tacacs/dictionary", src_file=0x0, src_line=0x0)
    at src/lib/util/dict.c:4551
```

**Comment by jpereira** [comment]
1. Fixing the fr_dict_read() as supposed to accept relative path.

```
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff7b89c1c in _dict_from_file (ctx=0x7fffffffe2d0, dir_name=0x0, 
    filename=0x55555575de50 "/opt/freeradius4/share/freeradius/dictionary/tacacs/dictionary", src_file=0x0, src_line=0x0)
    at src/lib/util/dict.c:4551
``` 

2. Fixing the radict dict calls.

**Comment by alandekok** [comment]
I've pushed a separate fix.  I think it's better to leave `fr_dict_read()` the way it is.

The patch to `radict.c` uses `dict_file` after it's been freed.

**Comment by alandekok** [comment]
I've pushed more fixes.  `fr_dict_read()` is the wrong function to use.

**Pull request closed without merging**
