### PR TITLE
Check the CVE ID, not the name

### PR DESCRIPTION
**Pull request by TheMysteriousX**
I think the ID is intended to be checked, not the name.

### CODE REVIEW

**Comment by alandekok** [comment]
And pulled over to v4.0.x, too.

**Comment by arr2036** [comment]
The comment in the code says newest first, but the new issues were added newest last which breaks the acknowledgement check.

**Comment by alandekok** [comment]
The comments in the code also said it looped over all CVEs, but the loop had a hard-coded check against entry[0].

I'll push a fix.

**Comment by arr2036** [comment]
In you read the code that's actually not true.  It did check all the defects, but it only checked to see if the first entry has been acknowledged.

	https://github.com/FreeRADIUS/freeradius-server/blob/a02b1725cba0119e31b5d4039ed3b2b42ed1ad25/src/main/tls/global.c

Which works find if all the defects are on the same branch, but it doesn't work when the defects are on multiple branches.

**Pull request merged**
