### PR TITLE
After removing a vp, if removed element was cursor->found it should b…

### PR DESCRIPTION
**Pull request by pwdng**
…e set to null, not current

### CODE REVIEW

**Comment by arr2036** [comment]
No, that's wrong.  That would mean you started searching from the start of the cursor, why would you want that behaviour?

**Comment by pwdng** [comment]
What I'm trying to solve is when fr_cursor_next_by_xxx gets called after fr_cursor_remove, cursor->found points to the vp after the one that was deleted and in fr_cursor_next_by_xxx, if cursor->found exists, we start iterating from cursor->found->next. The vp at cursor->found therefore gets skipped.
Where would it cause the search to restart from the cursor start?

**Comment by arr2036** [comment]
In the case you remove any attribute whilst you're iterating with fr_cursor_next_by_xxx.

**Comment by arr2036** [comment]
cursor->found should be set to the attribute before the one removed, or NULL if no attributes exist

**Comment by arr2036** [comment]
``if (vp == cursor->found) cursor->found = before;``

Actually, looking through the code your original patch would work, but it's confusing.

**Pull request merged**
