### PR TITLE
Updating trustrouter.c to OpenSSL 1.1.0 compatibility

### PR DESCRIPTION
**Pull request by spaetow**
Fixing the DH portions in the trust router client code to conform with OpenSSL 1.1.0 requirements.

### CODE REVIEW

**Comment by spaetow** [comment]
Have just built this on a Fedora 26 system with TR 3.0.2 libs rebuilt for OpenSSL 1.1.0 and trustrouter.c builds ok! 👍

**Comment by alandekok** [comment]
I've done I've pushed a fix with all changes squashed into one.  If this works for you, I'll push out 3.0.16 later this week.

**Comment by alandekok** [comment]
Fixed.

**Comment by spaetow** [comment]
Argh! How did that # go missing! Thank you, Alan!

**Pull request closed without merging**
