### PR TITLE
Add Lantronix dictionary

### PR DESCRIPTION
**Pull request by zi0r**
Add Lantronix's dictionary

### CODE REVIEW

**Comment by arr2036** [comment]
*sigh* really?  Don't suppose you're employed at Lantronix are you?

**Comment by zi0r** [comment]
No I do not work at Lantronix.  I am playing with one of their devices.  I know the dictionary is stupid, but it is what they provided.

**Comment by arr2036** [comment]
Yeah it's total crap *sigh*.  Merged to v3.0.x and v3.1.x.

**Comment by jpereira** [comment]
This was the best-crap dictionary ever!

**Comment by jpereira** [comment]
This was the best-crap dictionary ever!

from the documentation http://www.lantronix.com/wp-content/uploads/pdf/SLC8000_UG.pdf

```
...................
RADIUS servers will need to be configured to support the Lantronix Vendor-Specific Attribute. For
example, on a FreeRADIUS server, the dictionary will need be updated with the Lantronix
definition by including the contents below in a file named dictionary.lantronix, and including it in the
RADIUS server dictionary definitions by adding the appropriate $INCLUDE directive to the main
dictionary file.
# dictionary.lantronix
#
# Lantronix SLC Console Manager
# Provides SLC-specific user attributes
#
VENDOR Lantronix 244
BEGIN-VENDOR Lantronix
ATTRIBUTE Lantronix-User-Attributes 1 string
END-VENDOR Lantronix
Once this is complete, the users file can be updated to include the Lantronix VSA for any user:
myuser Auth-Type := Local, User-Password == "myuser_pwd"
 Reply-Message = "Hello, %u",
 Lantronix-User-Attributes = "data 1-4 listen 1-6 clear 1-4
 group power" 
```

**Pull request merged**
